/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type LabelPrinterSettingsVariables = Record<string, never>;

export type LabelPrinterSettingsResult = {
  labelPrinterSettings: {
  address: string;
  port: number;
  labelHeight: number;
  labelWidth: number;
} | null;
};

export const LabelPrinterSettings = {
  query: "query labelPrinterSettings {\n  labelPrinterSettings {\n    address\n    port\n    labelHeight\n    labelWidth\n  }\n}",
} as TypedDocument<LabelPrinterSettingsResult, LabelPrinterSettingsVariables>;
