import { t } from '../../intl';
import type { LocaleKey } from '../../intl';
import type { UserPermission } from '../../store/storeContext';

// The prescription-request status vocabulary and its gates
// (spec/prescription-requests/rules.md § the lifecycle, § editability, §
// deletion). Pure — the screens read these; the server is the real guard.

/** The statuses a request can hold (contract.md § the lifecycle). */
export type PrescriptionRequestStatus =
  'NEW' | 'READY_TO_DISPENSE' | 'DISPENSED';

// Narrow a wire value to the vocabulary, treating anything unexpected as the
// most locked-down state (the safe default).
export const asRequestStatus = (status: string): PrescriptionRequestStatus =>
  status === 'NEW' || status === 'READY_TO_DISPENSE' ? status : 'DISPENSED';

export const STATUS_LABEL_KEYS: Record<PrescriptionRequestStatus, LocaleKey> = {
  NEW: 'status.new',
  READY_TO_DISPENSE: 'status.ready-to-dispense',
  DISPENSED: 'status.dispensed',
};

export const statusLabel = (status: PrescriptionRequestStatus): string =>
  t(STATUS_LABEL_KEYS[status]);

/** Status → chip colour token (tokens.css --status-*). */
export const statusColour = (status: PrescriptionRequestStatus): string =>
  ({
    NEW: 'var(--status-new)',
    READY_TO_DISPENSE: 'var(--status-picked)',
    DISPENSED: 'var(--status-verified)',
  })[status];

/**
 * Everything — header, lines, deletion, the hand-over — is editable only
 * while New (rules § editability, § deletion; AC-N5/R3/D2).
 */
export const isEditable = (status: PrescriptionRequestStatus): boolean =>
  status === 'NEW';

/**
 * The lifecycle crumb steps (ui-surface S3 § status footer): New · Ready to
 * dispense · Dispensed, with recorded times feeding the history popover.
 */
export const statusSteps = (node: {
  createdDatetime: string;
  readyDatetime?: string | null;
  dispensedDatetime?: string | null;
}): { label: string; date?: string }[] => [
  { label: statusLabel('NEW'), date: node.createdDatetime },
  {
    label: statusLabel('READY_TO_DISPENSE'),
    date: node.readyDatetime ?? undefined,
  },
  {
    label: statusLabel('DISPENSED'),
    date: node.dispensedDatetime ?? undefined,
  },
];

export const statusIndex = (status: PrescriptionRequestStatus): number =>
  ({ NEW: 0, READY_TO_DISPENSE: 1, DISPENSED: 2 })[status];

/**
 * The dispensing permission the generated-dispensation back-link borrows
 * (contract § the hand-over). Named here so the gate and its reason travel
 * together.
 */
export const DISPENSATION_LINK_PERMISSION: UserPermission =
  'PRESCRIPTION_QUERY';

/**
 * Whether to look up the dispensation(s) generated by the hand-over
 * (ui-surface S3 § side panel, AC-R4).
 *
 * Two conditions, and both are needed:
 *
 * - **Past New** — there is nothing to find while the request is still
 *   editable, because the hand-over is what generates the dispensation.
 * - **Holding the dispensing read** — the lookup is an `invoices(type:
 *   PRESCRIPTION)` read, so it authorises on `PRESCRIPTION_QUERY`, which this
 *   vertical's own users need not hold (contract § permissions: this surface
 *   borrows nothing from dispensing). Asking without it answers Forbidden and
 *   raises the global permission-denied modal the instant the hand-over flips
 *   the status — issue #637. Not asking is also the honest answer for the
 *   section: a link that cannot open is not offered (D94), and the dispensing
 *   route is nav-gated on this same permission, so it could not open.
 *
 * The mirror of dispensing's own source-request gate (PrescriptionSidePanel).
 */
export const readsDispensations = (
  status: PrescriptionRequestStatus,
  hasPermission: (permission: UserPermission) => boolean
): boolean =>
  !isEditable(status) && hasPermission(DISPENSATION_LINK_PERMISSION);
