/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type PatientSearchFragment = {
  patient: {
  id: string;
  code: string;
  code2: string | null;
  name: string;
  firstName: string | null;
  lastName: string | null;
  gender: "FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY" | null;
  dateOfBirth: string | null;
  isDeceased: boolean;
};
  score: number;
};

export type PatientSearchVariables = {
  storeId: string;
  input: {
    code?: string | null;
    code2?: string | null;
    name?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    gender?: "FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY" | null;
    identifier?: string | null;
  };
};

export type PatientSearchResult = {
  patientSearch: ({
  __typename: "PatientSearchConnector";
} & {
  totalCount: number;
  nodes: Array<PatientSearchFragment>;
});
};

export const PatientSearch = {
  query: "query patientSearch($storeId: String!, $input: PatientSearchInput!) {\n  patientSearch(storeId: $storeId, input: $input) {\n    ... on PatientSearchConnector {\n      __typename\n      totalCount\n      nodes {\n        ...PatientSearch\n      }\n    }\n  }\n}\n\nfragment PatientSearch on PatientSearchNode {\n  patient {\n    id\n    code\n    code2\n    name\n    firstName\n    lastName\n    gender\n    dateOfBirth\n    isDeceased\n  }\n  score\n}",
} as TypedDocument<PatientSearchResult, PatientSearchVariables>;

export type CentralPatientSearchVariables = {
  storeId: string;
  input: {
    code?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
  };
};

export type CentralPatientSearchResult = {
  centralPatientSearch: ({
  __typename: "CentralPatientSearchConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  code2: string | null;
  firstName: string;
  lastName: string;
  gender: "FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY" | null;
  dateOfBirth: string | null;
  isDeceased: boolean;
}>;
}) | ({
  __typename: "CentralPatientSearchError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const CentralPatientSearch = {
  query: "query centralPatientSearch($storeId: String!, $input: CentralPatientSearchInput!) {\n  centralPatientSearch(storeId: $storeId, input: $input) {\n    __typename\n    ... on CentralPatientSearchConnector {\n      totalCount\n      nodes {\n        id\n        code\n        code2\n        firstName\n        lastName\n        gender\n        dateOfBirth\n        isDeceased\n      }\n    }\n    ... on CentralPatientSearchError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<CentralPatientSearchResult, CentralPatientSearchVariables>;

export type LinkPatientToStoreVariables = {
  storeId: string;
  nameId: string;
};

export type LinkPatientToStoreResult = {
  linkPatientToStore: ({
  __typename: "NameStoreJoinNode";
} & {
  id: string;
  nameId: string;
  storeId: string;
}) | ({
  __typename: "LinkPatientPatientToStoreError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const LinkPatientToStore = {
  query: "mutation linkPatientToStore($storeId: String!, $nameId: String!) {\n  linkPatientToStore(storeId: $storeId, nameId: $nameId) {\n    __typename\n    ... on NameStoreJoinNode {\n      id\n      nameId\n      storeId\n    }\n    ... on LinkPatientPatientToStoreError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<LinkPatientToStoreResult, LinkPatientToStoreVariables>;
