/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type SensorRowFragment = {
  __typename: "SensorNode";
  id: string;
  name: string;
  serial: string;
  type: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG";
  isActive: boolean;
  batteryLevel: number | null;
  location: {
  id: string;
  code: string;
  name: string;
} | null;
  assets: {
  __typename: "AssetConnector";
  nodes: Array<{
  id: string;
  assetNumber: string | null;
}>;
};
  latestTemperatureLog: {
  nodes: Array<{
  temperature: number;
  datetime: string;
}>;
} | null;
  breach: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION" | null;
};

export type SensorsListVariables = {
  storeId: string;
  filter?: {
    serial?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isActive?: boolean | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    equalAny?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
    notEqualTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    notEqualAll?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
  } | null;
    locationCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "serial" | "name";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type SensorsListResult = {
  sensors: ({
  __typename: "SensorConnector";
} & {
  totalCount: number;
  nodes: Array<SensorRowFragment>;
});
};

export const SensorsList = {
  query: "query sensorsList($storeId: String!, $filter: SensorFilterInput, $sort: [SensorSortInput!], $page: PaginationInput) {\n  sensors(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on SensorConnector {\n      __typename\n      totalCount\n      nodes {\n        ...SensorRow\n      }\n    }\n  }\n}\n\nfragment SensorRow on SensorNode {\n  __typename\n  id\n  name\n  serial\n  type\n  isActive\n  batteryLevel\n  location {\n    id\n    code\n    name\n  }\n  assets {\n    ... on AssetConnector {\n      __typename\n      nodes {\n        id\n        assetNumber\n      }\n    }\n  }\n  latestTemperatureLog {\n    nodes {\n      temperature\n      datetime\n    }\n  }\n  breach\n}",
} as TypedDocument<SensorsListResult, SensorsListVariables>;

export type UpdateSensorVariables = {
  storeId: string;
  input: {
    id: string;
    locationId?: {
    value?: string | null;
  } | null;
    name?: string | null;
    isActive?: boolean | null;
  };
};

export type UpdateSensorResult = {
  updateSensor: (SensorRowFragment);
};

export const UpdateSensor = {
  query: "mutation updateSensor($storeId: String!, $input: UpdateSensorInput!) {\n  updateSensor(storeId: $storeId, input: $input) {\n    ... on SensorNode {\n      ...SensorRow\n    }\n  }\n}\n\nfragment SensorRow on SensorNode {\n  __typename\n  id\n  name\n  serial\n  type\n  isActive\n  batteryLevel\n  location {\n    id\n    code\n    name\n  }\n  assets {\n    ... on AssetConnector {\n      __typename\n      nodes {\n        id\n        assetNumber\n      }\n    }\n  }\n  latestTemperatureLog {\n    nodes {\n      temperature\n      datetime\n    }\n  }\n  breach\n}",
} as TypedDocument<UpdateSensorResult, UpdateSensorVariables>;
