/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type CampaignsVariables = {
  storeId: string;
  sort?: Array<{
    key: "name";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type CampaignsResult = {
  campaigns: ({
  __typename: "CampaignConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  name: string;
  startDate: string | null;
  endDate: string | null;
}>;
});
};

export const Campaigns = {
  query: "query campaigns($storeId: String!, $sort: [CampaignSortInput!], $page: PaginationInput) {\n  campaigns(storeId: $storeId, sort: $sort, page: $page) {\n    ... on CampaignConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        name\n        startDate\n        endDate\n      }\n    }\n  }\n}",
} as TypedDocument<CampaignsResult, CampaignsVariables>;

export type UpsertCampaignVariables = {
  input: {
    id: string;
    name: string;
    startDate?: string | null;
    endDate?: string | null;
  };
};

export type UpsertCampaignResult = {
  centralServer: {
  campaign: {
  upsertCampaign: ({
  __typename: "CampaignNode";
} & {
  id: string;
  name: string;
  startDate: string | null;
  endDate: string | null;
}) | ({
  __typename: "UpsertCampaignError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};
};
};

export const UpsertCampaign = {
  query: "mutation upsertCampaign($input: UpsertCampaignInput!) {\n  centralServer {\n    campaign {\n      upsertCampaign(input: $input) {\n        __typename\n        ... on CampaignNode {\n          id\n          name\n          startDate\n          endDate\n        }\n        ... on UpsertCampaignError {\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<UpsertCampaignResult, UpsertCampaignVariables>;

export type DeleteCampaignVariables = {
  input: {
    id: string;
  };
};

export type DeleteCampaignResult = {
  centralServer: {
  campaign: {
  deleteCampaign: ({
  __typename: "DeleteCampaignSuccess";
} & {
  id: string;
}) | ({
  __typename: "DeleteCampaignError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};
};
};

export const DeleteCampaign = {
  query: "mutation deleteCampaign($input: DeleteCampaignInput!) {\n  centralServer {\n    campaign {\n      deleteCampaign(input: $input) {\n        __typename\n        ... on DeleteCampaignSuccess {\n          id\n        }\n        ... on DeleteCampaignError {\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteCampaignResult, DeleteCampaignVariables>;
