/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type ItemsWithStockVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    type?: {
    equalTo?: "SERVICE" | "STOCK" | "NON_STOCK" | null;
    equalAny?: Array<"SERVICE" | "STOCK" | "NON_STOCK"> | null;
    notEqualTo?: "SERVICE" | "STOCK" | "NON_STOCK" | null;
    notEqualAll?: Array<"SERVICE" | "STOCK" | "NON_STOCK"> | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    categoryId?: string | null;
    categoryName?: string | null;
    isVisibleOrOnHand?: boolean | null;
    isVisible?: boolean | null;
    hasStockOnHand?: boolean | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isActive?: boolean | null;
    isVaccine?: boolean | null;
    masterListId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isProgramItem?: boolean | null;
    ignoreForOrders?: boolean | null;
    minMonthsOfStock?: number | null;
    maxMonthsOfStock?: number | null;
    withRecentConsumption?: boolean | null;
    productsAtRiskOfBeingOutOfStock?: boolean | null;
    universalCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    dynamicFilter?: unknown | null;
  } | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
  sort?: Array<{
    key: "name" | "code" | "type";
    desc?: boolean | null;
  }> | null;
};

export type ItemsWithStockResult = {
  items: ({
  __typename: "ItemConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  unitName: string | null;
  isVaccine: boolean;
  doses: number;
  defaultPackSize: number;
  itemStoreProperties: {
  defaultSellPricePerPack: number;
} | null;
  availableBatches: {
  __typename: "StockLineConnector";
  nodes: Array<{
  id: string;
  availableNumberOfPacks: number;
  packSize: number;
}>;
};
}>;
});
};

export const ItemsWithStock = {
  query: "query itemsWithStock($storeId: String!, $filter: ItemFilterInput, $page: PaginationInput, $sort: [ItemSortInput!]) {\n  items(storeId: $storeId, filter: $filter, page: $page, sort: $sort) {\n    ... on ItemConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        code\n        name\n        unitName\n        isVaccine\n        doses\n        defaultPackSize\n        itemStoreProperties(storeId: $storeId) {\n          defaultSellPricePerPack\n        }\n        availableBatches(storeId: $storeId) {\n          ... on StockLineConnector {\n            __typename\n            nodes {\n              id\n              availableNumberOfPacks\n              packSize\n            }\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<ItemsWithStockResult, ItemsWithStockVariables>;
