/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type CreateOrderRequisitionsVariables = {
  storeId: string;
  supplierId: string;
};

export type CreateOrderRequisitionsResult = {
  requisitions: ({
  __typename: "RequisitionConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  requisitionNumber: number;
  otherPartyName: string;
  createdDatetime: string;
  programName: string | null;
  theirReference: string | null;
  status: "DRAFT" | "NEW" | "SENT" | "FINALISED";
  comment: string | null;
}>;
});
};

export const CreateOrderRequisitions = {
  query: "query createOrderRequisitions($storeId: String!, $supplierId: String!) {\n  requisitions(\n    storeId: $storeId\n    filter: {type: {equalTo: RESPONSE}, status: {notEqualTo: FINALISED}, hasOutstandingLines: true, otherPartyId: {notEqualTo: $supplierId}}\n    sort: [{key: createdDatetime, desc: true}]\n  ) {\n    ... on RequisitionConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        requisitionNumber\n        otherPartyName\n        createdDatetime\n        programName\n        theirReference\n        status\n        comment\n      }\n    }\n  }\n}",
} as TypedDocument<CreateOrderRequisitionsResult, CreateOrderRequisitionsVariables>;

export type InsertOrderFromRequisitionVariables = {
  storeId: string;
  input: {
    id: string;
    responseRequisitionId: string;
    otherPartyId: string;
    comment?: string | null;
    status?: "DRAFT" | "SENT" | null;
  };
};

export type InsertOrderFromRequisitionResult = {
  insertRequestFromResponseRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
}) | ({
  __typename: "InsertFromResponseRequisitionError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const InsertOrderFromRequisition = {
  query: "mutation insertOrderFromRequisition($storeId: String!, $input: InsertFromResponseRequisitionInput!) {\n  insertRequestFromResponseRequisition(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionNode {\n      id\n    }\n    ... on InsertFromResponseRequisitionError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertOrderFromRequisitionResult, InsertOrderFromRequisitionVariables>;
