/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type CustomerProgramSettingsVariables = {
  storeId: string;
  customerNameId: string;
};

export type CustomerProgramSettingsResult = {
  programRequisitionSettingsByCustomer: {
  customerNameId: string;
  programSettings: Array<{
  masterListId: string;
  masterListName: string;
  masterListNameTagName: string;
  orderTypes: Array<{
  id: string;
  name: string;
  isEmergency: boolean;
  availablePeriods: Array<{
  id: string;
  name: string;
}>;
}>;
}>;
};
};

export const CustomerProgramSettings = {
  query: "query customerProgramSettings($storeId: String!, $customerNameId: String!) {\n  programRequisitionSettingsByCustomer(\n    storeId: $storeId\n    customerNameId: $customerNameId\n  ) {\n    customerNameId\n    programSettings {\n      masterListId\n      masterListName\n      masterListNameTagName\n      orderTypes {\n        id\n        name\n        isEmergency\n        availablePeriods {\n          id\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<CustomerProgramSettingsResult, CustomerProgramSettingsVariables>;

export type InsertRequisitionVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    maxMonthsOfStock: number;
    minMonthsOfStock: number;
  };
};

export type InsertRequisitionResult = {
  insertResponseRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
}) | ({
  __typename: "InsertResponseRequisitionError";
} & {
  error: {
  __typename: "OtherPartyNotACustomer" | "OtherPartyNotVisible";
  description: string;
};
});
};

export const InsertRequisition = {
  query: "mutation insertRequisition($storeId: String!, $input: InsertResponseRequisitionInput!) {\n  insertResponseRequisition(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionNode {\n      id\n    }\n    ... on InsertResponseRequisitionError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertRequisitionResult, InsertRequisitionVariables>;

export type InsertProgramRequisitionVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    programOrderTypeId: string;
    periodId: string;
  };
};

export type InsertProgramRequisitionResult = {
  insertProgramResponseRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
}) | ({
  __typename: "InsertProgramResponseRequisitionError";
} & {
  error: {
  __typename: "MaxOrdersReachedForPeriod";
  description: string;
};
});
};

export const InsertProgramRequisition = {
  query: "mutation insertProgramRequisition($storeId: String!, $input: InsertProgramResponseRequisitionInput!) {\n  insertProgramResponseRequisition(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionNode {\n      id\n    }\n    ... on InsertProgramResponseRequisitionError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertProgramRequisitionResult, InsertProgramRequisitionVariables>;
