export { Customers } from './Customers';
export { Dashboard } from './Dashboard';
export { Invoice } from './Invoice';
export { MSupplyGuy } from './MSupplyGuy';
export { Menu as MenuIcon } from './Menu';
export { Receipt as ReceiptIcon } from '@material-ui/icons';
export { Messages } from './Messages';
export { Power } from './Power';
export { Radio } from './Radio';
export { Reports } from './Reports';
export { Settings } from './Settings';
export { Stock } from './Stock';
export { Suppliers } from './Suppliers';
export { Tools } from './Tools';
export { Translate as TranslateIcon } from '@material-ui/icons';
