/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type AssetClassesVariables = Record<string, never>;

export type AssetClassesResult = {
  assetClasses: ({
  __typename: "AssetClassConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const AssetClasses = {
  query: "query assetClasses {\n  assetClasses(sort: [{key: name}]) {\n    ... on AssetClassConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<AssetClassesResult, AssetClassesVariables>;

export type AssetPropertiesVariables = Record<string, never>;

export type AssetPropertiesResult = {
  assetProperties: ({
  __typename: "AssetPropertyConnector";
} & {
  nodes: Array<{
  id: string;
  key: string;
  name: string;
  valueType: "STRING" | "BOOLEAN" | "INTEGER" | "FLOAT" | "DATE";
  allowedValues: string | null;
}>;
});
};

export const AssetProperties = {
  query: "query assetProperties {\n  assetProperties {\n    ... on AssetPropertyConnector {\n      __typename\n      nodes {\n        id\n        key\n        name\n        valueType\n        allowedValues\n      }\n    }\n  }\n}",
} as TypedDocument<AssetPropertiesResult, AssetPropertiesVariables>;

export type InsertAssetCatalogueItemVariables = {
  storeId: string;
  input: {
    id: string;
    subCatalogue: string;
    categoryId: string;
    classId: string;
    code: string;
    manufacturer?: string | null;
    model: string;
    typeId: string;
    properties?: string | null;
  };
};

export type InsertAssetCatalogueItemResult = {
  centralServer: {
  assetCatalogue: {
  insertAssetCatalogueItem: ({
  __typename: "AssetCatalogueItemNode";
} & {
  id: string;
}) | ({
  __typename: "InsertAssetCatalogueItemError";
} & {
  error: ({
  __typename: "RecordAlreadyExist";
} & {
  description: string;
} & {
  description: string;
}) | ({
  __typename: "UniqueValueViolation";
} & {
  field: "code" | "serial" | "name";
} & {
  description: string;
}) | ({
  __typename: "UniqueCombinationViolation";
} & {
  fields: Array<"manufacturer" | "model">;
} & {
  description: string;
});
});
};
};
};

export const InsertAssetCatalogueItem = {
  query: "mutation insertAssetCatalogueItem($storeId: String!, $input: InsertAssetCatalogueItemInput!) {\n  centralServer {\n    assetCatalogue {\n      insertAssetCatalogueItem(storeId: $storeId, input: $input) {\n        __typename\n        ... on AssetCatalogueItemNode {\n          id\n        }\n        ... on InsertAssetCatalogueItemError {\n          error {\n            __typename\n            description\n            ... on RecordAlreadyExist {\n              description\n            }\n            ... on UniqueValueViolation {\n              field\n            }\n            ... on UniqueCombinationViolation {\n              fields\n            }\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<InsertAssetCatalogueItemResult, InsertAssetCatalogueItemVariables>;
