/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type CustomerReturnInfoFragment = {
  id: string;
  invoiceNumber: number;
  status: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED";
  onHold: boolean;
  colour: string | null;
  comment: string | null;
  theirReference: string | null;
  createdDatetime: string;
  pickedDatetime: string | null;
  shippedDatetime: string | null;
  deliveredDatetime: string | null;
  receivedDatetime: string | null;
  verifiedDatetime: string | null;
  otherPartyId: string;
  otherPartyName: string;
  transportReference: string | null;
  user: {
  username: string;
  email: string | null;
} | null;
  linkedShipment: {
  id: string;
} | null;
  originalShipment: {
  id: string;
  invoiceNumber: number;
  createdDatetime: string;
  user: {
  username: string;
} | null;
} | null;
  customFields: unknown | null;
};

export type CustomerReturnLineFragment = {
  id: string;
  itemName: string;
  itemCode: string;
  item: {
  id: string;
  code: string;
  unitName: string | null;
};
  batch: string | null;
  expiryDate: string | null;
  packSize: number;
  numberOfPacks: number;
  sellPricePerPack: number;
  note: string | null;
  itemVariantId: string | null;
  volumePerPack: number;
  reasonOption: {
  id: string;
  type: "POSITIVE_INVENTORY_ADJUSTMENT" | "NEGATIVE_INVENTORY_ADJUSTMENT" | "OPEN_VIAL_WASTAGE" | "RETURN_REASON" | "REQUISITION_LINE_VARIANCE" | "CLOSED_VIAL_WASTAGE" | "SHIPMENT_VARIANCE";
  reason: string;
} | null;
  stockLine: {
  id: string;
} | null;
};

export type CustomerReturnDetailVariables = {
  storeId: string;
  id: string;
};

export type CustomerReturnDetailResult = {
  invoice: ({
  __typename: "InvoiceNode";
} & CustomerReturnInfoFragment) | ({
  __typename: "NodeError";
} & {
  error: {
  __typename: "DatabaseError" | "RecordNotFound";
  description: string;
};
});
};

export const CustomerReturnDetail = {
  query: "query customerReturnDetail($storeId: String!, $id: String!) {\n  invoice(storeId: $storeId, id: $id) {\n    __typename\n    ... on InvoiceNode {\n      ...CustomerReturnInfo\n    }\n    ... on NodeError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}\n\nfragment CustomerReturnInfo on InvoiceNode {\n  id\n  invoiceNumber\n  status\n  onHold\n  colour\n  comment\n  theirReference\n  createdDatetime\n  pickedDatetime\n  shippedDatetime\n  deliveredDatetime\n  receivedDatetime\n  verifiedDatetime\n  otherPartyId\n  otherPartyName\n  transportReference\n  user {\n    username\n    email\n  }\n  linkedShipment {\n    id\n  }\n  originalShipment {\n    id\n    invoiceNumber\n    createdDatetime\n    user {\n      username\n    }\n  }\n  customFields\n}",
} as TypedDocument<CustomerReturnDetailResult, CustomerReturnDetailVariables>;

export type CustomerReturnForCopyVariables = {
  storeId: string;
  id: string;
};

export type CustomerReturnForCopyResult = {
  invoice: ({
  __typename: "InvoiceNode";
} & {
  lines: {
  totalCount: number;
  nodes: Array<CustomerReturnLineFragment>;
};
} & CustomerReturnInfoFragment);
};

export const CustomerReturnForCopy = {
  query: "query customerReturnForCopy($storeId: String!, $id: String!) {\n  invoice(storeId: $storeId, id: $id) {\n    __typename\n    ... on InvoiceNode {\n      ...CustomerReturnInfo\n      lines {\n        totalCount\n        nodes {\n          ...CustomerReturnLine\n        }\n      }\n    }\n  }\n}\n\nfragment CustomerReturnInfo on InvoiceNode {\n  id\n  invoiceNumber\n  status\n  onHold\n  colour\n  comment\n  theirReference\n  createdDatetime\n  pickedDatetime\n  shippedDatetime\n  deliveredDatetime\n  receivedDatetime\n  verifiedDatetime\n  otherPartyId\n  otherPartyName\n  transportReference\n  user {\n    username\n    email\n  }\n  linkedShipment {\n    id\n  }\n  originalShipment {\n    id\n    invoiceNumber\n    createdDatetime\n    user {\n      username\n    }\n  }\n  customFields\n}\n\nfragment CustomerReturnLine on InvoiceLineNode {\n  id\n  itemName\n  itemCode\n  item {\n    id\n    code\n    unitName\n  }\n  batch\n  expiryDate\n  packSize\n  numberOfPacks\n  sellPricePerPack\n  note\n  itemVariantId\n  volumePerPack\n  reasonOption {\n    id\n    type\n    reason\n  }\n  stockLine {\n    id\n  }\n}",
} as TypedDocument<CustomerReturnForCopyResult, CustomerReturnForCopyVariables>;

export type CustomerReturnLinesVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    invoiceId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    itemCodeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    type?: {
    equalTo?: "STOCK_IN" | "STOCK_OUT" | "UNALLOCATED_STOCK" | "SERVICE" | null;
    equalAny?: Array<"STOCK_IN" | "STOCK_OUT" | "UNALLOCATED_STOCK" | "SERVICE"> | null;
    notEqualTo?: "STOCK_IN" | "STOCK_OUT" | "UNALLOCATED_STOCK" | "SERVICE" | null;
    notEqualAll?: Array<"STOCK_IN" | "STOCK_OUT" | "UNALLOCATED_STOCK" | "SERVICE"> | null;
  } | null;
    requisitionId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    numberOfPacks?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    invoiceType?: {
    equalTo?: "OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK" | null;
    equalAny?: Array<"OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK"> | null;
    notEqualTo?: "OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK" | null;
    notEqualAll?: Array<"OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK"> | null;
  } | null;
    invoiceStatus?: {
    equalTo?: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED" | null;
    equalAny?: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED"> | null;
    notEqualTo?: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED" | null;
    notEqualAll?: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED"> | null;
  } | null;
    stockLineId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    reasonOption?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    inventoryAdjustmentReason?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    verifiedDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isProgramInvoice?: boolean | null;
  } | null;
  sort?: Array<{
    key: "itemCode" | "itemName" | "batch" | "expiryDate" | "packSize" | "locationName" | "requestedQuantity";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type CustomerReturnLinesResult = {
  invoiceLines: ({
  __typename: "InvoiceLineConnector";
} & {
  totalCount: number;
  nodes: Array<CustomerReturnLineFragment>;
});
};

export const CustomerReturnLines = {
  query: "query customerReturnLines($storeId: String!, $filter: InvoiceLineFilterInput, $sort: [InvoiceLineSortInput!], $page: PaginationInput) {\n  invoiceLines(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on InvoiceLineConnector {\n      __typename\n      totalCount\n      nodes {\n        ...CustomerReturnLine\n      }\n    }\n  }\n}\n\nfragment CustomerReturnLine on InvoiceLineNode {\n  id\n  itemName\n  itemCode\n  item {\n    id\n    code\n    unitName\n  }\n  batch\n  expiryDate\n  packSize\n  numberOfPacks\n  sellPricePerPack\n  note\n  itemVariantId\n  volumePerPack\n  reasonOption {\n    id\n    type\n    reason\n  }\n  stockLine {\n    id\n  }\n}",
} as TypedDocument<CustomerReturnLinesResult, CustomerReturnLinesVariables>;

export type UpdateCustomerReturnVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId?: string | null;
    status?: "RECEIVED" | "VERIFIED" | null;
    onHold?: boolean | null;
    comment?: string | null;
    colour?: string | null;
    theirReference?: string | null;
    customFields?: unknown | null;
  };
};

export type UpdateCustomerReturnResult = {
  updateCustomerReturn: ({
  __typename: "InvoiceNode";
} & CustomerReturnInfoFragment) | ({
  __typename: "UpdateCustomerReturnError";
} & {
  error: {
  __typename: "OtherPartyNotACustomer" | "OtherPartyNotVisible";
  description: string;
};
});
};

export const UpdateCustomerReturn = {
  query: "mutation updateCustomerReturn($storeId: String!, $input: UpdateCustomerReturnInput!) {\n  updateCustomerReturn(storeId: $storeId, input: $input) {\n    __typename\n    ... on InvoiceNode {\n      ...CustomerReturnInfo\n    }\n    ... on UpdateCustomerReturnError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}\n\nfragment CustomerReturnInfo on InvoiceNode {\n  id\n  invoiceNumber\n  status\n  onHold\n  colour\n  comment\n  theirReference\n  createdDatetime\n  pickedDatetime\n  shippedDatetime\n  deliveredDatetime\n  receivedDatetime\n  verifiedDatetime\n  otherPartyId\n  otherPartyName\n  transportReference\n  user {\n    username\n    email\n  }\n  linkedShipment {\n    id\n  }\n  originalShipment {\n    id\n    invoiceNumber\n    createdDatetime\n    user {\n      username\n    }\n  }\n  customFields\n}",
} as TypedDocument<UpdateCustomerReturnResult, UpdateCustomerReturnVariables>;

export type UpdateCustomerReturnLinesVariables = {
  storeId: string;
  input: {
    customerReturnId: string;
    customerReturnLines: Array<{
    id: string;
    numberOfPacksReturned: number;
    itemId: string;
    reasonId?: string | null;
    note?: string | null;
    packSize: number;
    batch?: string | null;
    expiryDate?: string | null;
    itemVariantId?: string | null;
    vvmStatusId?: string | null;
    volumePerPack?: number | null;
  }>;
  };
};

export type UpdateCustomerReturnLinesResult = {
  updateCustomerReturnLines: ({
  __typename: "InvoiceNode";
} & CustomerReturnInfoFragment);
};

export const UpdateCustomerReturnLines = {
  query: "mutation updateCustomerReturnLines($storeId: String!, $input: UpdateCustomerReturnLinesInput!) {\n  updateCustomerReturnLines(storeId: $storeId, input: $input) {\n    ... on InvoiceNode {\n      __typename\n      ...CustomerReturnInfo\n    }\n  }\n}\n\nfragment CustomerReturnInfo on InvoiceNode {\n  id\n  invoiceNumber\n  status\n  onHold\n  colour\n  comment\n  theirReference\n  createdDatetime\n  pickedDatetime\n  shippedDatetime\n  deliveredDatetime\n  receivedDatetime\n  verifiedDatetime\n  otherPartyId\n  otherPartyName\n  transportReference\n  user {\n    username\n    email\n  }\n  linkedShipment {\n    id\n  }\n  originalShipment {\n    id\n    invoiceNumber\n    createdDatetime\n    user {\n      username\n    }\n  }\n  customFields\n}",
} as TypedDocument<UpdateCustomerReturnLinesResult, UpdateCustomerReturnLinesVariables>;

export type GenerateCustomerReturnLinesVariables = {
  storeId: string;
  input: {
    outboundShipmentLineIds: Array<string>;
    existingLinesInput?: {
    itemId: string;
    returnId: string;
  } | null;
  };
};

export type GenerateCustomerReturnLinesResult = {
  generateCustomerReturnLines: ({
  __typename: "GeneratedCustomerReturnLineConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  batch: string | null;
  expiryDate: string | null;
  packSize: number;
  numberOfPacksReturned: number;
  numberOfPacksIssued: number | null;
  note: string | null;
  reasonId: string | null;
  itemVariantId: string | null;
  volumePerPack: number;
  itemCode: string;
  itemName: string;
  item: {
  id: string;
  code: string;
  unitName: string | null;
};
}>;
});
};

export const GenerateCustomerReturnLines = {
  query: "query generateCustomerReturnLines($storeId: String!, $input: GenerateCustomerReturnLinesInput!) {\n  generateCustomerReturnLines(storeId: $storeId, input: $input) {\n    ... on GeneratedCustomerReturnLineConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        batch\n        expiryDate\n        packSize\n        numberOfPacksReturned\n        numberOfPacksIssued\n        note\n        reasonId\n        itemVariantId\n        volumePerPack\n        itemCode\n        itemName\n        item {\n          id\n          code\n          unitName\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<GenerateCustomerReturnLinesResult, GenerateCustomerReturnLinesVariables>;
