/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type AssetRowFragment = {
  __typename: "AssetNode";
  id: string;
  storeId: string | null;
  assetNumber: string | null;
  serialNumber: string | null;
  notes: string | null;
  installationDate: string | null;
  replacementDate: string | null;
  catalogueItemId: string | null;
  catalogueItem: {
  manufacturer: string | null;
  model: string;
} | null;
  assetCategory: {
  id: string;
  name: string;
} | null;
  assetType: {
  id: string;
  name: string;
} | null;
  statusLog: {
  status: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
  logDatetime: string;
} | null;
  store: {
  id: string;
  code: string;
  storeName: string;
} | null;
};

export type AssetDetailFragment = {
  __typename: "AssetNode";
  id: string;
  storeId: string | null;
  assetNumber: string | null;
  serialNumber: string | null;
  notes: string | null;
  catalogueItemId: string | null;
  installationDate: string | null;
  replacementDate: string | null;
  warrantyStart: string | null;
  warrantyEnd: string | null;
  needsReplacement: boolean | null;
  donorNameId: string | null;
  createdDatetime: string;
  modifiedDatetime: string;
  properties: string;
  catalogProperties: string | null;
  catalogueItem: {
  id: string;
  code: string;
  manufacturer: string | null;
  model: string;
} | null;
  assetClass: {
  id: string;
  name: string;
} | null;
  assetCategory: {
  id: string;
  name: string;
} | null;
  assetType: {
  id: string;
  name: string;
} | null;
  statusLog: {
  status: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
  logDatetime: string;
  reason: {
  reason: string;
} | null;
} | null;
  store: {
  __typename: "StoreNode";
  id: string;
  code: string;
  storeName: string;
  siteId: number;
} | null;
  donor: {
  __typename: "NameNode";
  id: string;
  name: string;
  code: string;
  isSupplier: boolean;
  isDonor: boolean;
  isOnHold: boolean;
  store: {
  id: string;
} | null;
} | null;
  locations: {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  locationType: {
  id: string;
  name: string;
} | null;
}>;
};
  documents: {
  nodes: Array<{
  id: string;
  fileName: string;
  mimeType: string | null;
  createdDatetime: string;
  totalBytes: number;
}>;
};
  lockedFields: {
  serialNumber: boolean;
  catalogueItemId: boolean;
  warrantyStart: boolean;
  warrantyEnd: boolean;
};
};

export type AssetLogRowFragment = {
  __typename: "AssetLogNode";
  id: string;
  status: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
  type: "STATUS_UPDATE" | "TEMPERATURE_MAPPING";
  comment: string | null;
  logDatetime: string;
  reason: {
  id: string;
  reason: string;
} | null;
  user: {
  username: string;
  firstName: string | null;
  lastName: string | null;
  jobTitle: string | null;
} | null;
  documents: {
  nodes: Array<{
  id: string;
  fileName: string;
}>;
};
};

export type AssetsListVariables = {
  storeId: string;
  filter?: {
    notes?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    assetNumber?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    serialNumber?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    classId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    categoryId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    typeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    catalogueItemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isNonCatalogue?: boolean | null;
    installationDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    replacementDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    storeCodeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    functionalStatus?: {
    equalTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    equalAny?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
    notEqualTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    notEqualAll?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "serialNumber" | "installationDate" | "replacementDate" | "modifiedDatetime" | "assetNumber" | "store" | "notes";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type AssetsListResult = {
  assets: ({
  __typename: "AssetConnector";
} & {
  totalCount: number;
  nodes: Array<AssetRowFragment>;
});
};

export const AssetsList = {
  query: "query assetsList($storeId: String!, $filter: AssetFilterInput, $sort: [AssetSortInput!], $page: PaginationInput) {\n  assets(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on AssetConnector {\n      __typename\n      totalCount\n      nodes {\n        ...AssetRow\n      }\n    }\n  }\n}\n\nfragment AssetRow on AssetNode {\n  __typename\n  id\n  storeId\n  assetNumber\n  serialNumber\n  notes\n  installationDate\n  replacementDate\n  catalogueItemId\n  catalogueItem {\n    manufacturer\n    model\n  }\n  assetCategory {\n    id\n    name\n  }\n  assetType {\n    id\n    name\n  }\n  statusLog {\n    status\n    logDatetime\n  }\n  store {\n    id\n    code\n    storeName\n  }\n}",
} as TypedDocument<AssetsListResult, AssetsListVariables>;

export type AssetByIdVariables = {
  storeId: string;
  assetId: string;
};

export type AssetByIdResult = {
  assets: ({
  __typename: "AssetConnector";
} & {
  totalCount: number;
  nodes: Array<AssetDetailFragment>;
});
};

export const AssetById = {
  query: "query assetById($storeId: String!, $assetId: String!) {\n  assets(storeId: $storeId, filter: {id: {equalTo: $assetId}}) {\n    ... on AssetConnector {\n      __typename\n      totalCount\n      nodes {\n        ...AssetDetail\n      }\n    }\n  }\n}\n\nfragment AssetDetail on AssetNode {\n  __typename\n  id\n  storeId\n  assetNumber\n  serialNumber\n  notes\n  catalogueItemId\n  installationDate\n  replacementDate\n  warrantyStart\n  warrantyEnd\n  needsReplacement\n  donorNameId\n  createdDatetime\n  modifiedDatetime\n  properties\n  catalogProperties\n  catalogueItem {\n    id\n    code\n    manufacturer\n    model\n  }\n  assetClass {\n    id\n    name\n  }\n  assetCategory {\n    id\n    name\n  }\n  assetType {\n    id\n    name\n  }\n  statusLog {\n    status\n    logDatetime\n    reason {\n      reason\n    }\n  }\n  store {\n    __typename\n    id\n    code\n    storeName\n    siteId\n  }\n  donor(storeId: $storeId) {\n    __typename\n    id\n    name\n    code\n    isSupplier\n    isDonor\n    isOnHold\n    store {\n      id\n    }\n  }\n  locations {\n    totalCount\n    nodes {\n      id\n      code\n      name\n      locationType {\n        id\n        name\n      }\n    }\n  }\n  documents {\n    nodes {\n      id\n      fileName\n      mimeType\n      createdDatetime\n      totalBytes\n    }\n  }\n  lockedFields {\n    serialNumber\n    catalogueItemId\n    warrantyStart\n    warrantyEnd\n  }\n}",
} as TypedDocument<AssetByIdResult, AssetByIdVariables>;

export type AssetLogsListVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    assetId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    status?: {
    equalTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    equalAny?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
    notEqualTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    notEqualAll?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
  } | null;
    logDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    user?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    reasonId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: "STATUS_UPDATE" | "TEMPERATURE_MAPPING" | null;
    equalAny?: Array<"STATUS_UPDATE" | "TEMPERATURE_MAPPING"> | null;
    notEqualTo?: "STATUS_UPDATE" | "TEMPERATURE_MAPPING" | null;
    notEqualAll?: Array<"STATUS_UPDATE" | "TEMPERATURE_MAPPING"> | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "status" | "logDatetime";
    desc?: boolean | null;
  }> | null;
};

export type AssetLogsListResult = {
  assetLogs: ({
  __typename: "AssetLogConnector";
} & {
  totalCount: number;
  nodes: Array<AssetLogRowFragment>;
});
};

export const AssetLogsList = {
  query: "query assetLogsList($storeId: String!, $filter: AssetLogFilterInput, $sort: [AssetLogSortInput!]) {\n  assetLogs(storeId: $storeId, filter: $filter, sort: $sort) {\n    ... on AssetLogConnector {\n      __typename\n      totalCount\n      nodes {\n        ...AssetLogRow\n      }\n    }\n  }\n}\n\nfragment AssetLogRow on AssetLogNode {\n  __typename\n  id\n  status\n  type\n  comment\n  logDatetime\n  reason {\n    id\n    reason\n  }\n  user {\n    username\n    firstName\n    lastName\n    jobTitle\n  }\n  documents {\n    nodes {\n      id\n      fileName\n    }\n  }\n}",
} as TypedDocument<AssetLogsListResult, AssetLogsListVariables>;

export type AssetLogReasonsListVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    assetLogStatus?: {
    equalTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    equalAny?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
    notEqualTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    notEqualAll?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
  } | null;
    reason?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
};

export type AssetLogReasonsListResult = {
  assetLogReasons: ({
  __typename: "AssetLogReasonConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  assetLogStatus: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE";
  reason: string;
  commentsRequired: boolean;
}>;
});
};

export const AssetLogReasonsList = {
  query: "query assetLogReasonsList($storeId: String!, $filter: AssetLogReasonFilterInput) {\n  assetLogReasons(storeId: $storeId, filter: $filter) {\n    ... on AssetLogReasonConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        assetLogStatus\n        reason\n        commentsRequired\n      }\n    }\n  }\n}",
} as TypedDocument<AssetLogReasonsListResult, AssetLogReasonsListVariables>;

export type InsertAssetVariables = {
  storeId: string;
  input: {
    id: string;
    storeId?: string | null;
    notes?: string | null;
    assetNumber?: string | null;
    serialNumber?: string | null;
    catalogueItemId?: string | null;
    categoryId?: string | null;
    classId?: string | null;
    typeId?: string | null;
    installationDate?: string | null;
    replacementDate?: string | null;
    properties?: string | null;
    donorNameId?: string | null;
    warrantyStart?: string | null;
    warrantyEnd?: string | null;
    needsReplacement?: boolean | null;
    lockedFieldsJson?: string | null;
  };
};

export type InsertAssetResult = {
  insertAsset: ({
  __typename: "AssetNode";
} & {
  id: string;
});
};

export const InsertAsset = {
  query: "mutation insertAsset($storeId: String!, $input: InsertAssetInput!) {\n  insertAsset(storeId: $storeId, input: $input) {\n    ... on AssetNode {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<InsertAssetResult, InsertAssetVariables>;

export type UpdateAssetVariables = {
  storeId: string;
  input: {
    id: string;
    assetNumber?: string | null;
    notes?: string | null;
    storeId?: {
    value?: string | null;
  } | null;
    serialNumber?: {
    value?: string | null;
  } | null;
    catalogueItemId?: {
    value?: string | null;
  } | null;
    installationDate?: {
    value?: string | null;
  } | null;
    replacementDate?: {
    value?: string | null;
  } | null;
    locationIds?: Array<string> | null;
    properties?: string | null;
    donorNameId?: {
    value?: string | null;
  } | null;
    warrantyStart?: {
    value?: string | null;
  } | null;
    warrantyEnd?: {
    value?: string | null;
  } | null;
    needsReplacement?: boolean | null;
  };
};

export type UpdateAssetResult = {
  updateAsset: ({
  __typename: "AssetNode";
} & {
  id: string;
});
};

export const UpdateAsset = {
  query: "mutation updateAsset($storeId: String!, $input: UpdateAssetInput!) {\n  updateAsset(storeId: $storeId, input: $input) {\n    ... on AssetNode {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<UpdateAssetResult, UpdateAssetVariables>;

export type DeleteAssetVariables = {
  storeId: string;
  assetId: string;
};

export type DeleteAssetResult = {
  deleteAsset: ({
  __typename: "DeleteResponse";
} & {
  id: string;
});
};

export const DeleteAsset = {
  query: "mutation deleteAsset($storeId: String!, $assetId: String!) {\n  deleteAsset(storeId: $storeId, assetId: $assetId) {\n    ... on DeleteResponse {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<DeleteAssetResult, DeleteAssetVariables>;

export type InsertAssetLogVariables = {
  storeId: string;
  input: {
    id: string;
    assetId: string;
    status?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    reasonId?: string | null;
    comment?: string | null;
    type?: "STATUS_UPDATE" | "TEMPERATURE_MAPPING" | null;
    logDatetime?: string | null;
  };
};

export type InsertAssetLogResult = {
  insertAssetLog: ({
  __typename: "AssetLogNode";
} & {
  id: string;
});
};

export const InsertAssetLog = {
  query: "mutation insertAssetLog($storeId: String!, $input: InsertAssetLogInput!) {\n  insertAssetLog(storeId: $storeId, input: $input) {\n    ... on AssetLogNode {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<InsertAssetLogResult, InsertAssetLogVariables>;

export type AssetsExportVariables = {
  storeId: string;
  filter?: {
    notes?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    assetNumber?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    serialNumber?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    classId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    categoryId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    typeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    catalogueItemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isNonCatalogue?: boolean | null;
    installationDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    replacementDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    storeCodeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    functionalStatus?: {
    equalTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    equalAny?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
    notEqualTo?: "NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE" | null;
    notEqualAll?: Array<"NOT_IN_USE" | "FUNCTIONING" | "FUNCTIONING_BUT_NEEDS_ATTENTION" | "NOT_FUNCTIONING" | "DECOMMISSIONED" | "UNSERVICEABLE"> | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "serialNumber" | "installationDate" | "replacementDate" | "modifiedDatetime" | "assetNumber" | "store" | "notes";
    desc?: boolean | null;
  }> | null;
};

export type AssetsExportResult = {
  assets: ({
  __typename: "AssetConnector";
} & {
  totalCount: number;
  nodes: Array<{
  warrantyStart: string | null;
  warrantyEnd: string | null;
  needsReplacement: boolean | null;
  createdDatetime: string;
  modifiedDatetime: string;
  properties: string;
  catalogProperties: string | null;
  catalogueItem: {
  code: string;
} | null;
} & AssetRowFragment>;
});
};

export const AssetsExport = {
  query: "query assetsExport($storeId: String!, $filter: AssetFilterInput, $sort: [AssetSortInput!]) {\n  assets(storeId: $storeId, filter: $filter, sort: $sort) {\n    ... on AssetConnector {\n      __typename\n      totalCount\n      nodes {\n        ...AssetRow\n        warrantyStart\n        warrantyEnd\n        needsReplacement\n        createdDatetime\n        modifiedDatetime\n        properties\n        catalogProperties\n        catalogueItem {\n          code\n        }\n      }\n    }\n  }\n}\n\nfragment AssetRow on AssetNode {\n  __typename\n  id\n  storeId\n  assetNumber\n  serialNumber\n  notes\n  installationDate\n  replacementDate\n  catalogueItemId\n  catalogueItem {\n    manufacturer\n    model\n  }\n  assetCategory {\n    id\n    name\n  }\n  assetType {\n    id\n    name\n  }\n  statusLog {\n    status\n    logDatetime\n  }\n  store {\n    id\n    code\n    storeName\n  }\n}",
} as TypedDocument<AssetsExportResult, AssetsExportVariables>;
