/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type ItemLedgerVariables = {
  storeId: string;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
  filter?: {
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    datetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    invoiceType?: {
    equalTo?: "OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK" | null;
    equalAny?: Array<"OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK"> | null;
    notEqualTo?: "OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK" | null;
    notEqualAll?: Array<"OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK"> | null;
  } | null;
    invoiceStatus?: {
    equalTo?: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED" | null;
    equalAny?: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED"> | null;
    notEqualTo?: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED" | null;
    notEqualAll?: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED"> | null;
  } | null;
  } | null;
};

export type ItemLedgerResult = {
  itemLedger: ({
  __typename: "ItemLedgerConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  datetime: string;
  name: string;
  invoiceType: "OUTBOUND_SHIPMENT" | "INBOUND_SHIPMENT" | "PRESCRIPTION" | "INVENTORY_ADDITION" | "INVENTORY_REDUCTION" | "SUPPLIER_RETURN" | "CUSTOMER_RETURN" | "REPACK";
  invoiceNumber: number;
  invoiceId: string;
  invoiceStatus: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED";
  expiryDate: string | null;
  batch: string | null;
  packSize: number;
  numberOfPacks: number;
  movementInUnits: number;
  balance: number;
  costPricePerPack: number;
  sellPricePerPack: number;
  totalBeforeTax: number | null;
  reason: string | null;
  isExternal: boolean;
  user: {
  username: string;
} | null;
}>;
});
};

export const ItemLedger = {
  query: "query itemLedger($storeId: String!, $page: PaginationInput, $filter: ItemLedgerFilterInput) {\n  itemLedger(storeId: $storeId, page: $page, filter: $filter) {\n    ... on ItemLedgerConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        datetime\n        name\n        invoiceType\n        invoiceNumber\n        invoiceId\n        invoiceStatus\n        expiryDate\n        batch\n        packSize\n        numberOfPacks\n        movementInUnits\n        balance\n        costPricePerPack\n        sellPricePerPack\n        totalBeforeTax\n        reason\n        isExternal\n        user {\n          username\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<ItemLedgerResult, ItemLedgerVariables>;
