/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "./graphql";

export type StocktakeLineFragment = {
  __typename: "StocktakeLineNode";
  id: string;
  stocktakeId: string;
  batch: string | null;
  itemId: string;
  itemName: string;
  expiryDate: string | null;
  packSize: number | null;
  snapshotNumberOfPacks: number;
  countedNumberOfPacks: number | null;
  comment: string | null;
  item: {
  __typename: "ItemNode";
  id: string;
  code: string;
  name: string;
  unitName: string | null;
  isVaccine: boolean;
  defaultPackSize: number;
};
  location: {
  __typename: "LocationNode";
  id: string;
  name: string;
  code: string;
  onHold: boolean;
} | null;
  reasonOption: {
  id: string;
  reason: string;
  type: "POSITIVE_INVENTORY_ADJUSTMENT" | "NEGATIVE_INVENTORY_ADJUSTMENT";
  isActive: boolean;
} | null;
};

export type StocktakeLinesVariables = {
  stocktakeId: string;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
  sort?: Array<{
    key: "itemName" | "expiryDate" | "packSize";
    desc?: boolean | null;
  }> | null;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
  } | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
  } | null;
  } | null;
};

export type StocktakeLinesResult = {
  stocktakeLines: ({
  __typename: "StocktakeLineConnector";
} & {
  totalCount: number;
  nodes: Array<StocktakeLineFragment>;
}) | ({
  __typename: "StocktakeDoesNotExist";
} & {
  description: string;
});
};

export const StocktakeLines = {
  query: "query stocktakeLines($stocktakeId: String!, $page: PaginationInput, $sort: [StocktakeLineSortInput!], $filter: StocktakeLineFilterInput) {\n  stocktakeLines(\n    stocktakeId: $stocktakeId\n    page: $page\n    sort: $sort\n    filter: $filter\n  ) {\n    __typename\n    ... on StocktakeLineConnector {\n      totalCount\n      nodes {\n        ...StocktakeLine\n      }\n    }\n    ... on StocktakeDoesNotExist {\n      description\n    }\n  }\n}\n\nfragment StocktakeLine on StocktakeLineNode {\n  __typename\n  id\n  stocktakeId\n  batch\n  itemId\n  itemName\n  expiryDate\n  packSize\n  snapshotNumberOfPacks\n  countedNumberOfPacks\n  comment\n  item {\n    __typename\n    id\n    code\n    name\n    unitName\n    isVaccine\n    defaultPackSize\n  }\n  location {\n    __typename\n    id\n    name\n    code\n    onHold\n  }\n  reasonOption {\n    id\n    reason\n    type\n    isActive\n  }\n}",
} as TypedDocument<StocktakeLinesResult, StocktakeLinesVariables>;

