CREATE TABLE report (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('OM_REPORT')) NOT NULL,
    data TEXT NOT NULL,
    context TEXT CHECK (context IN ('INVOICE', 'REQUISITION', 'STOCKTAKE', "RESOURCE")) NOT NULL
)