/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type StockMovementInfoFragment = {
  id: string;
  stockMovementNumber: number;
  status: "NEW" | "CONFIRMED" | "FINALISED";
  createdDatetime: string;
  confirmedDatetime: string | null;
  finalisedDatetime: string | null;
  comment: string | null;
  lineCount: number;
  user: {
  username: string;
  email: string | null;
} | null;
};

export type StockMovementLineFragment = {
  id: string;
  stockLineId: string;
  numberOfPacks: number;
  sourceLocation: {
  id: string;
  code: string;
} | null;
  destinationLocation: {
  id: string;
  code: string;
} | null;
  stockLine: {
  id: string;
  itemId: string;
  itemName: string;
  batch: string | null;
  expiryDate: string | null;
  packSize: number;
  totalNumberOfPacks: number;
  item: {
  id: string;
  code: string;
};
} | null;
};

export type StockMovementDetailVariables = {
  storeId: string;
  id: string;
};

export type StockMovementDetailResult = {
  stockRelocation: ({
  __typename: "StockRelocationNode";
} & {
  lines: {
  nodes: Array<StockMovementLineFragment>;
};
} & StockMovementInfoFragment) | ({
  __typename: "RecordNotFound";
} & {
  description: string;
});
};

export const StockMovementDetail = {
  query: "query StockMovementDetail($storeId: String!, $id: String!) {\n  stockRelocation(storeId: $storeId, id: $id) {\n    __typename\n    ... on StockRelocationNode {\n      ...StockMovementInfo\n      lines {\n        nodes {\n          ...StockMovementLine\n        }\n      }\n    }\n    ... on RecordNotFound {\n      description\n    }\n  }\n}\n\nfragment StockMovementInfo on StockRelocationNode {\n  id\n  stockMovementNumber\n  status\n  createdDatetime\n  confirmedDatetime\n  finalisedDatetime\n  comment\n  lineCount\n  user {\n    username\n    email\n  }\n}\n\nfragment StockMovementLine on StockRelocationLineNode {\n  id\n  stockLineId\n  numberOfPacks\n  sourceLocation {\n    id\n    code\n  }\n  destinationLocation {\n    id\n    code\n  }\n  stockLine {\n    id\n    itemId\n    itemName\n    batch\n    expiryDate\n    packSize\n    totalNumberOfPacks\n    item {\n      id\n      code\n    }\n  }\n}",
} as TypedDocument<StockMovementDetailResult, StockMovementDetailVariables>;

export type UpdateStockMovementVariables = {
  storeId: string;
  input: {
    id: string;
    comment?: string | null;
    status?: "NEW" | "CONFIRMED" | "FINALISED" | null;
  };
};

export type UpdateStockMovementResult = {
  updateStockRelocation: ({
  __typename: "StockRelocationNode";
} & StockMovementInfoFragment) | ({
  __typename: "UpdateStockRelocationError";
} & {
  error: ({
  __typename: "NotEnoughStock";
} & {
  stockLineId: string;
} & {
  description: string;
}) | ({
  __typename: "LocationOnHold";
} & {
  locationId: string;
} & {
  description: string;
});
});
};

export const UpdateStockMovement = {
  query: "mutation UpdateStockMovement($storeId: String!, $input: UpdateStockRelocationInput!) {\n  updateStockRelocation(storeId: $storeId, input: $input) {\n    __typename\n    ... on StockRelocationNode {\n      ...StockMovementInfo\n    }\n    ... on UpdateStockRelocationError {\n      error {\n        __typename\n        description\n        ... on NotEnoughStock {\n          stockLineId\n        }\n        ... on LocationOnHold {\n          locationId\n        }\n      }\n    }\n  }\n}\n\nfragment StockMovementInfo on StockRelocationNode {\n  id\n  stockMovementNumber\n  status\n  createdDatetime\n  confirmedDatetime\n  finalisedDatetime\n  comment\n  lineCount\n  user {\n    username\n    email\n  }\n}",
} as TypedDocument<UpdateStockMovementResult, UpdateStockMovementVariables>;

export type DeleteStockMovementVariables = {
  storeId: string;
  input: {
    id: string;
  };
};

export type DeleteStockMovementResult = {
  deleteStockRelocation: ({
  id: string;
});
};

export const DeleteStockMovement = {
  query: "mutation DeleteStockMovement($storeId: String!, $input: DeleteStockRelocationInput!) {\n  deleteStockRelocation(storeId: $storeId, input: $input) {\n    ... on DeleteResponse {\n      id\n    }\n  }\n}",
} as TypedDocument<DeleteStockMovementResult, DeleteStockMovementVariables>;
