/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type InboundCurrenciesVariables = Record<string, never>;

export type InboundCurrenciesResult = {
  currencies: ({
  __typename: "CurrencyConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  rate: number;
  isHomeCurrency: boolean;
}>;
});
};

export const InboundCurrencies = {
  query: "query inboundCurrencies {\n  currencies(filter: {isActive: true}) {\n    ... on CurrencyConnector {\n      __typename\n      nodes {\n        id\n        code\n        rate\n        isHomeCurrency\n      }\n    }\n  }\n}",
} as TypedDocument<InboundCurrenciesResult, InboundCurrenciesVariables>;

export type InboundCampaignsVariables = {
  storeId: string;
};

export type InboundCampaignsResult = {
  campaigns: ({
  __typename: "CampaignConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const InboundCampaigns = {
  query: "query inboundCampaigns($storeId: String!) {\n  campaigns(storeId: $storeId) {\n    ... on CampaignConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<InboundCampaignsResult, InboundCampaignsVariables>;

export type InboundProgramsVariables = {
  storeId: string;
};

export type InboundProgramsResult = {
  programs: ({
  __typename: "ProgramConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const InboundPrograms = {
  query: "query inboundPrograms($storeId: String!) {\n  programs(storeId: $storeId) {\n    ... on ProgramConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<InboundProgramsResult, InboundProgramsVariables>;

export type InternalOrderLinesVariables = {
  storeId: string;
  requisitionId: string;
};

export type InternalOrderLinesResult = {
  requisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
  requisitionNumber: number;
  lines: {
  nodes: Array<{
  id: string;
  itemName: string;
  requestedQuantity: number;
  item: {
  id: string;
  code: string;
};
}>;
};
});
};

export const InternalOrderLines = {
  query: "query internalOrderLines($storeId: String!, $requisitionId: String!) {\n  requisition(storeId: $storeId, id: $requisitionId) {\n    __typename\n    ... on RequisitionNode {\n      id\n      requisitionNumber\n      lines {\n        nodes {\n          id\n          itemName\n          requestedQuantity\n          item {\n            id\n            code\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<InternalOrderLinesResult, InternalOrderLinesVariables>;

export type PurchaseOrderLinesVariables = {
  storeId: string;
  purchaseOrderId: string;
};

export type PurchaseOrderLinesResult = {
  purchaseOrder: ({
  __typename: "PurchaseOrderNode";
} & {
  id: string;
  lines: {
  nodes: Array<{
  id: string;
  lineNumber: number;
  requestedPackSize: number;
  item: {
  id: string;
  code: string;
  name: string;
};
}>;
};
});
};

export const PurchaseOrderLines = {
  query: "query purchaseOrderLines($storeId: String!, $purchaseOrderId: String!) {\n  purchaseOrder(storeId: $storeId, id: $purchaseOrderId) {\n    __typename\n    ... on PurchaseOrderNode {\n      id\n      lines {\n        nodes {\n          id\n          lineNumber\n          requestedPackSize\n          item {\n            id\n            code\n            name\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<PurchaseOrderLinesResult, PurchaseOrderLinesVariables>;

export type SupplierInternalOrdersVariables = {
  storeId: string;
  otherPartyId: string;
};

export type SupplierInternalOrdersResult = {
  requisitions: ({
  __typename: "RequisitionConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  requisitionNumber: number;
  status: "DRAFT" | "NEW" | "SENT" | "FINALISED";
}>;
});
};

export const SupplierInternalOrders = {
  query: "query supplierInternalOrders($storeId: String!, $otherPartyId: String!) {\n  requisitions(\n    storeId: $storeId\n    filter: {type: {equalTo: REQUEST}, otherPartyId: {equalTo: $otherPartyId}}\n    sort: [{key: requisitionNumber, desc: true}]\n  ) {\n    ... on RequisitionConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        requisitionNumber\n        status\n      }\n    }\n  }\n}",
} as TypedDocument<SupplierInternalOrdersResult, SupplierInternalOrdersVariables>;
