use super::{
    ChangelogRepository, RowActionType, StorageConnection,
};

use crate::{
    diesel_macros::define_batch_table, repository_error::RepositoryError, SourceSiteId,
};
use diesel::prelude::*;
use diesel_derive_enum::DbEnum;
use serde::{Deserialize, Serialize};

#[derive(Clone, Eq, PartialEq, Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PluginType {
    AverageMonthlyConsumption,
    TransformRequestRequisitionLines,
    GetConsumption,
    GraphqlQuery,
    // TODO backwards compatibility ? When integrating this one via sync
    Processor,
    Schedule,
}

#[derive(Clone, PartialEq, Eq, Debug, Default, Serialize, Deserialize)]
pub struct PluginTypes(pub Vec<PluginType>);

impl From<String> for PluginTypes {
    fn from(value: String) -> Self {
        serde_json::from_str(&value).unwrap_or_default()
    }
}

impl From<PluginTypes> for String {
    fn from(value: PluginTypes) -> Self {
        serde_json::to_string(&value).unwrap_or_default()
    }
}

#[derive(DbEnum, Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[DbValueStyle = "SCREAMING_SNAKE_CASE"]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[cfg_attr(test, derive(strum::EnumIter))]
pub enum PluginVariantType {
    #[default]
    BoaJs,
}

define_batch_table! {
  struct: BackendPluginRow,
  repo: BackendPluginRowRepository,
  // `types` is `#[diesel(serialize_as = String)]` => owned-only Insertable.
  owned_insert,
  table: backend_plugin (id) {
      id -> Text,
      code -> Text,
      version -> Text,
      bundle_base64 -> Text,
      types -> Text,
      variant_type  -> crate::db_diesel::backend_plugin_row::PluginVariantTypeMapping,
  }
}

#[derive(
    Clone, Insertable, Default, Queryable, Debug, PartialEq, Eq, AsChangeset, Serialize, Deserialize,
)]
#[diesel(table_name = backend_plugin)]
pub struct BackendPluginRow {
    pub id: String,
    pub code: String,
    pub version: String,
    pub bundle_base64: String,
    #[diesel(serialize_as = String)]
    #[diesel(deserialize_as = String)]
    pub types: PluginTypes,
    pub variant_type: PluginVariantType,
}
pub struct BackendPluginRowRepository<'a> {
    connection: &'a StorageConnection,
}

impl<'a> BackendPluginRowRepository<'a> {
    pub fn new(connection: &'a StorageConnection) -> Self {
        BackendPluginRowRepository { connection }
    }

    pub fn find_one_by_id(&self, id: &str) -> Result<Option<BackendPluginRow>, RepositoryError> {
        let result = backend_plugin::table
            .filter(backend_plugin::id.eq(id))
            .first(self.connection.lock().connection())
            .optional()?;
        Ok(result)
    }

    pub fn all(&self) -> Result<Vec<BackendPluginRow>, RepositoryError> {
        let result = backend_plugin::table
            .order_by(backend_plugin::id)
            .load(self.connection.lock().connection())?;

        Ok(result)
    }

    pub fn _upsert_one(&self, row: &BackendPluginRow) -> Result<(), RepositoryError> {
        diesel::insert_into(backend_plugin::table)
            .values(row.clone())
            .on_conflict(backend_plugin::id)
            .do_update()
            .set(row.clone())
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    /// Hand-written batch upsert (NOT generated by `define_batch_table!`): the
    /// `types` field is `#[diesel(serialize_as = String)]`, so the row only
    /// implements `Insertable`/`ToSql` for the OWNED struct — the raw-SQL
    /// `WalkRow` path can't bind the field type directly. Postgres does one
    /// multi-row statement (owned values); sqlite loops the per-row upsert.
    pub(crate) fn batch_upsert(
        &self,
        rows: Vec<&BackendPluginRow>,
    ) -> Result<(), RepositoryError> {
        if rows.is_empty() {
            return Ok(());
        }
        #[cfg(feature = "postgres")]
        {
            let owned: Vec<BackendPluginRow> = rows.iter().map(|r| (*r).clone()).collect();
            diesel::insert_into(backend_plugin::table)
                .values(owned)
                .on_conflict(backend_plugin::id)
                .do_update()
                .set((
                    backend_plugin::code.eq(diesel::upsert::excluded(backend_plugin::code)),
                    backend_plugin::version.eq(diesel::upsert::excluded(backend_plugin::version)),
                    backend_plugin::bundle_base64
                        .eq(diesel::upsert::excluded(backend_plugin::bundle_base64)),
                    backend_plugin::types.eq(diesel::upsert::excluded(backend_plugin::types)),
                    backend_plugin::variant_type
                        .eq(diesel::upsert::excluded(backend_plugin::variant_type)),
                ))
                .execute(self.connection.lock().connection())?;
        }
        #[cfg(not(feature = "postgres"))]
        for row in rows {
            self._upsert_one(row)?;
        }
        Ok(())
    }

    pub fn upsert_one(&self, row: BackendPluginRow) -> Result<(), RepositoryError> {
        self._upsert_one(&row)?;
        let changelog = BackendPluginRow::generate_changelog(
            row.id.clone(),
            self.connection,
            RowActionType::Upsert,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)
    }

    pub fn delete(&self, id: &str) -> Result<(), RepositoryError> {
        let changelog = BackendPluginRow::generate_changelog(
            id.to_string(),
            self.connection,
            RowActionType::Delete,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)?;

        diesel::delete(backend_plugin::table.filter(backend_plugin::id.eq(id)))
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    pub fn find_many_by_id(&self, ids: &[String]) -> Result<Vec<BackendPluginRow>, RepositoryError> {
        Ok(backend_plugin::table
            .filter(backend_plugin::id.eq_any(ids))
            .load(self.connection.lock().connection())?)
    }

    pub(crate) fn _batch_delete(&self, ids: &[&str]) -> Result<(), RepositoryError> {
        if ids.is_empty() {
            return Ok(());
        }
        diesel::delete(backend_plugin::table.filter(backend_plugin::id.eq_any(ids)))
            .execute(self.connection.lock().connection())?;
        Ok(())
    }
}

#[cfg(test)]
mod test {
    use crate::{mock::MockDataInserts, test_db::setup_all};

    use super::*;
    use diesel::{sql_query, sql_types::Text};
    use strum::IntoEnumIterator;
    use util::assert_variant;

    #[actix_rt::test]
    async fn backend_plugin_row_enum() {
        let (_, connection, _, _) =
            setup_all("backend_plugin_row_enum", MockDataInserts::none()).await;

        let repo = BackendPluginRowRepository::new(&connection);
        // Try upsert all plugin_variant types, confirm that diesel enums match postgres
        for variant in PluginVariantType::iter() {
            let id = format!("{variant:?}");
            let result = repo.upsert_one(BackendPluginRow {
                id: id.clone(),
                variant_type: variant.clone(),
                ..Default::default()
            });
            assert_variant!(result, Ok(_) => {});

            let result = repo.find_one_by_id(&id).unwrap().unwrap();
            assert_eq!(result.variant_type, variant);
        }
    }

    #[derive(QueryableByName)]
    struct Check {
        #[diesel(sql_type = Text)]
        types: String,
    }

    #[actix_rt::test]
    async fn backend_plugin_row() {
        let (_, connection, _, _) = setup_all("backend_plugin_row", MockDataInserts::none()).await;

        let repo = BackendPluginRowRepository::new(&connection);
        let id = "backend_plugin_row".to_string();

        let types = PluginTypes(vec![
            PluginType::AverageMonthlyConsumption,
            PluginType::TransformRequestRequisitionLines,
        ]);
        let _ = repo.upsert_one(BackendPluginRow {
            id: id.clone(),
            types: types.clone(),
            ..Default::default()
        });

        let result = repo.find_one_by_id(&id).unwrap().unwrap();
        assert_eq!(result.types, types);

        let result: Vec<Check> = sql_query("SELECT types FROM backend_plugin")
            .load(connection.lock().connection())
            .unwrap();

        // Showing that types serializes to a readable text in DB field
        assert_eq!(
            result[0].types,
            r#"["average_monthly_consumption","transform_request_requisition_lines"]"#
        );
    }
}
