//! Hand-built multi-row upsert/insert that works on BOTH backends in a single
//! statement.
//!
//! Diesel's typed `insert_into(..).values(slice).on_conflict(..).do_update()`
//! emits a real multi-row `INSERT ... ON CONFLICT DO UPDATE` on Postgres, but
//! SQLite has no typed multi-row on-conflict-upsert, so the typed path there can
//! only loop per row. The SQL itself —
//! `INSERT INTO t (cols) VALUES (..),(..) ON CONFLICT(id) DO UPDATE SET col = excluded.col`
//! — is perfectly valid SQLite; we just have to build it by hand via
//! `QueryFragment`/`AstPass` (bypassing diesel's typed insert) to emit it.
//!
//! `define_batch_table!` generates the [`BatchUpsertable`] + [`WalkRow`] impls
//! (it already lists every column), then calls [`batch_upsert`] for both backends.
//! Variable-length SQL is kept out of the prepared-statement cache via
//! `unsafe_to_cache_prepared`.

use diesel::query_builder::{AstPass, QueryFragment, QueryId};
use diesel::query_dsl::RunQueryDsl;
use diesel::result::QueryResult;

/// Max bind parameters allowed in one statement, per backend, with headroom. Every batch
/// statement (multi-row upsert, `INSERT`, the changelog/sync_buffer batches) must chunk
/// under this so it never exceeds the backend's hard cap:
/// - Postgres caps a statement at 65535 bind parameters.
/// - SQLite's `SQLITE_MAX_VARIABLE_NUMBER` defaults to 32766 (SQLite >= 3.32; our bundled
///   libsqlite3-sys is newer). Stay well under it.
#[cfg(feature = "postgres")]
pub const PARAM_BUDGET: usize = 60000;
#[cfg(not(feature = "postgres"))]
pub const PARAM_BUDGET: usize = 32000;

/// Rows per chunk for a statement that binds `columns_per_row` params per row, kept under
/// [`PARAM_BUDGET`]. Always at least 1 (a single over-wide row still goes out on its own).
/// `columns_per_row == 0` means "no per-row bind params" — caller can send everything at once.
pub fn max_rows_per_chunk(columns_per_row: usize) -> usize {
    match columns_per_row {
        0 => usize::MAX,
        n => (PARAM_BUDGET / n).max(1),
    }
}

/// The active diesel backend. Exactly one of `sqlite`/`postgres` is enabled in
/// this crate; the generated `WalkRow` impls resolve `ToSql`/`HasSqlType`
/// against this so callers don't have to name a backend.
#[cfg(feature = "postgres")]
pub type DbType = diesel::pg::Pg;
#[cfg(not(feature = "postgres"))]
pub type DbType = diesel::sqlite::Sqlite;

/// Compile-time table metadata. Generated per row struct by `define_batch_table!`.
/// The conflict target is always `id`.
pub trait BatchUpsertable {
    /// Physical table name.
    const TABLE_NAME: &'static str;
    /// All column names, in the order `WalkRow` binds them (pk first).
    const COLUMNS: &'static [&'static str];
    /// Conflict-target column (always the `id` pk).
    const CONFLICT: &'static str;
    /// Columns assigned in `DO UPDATE SET col = excluded.col` (every column except the pk).
    const UPDATE: &'static [&'static str];
}

/// Pushes one row's bind params, in `COLUMNS` order, skipping any column named in
/// `excludes`. Generated by `define_batch_table!`; the binding order matches
/// `BatchUpsertable::COLUMNS` (minus excludes) so the column list and the values
/// stay aligned.
pub trait WalkRow {
    fn walk_row<'b>(&'b self, excludes: &[&str], out: AstPass<'_, 'b, DbType>) -> QueryResult<()>;
}

// Blanket impls over references so callers can pass `&[&Row]` (the batch helpers
// hand us borrowed rows — no clone) and still satisfy `U: BatchUpsertable + WalkRow`.
impl<U: BatchUpsertable> BatchUpsertable for &U {
    const TABLE_NAME: &'static str = U::TABLE_NAME;
    const COLUMNS: &'static [&'static str] = U::COLUMNS;
    const CONFLICT: &'static str = U::CONFLICT;
    const UPDATE: &'static [&'static str] = U::UPDATE;
}

impl<U: WalkRow> WalkRow for &U {
    fn walk_row<'b>(&'b self, excludes: &[&str], out: AstPass<'_, 'b, DbType>) -> QueryResult<()> {
        (*self).walk_row(excludes, out)
    }
}

/// Emit the `(col, col, ...)` column list, skipping `excludes`.
fn push_column_list<U: BatchUpsertable>(
    out: &mut AstPass<'_, '_, DbType>,
    excludes: &[&str],
) -> QueryResult<()> {
    let mut first = true;
    for col in U::COLUMNS {
        if excludes.contains(col) {
            continue;
        }
        if !first {
            out.push_sql(", ");
        }
        first = false;
        out.push_identifier(col)?;
    }
    Ok(())
}

/// Multi-row `INSERT ... ON CONFLICT(id) DO UPDATE SET col = excluded.col`.
/// Build with [`batch_upsert`]; run with `.execute(conn)`.
pub struct BatchUpsert<'a, U> {
    rows: &'a [U],
}

/// One-statement upsert of `rows`. Caller chunks under the backend's
/// bind-parameter limit and wraps in a transaction. Empty slice is a no-op.
pub fn batch_upsert<U>(rows: &[U]) -> BatchUpsert<'_, U> {
    BatchUpsert { rows }
}

impl<U> QueryId for BatchUpsert<'_, U> {
    type QueryId = ();
    const HAS_STATIC_QUERY_ID: bool = false;
}

impl<U> QueryFragment<DbType> for BatchUpsert<'_, U>
where
    U: BatchUpsertable + WalkRow,
{
    fn walk_ast<'b>(&'b self, mut out: AstPass<'_, 'b, DbType>) -> QueryResult<()> {
        if self.rows.is_empty() {
            return Ok(());
        }
        // SQL string length depends on row count; don't pollute the cache.
        out.unsafe_to_cache_prepared();

        out.push_sql("INSERT INTO ");
        out.push_identifier(U::TABLE_NAME)?;
        out.push_sql(" (");
        push_column_list::<U>(&mut out, &[])?;
        out.push_sql(") VALUES ");

        for (i, row) in self.rows.iter().enumerate() {
            if i > 0 {
                out.push_sql(", ");
            }
            out.push_sql("(");
            row.walk_row(&[], out.reborrow())?;
            out.push_sql(")");
        }

        out.push_sql(" ON CONFLICT(");
        out.push_identifier(U::CONFLICT)?;
        out.push_sql(") DO UPDATE SET ");
        for (i, col) in U::UPDATE.iter().enumerate() {
            if i > 0 {
                out.push_sql(", ");
            }
            out.push_identifier(col)?;
            out.push_sql(" = excluded.");
            out.push_identifier(col)?;
        }
        Ok(())
    }
}

impl<U, Conn> RunQueryDsl<Conn> for BatchUpsert<'_, U> {}

/// Multi-row `INSERT` with no conflict clause, skipping `excludes` columns
/// (e.g. an auto-assigned pk). Build with [`batch_insert`].
pub struct BatchInsert<'a, U> {
    rows: &'a [U],
    excludes: &'a [&'a str],
}

/// One-statement insert of `rows`, omitting the `excludes` columns from both the
/// column list and the bindings. Empty slice is a no-op.
pub fn batch_insert<'a, U>(rows: &'a [U], excludes: &'a [&'a str]) -> BatchInsert<'a, U> {
    BatchInsert { rows, excludes }
}

impl<U> QueryId for BatchInsert<'_, U> {
    type QueryId = ();
    const HAS_STATIC_QUERY_ID: bool = false;
}

impl<U> QueryFragment<DbType> for BatchInsert<'_, U>
where
    U: BatchUpsertable + WalkRow,
{
    fn walk_ast<'b>(&'b self, mut out: AstPass<'_, 'b, DbType>) -> QueryResult<()> {
        if self.rows.is_empty() {
            return Ok(());
        }
        out.unsafe_to_cache_prepared();

        out.push_sql("INSERT INTO ");
        out.push_identifier(U::TABLE_NAME)?;
        out.push_sql(" (");
        push_column_list::<U>(&mut out, self.excludes)?;
        out.push_sql(") VALUES ");

        for (i, row) in self.rows.iter().enumerate() {
            if i > 0 {
                out.push_sql(", ");
            }
            out.push_sql("(");
            row.walk_row(self.excludes, out.reborrow())?;
            out.push_sql(")");
        }
        Ok(())
    }
}

impl<U, Conn> RunQueryDsl<Conn> for BatchInsert<'_, U> {}
