use super::{
    ChangelogRepository, RowActionType, StorageConnection,
};

use crate::{
    diesel_macros::define_batch_table, repository_error::RepositoryError, SourceSiteId,
};
use diesel::prelude::*;
use diesel_derive_enum::DbEnum;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, PartialEq, Eq, Debug, Clone)]
pub struct FrontendPluginFile {
    pub file_name: String,
    pub file_content_base64: String,
}

#[derive(Clone, PartialEq, Eq, Debug, Default, Serialize, Deserialize)]
pub struct FrontendPluginFiles(pub Vec<FrontendPluginFile>);

impl From<String> for FrontendPluginFiles {
    fn from(value: String) -> Self {
        serde_json::from_str(&value).unwrap_or_default()
    }
}

impl From<FrontendPluginFiles> for String {
    fn from(value: FrontendPluginFiles) -> Self {
        serde_json::to_string(&value).unwrap_or_default()
    }
}

#[derive(Clone, PartialEq, Eq, Debug, Default, Serialize, Deserialize)]
pub struct FrontendPluginTypes(pub Vec<String>);

impl From<String> for FrontendPluginTypes {
    fn from(value: String) -> Self {
        serde_json::from_str(&value).unwrap_or_default()
    }
}

impl From<FrontendPluginTypes> for String {
    fn from(value: FrontendPluginTypes) -> Self {
        serde_json::to_string(&value).unwrap_or_default()
    }
}

#[derive(DbEnum, Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[DbValueStyle = "SCREAMING_SNAKE_CASE"]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[cfg_attr(test, derive(strum::EnumIter))]
pub enum FrontendPluginVariantType {
    #[default]
    BoaJs,
}

define_batch_table! {
  struct: FrontendPluginRow,
  repo: FrontendPluginRowRepository,
  // `files`/`variant_type` are `#[diesel(serialize_as = String)]` => owned-only Insertable.
  owned_insert,
  table: frontend_plugin (id) {
      id -> Text,
      code -> Text,
      version -> Text,
      entry_point -> Text,
      types -> Text,
      files -> Text,
  }
}

#[derive(
    Clone, Insertable, Default, Queryable, Debug, PartialEq, Eq, AsChangeset, Serialize, Deserialize,
)]
#[diesel(table_name = frontend_plugin)]
pub struct FrontendPluginRow {
    pub id: String,
    pub code: String,
    pub version: String,
    pub entry_point: String,
    #[diesel(serialize_as = String)]
    #[diesel(deserialize_as = String)]
    pub types: FrontendPluginTypes,
    #[diesel(serialize_as = String)]
    #[diesel(deserialize_as = String)]
    pub files: FrontendPluginFiles,
}
pub struct FrontendPluginRowRepository<'a> {
    connection: &'a StorageConnection,
}

impl<'a> FrontendPluginRowRepository<'a> {
    pub fn new(connection: &'a StorageConnection) -> Self {
        FrontendPluginRowRepository { connection }
    }

    pub fn find_one_by_id(&self, id: &str) -> Result<Option<FrontendPluginRow>, RepositoryError> {
        let result = frontend_plugin::table
            .filter(frontend_plugin::id.eq(id))
            .first(self.connection.lock().connection())
            .optional()?;
        Ok(result)
    }

    pub fn all(&self) -> Result<Vec<FrontendPluginRow>, RepositoryError> {
        let result = frontend_plugin::table
            .order_by(frontend_plugin::id)
            .load(self.connection.lock().connection())?;

        Ok(result)
    }

    pub fn _upsert_one(&self, row: &FrontendPluginRow) -> Result<(), RepositoryError> {
        diesel::insert_into(frontend_plugin::table)
            .values(row.clone())
            .on_conflict(frontend_plugin::id)
            .do_update()
            .set(row.clone())
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    /// Hand-written batch upsert (NOT generated by `define_batch_table!`): `types`
    /// and `files` are `#[diesel(serialize_as = String)]`, so the row only
    /// implements `Insertable`/`ToSql` for the OWNED struct — the raw-SQL
    /// `WalkRow` path can't bind the field types directly. Postgres does one
    /// multi-row statement (owned values); sqlite loops the per-row upsert.
    pub(crate) fn batch_upsert(
        &self,
        rows: Vec<&FrontendPluginRow>,
    ) -> Result<(), RepositoryError> {
        if rows.is_empty() {
            return Ok(());
        }
        #[cfg(feature = "postgres")]
        {
            let owned: Vec<FrontendPluginRow> = rows.iter().map(|r| (*r).clone()).collect();
            diesel::insert_into(frontend_plugin::table)
                .values(owned)
                .on_conflict(frontend_plugin::id)
                .do_update()
                .set((
                    frontend_plugin::code.eq(diesel::upsert::excluded(frontend_plugin::code)),
                    frontend_plugin::version
                        .eq(diesel::upsert::excluded(frontend_plugin::version)),
                    frontend_plugin::entry_point
                        .eq(diesel::upsert::excluded(frontend_plugin::entry_point)),
                    frontend_plugin::types.eq(diesel::upsert::excluded(frontend_plugin::types)),
                    frontend_plugin::files.eq(diesel::upsert::excluded(frontend_plugin::files)),
                ))
                .execute(self.connection.lock().connection())?;
        }
        #[cfg(not(feature = "postgres"))]
        for row in rows {
            self._upsert_one(row)?;
        }
        Ok(())
    }

    pub fn upsert_one(&self, row: FrontendPluginRow) -> Result<(), RepositoryError> {
        self._upsert_one(&row)?;
        let changelog = FrontendPluginRow::generate_changelog(
            row.id.clone(),
            self.connection,
            RowActionType::Upsert,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)
    }

    pub fn delete(&self, id: &str) -> Result<(), RepositoryError> {
        let changelog = FrontendPluginRow::generate_changelog(
            id.to_string(),
            self.connection,
            RowActionType::Delete,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)?;

        diesel::delete(frontend_plugin::table.filter(frontend_plugin::id.eq(id)))
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    pub(crate) fn _batch_delete(&self, ids: &[&str]) -> Result<(), RepositoryError> {
        if ids.is_empty() {
            return Ok(());
        }
        diesel::delete(frontend_plugin::table.filter(frontend_plugin::id.eq_any(ids)))
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    pub fn find_many_by_id(&self, ids: &[String]) -> Result<Vec<FrontendPluginRow>, RepositoryError> {
        Ok(frontend_plugin::table
            .filter(frontend_plugin::id.eq_any(ids))
            .load(self.connection.lock().connection())?)
    }
}
