use super::item_direction_row::item_direction::dsl::*;
use super::item_row::item;
use crate::diesel_macros::define_linked_tables;
use crate::{
    ChangelogRepository, ChangelogSyncType, Delete, RepositoryError, RowActionType, SourceSiteId,
    StorageConnection, Upsert,
};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};

define_linked_tables! {
    view: item_direction = "item_direction_view",
    core: item_direction_with_links = "item_direction",
    struct: ItemDirectionRow,
    repo: ItemDirectionRowRepository,
    shared: {
        directions -> Text,
        priority -> BigInt,
    },
    links: {
        item_link_id -> item_id,
    },
    optional_links: {
    }
}

joinable!(item_direction -> item (item_id));
allow_tables_to_appear_in_same_query!(item_direction, item);

#[derive(
    Clone, Default, Queryable, Debug, PartialEq, Eq, Serialize, Deserialize,
)]
#[diesel(table_name = item_direction)]
pub struct ItemDirectionRow {
    pub id: String,
    pub directions: String,
    pub priority: i64,
    // Resolved from item_link - must be last to match view column order
    pub item_id: String,
}

pub struct ItemDirectionRowRepository<'a> {
    connection: &'a StorageConnection,
}

impl<'a> ItemDirectionRowRepository<'a> {
    pub fn new(connection: &'a StorageConnection) -> Self {
        ItemDirectionRowRepository { connection }
    }

    fn _upsert_one(&self, row: &ItemDirectionRow) -> Result<(), RepositoryError> {
        // `_upsert` is generated by `define_linked_tables!` and writes to the core
        // table (item_direction_with_links), resolving item_id -> item_link_id.
        self._upsert(row)?;
        Ok(())
    }

    pub fn upsert_one(&self, row: &ItemDirectionRow) -> Result<(), RepositoryError> {
        self._upsert_one(row)?;
        let changelog = ItemDirectionRow::generate_changelog(
            row.id.clone(),
            self.connection,
            RowActionType::Upsert,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)
    }

    pub fn find_all(&self) -> Result<Vec<ItemDirectionRow>, RepositoryError> {
        let result = item_direction.load(self.connection.lock().connection())?;
        Ok(result)
    }

    pub fn find_one_by_id(
        &self,
        item_direction_id: &str,
    ) -> Result<Option<ItemDirectionRow>, RepositoryError> {
        let result = item_direction
            .filter(id.eq(item_direction_id))
            .first(self.connection.lock().connection())
            .optional()?;
        Ok(result)
    }

    pub fn find_many_by_id(
        &self,
        ids: &[String],
    ) -> Result<Vec<ItemDirectionRow>, RepositoryError> {
        Ok(item_direction
            .filter(id.eq_any(ids))
            .load(self.connection.lock().connection())?)
    }

    fn _delete(&self, item_direction_id: &str) -> Result<(), RepositoryError> {
        // Delete via the core table (item_direction is now a read view).
        diesel::delete(
            item_direction_with_links::table
                .filter(item_direction_with_links::id.eq(item_direction_id)),
        )
        .execute(self.connection.lock().connection())?;
        Ok(())
    }

    pub fn delete(&self, item_direction_id: &str) -> Result<(), RepositoryError> {
        self._delete(item_direction_id)?;
        let changelog = ItemDirectionRow::generate_changelog(
            item_direction_id.to_string(),
            self.connection,
            RowActionType::Delete,
            SourceSiteId::CurrentSiteId,
        )?;
        ChangelogRepository::new(self.connection).insert(&changelog)
    }
}

impl Upsert for ItemDirectionRow {
    fn upsert_sync(
        &self,
        con: &StorageConnection,
        sync_type: ChangelogSyncType,
    ) -> Result<(), RepositoryError> {
        ItemDirectionRowRepository::new(con)._upsert_one(self)?;

        let changelog = match sync_type {
            ChangelogSyncType::SyncTypeV5V6 { source_site_id } => Self::generate_changelog(
                self.id.clone(),
                con,
                RowActionType::Upsert,
                SourceSiteId::SourceSiteId(source_site_id),
            )?,
            ChangelogSyncType::SyncTypeV7 { changelog_row } => changelog_row,
        };

        ChangelogRepository::new(con).insert(&changelog)?;
        Ok(())
    }

    // Test only
    fn assert_upserted(&self, con: &StorageConnection) {
        assert_eq!(
            ItemDirectionRowRepository::new(con).find_one_by_id(&self.id),
            Ok(Some(self.clone()))
        )
    }
}

#[derive(Debug, Clone)]
pub struct ItemDirectionRowDelete(pub String);
impl Delete for ItemDirectionRowDelete {
    fn delete_sync(
        &self,
        con: &StorageConnection,
        sync_type: ChangelogSyncType,
    ) -> Result<(), RepositoryError> {
        let repo = ItemDirectionRowRepository::new(con);

        let changelog = match sync_type {
            ChangelogSyncType::SyncTypeV5V6 { source_site_id } => {
                ItemDirectionRow::generate_changelog(
                    self.0.clone(),
                    con,
                    RowActionType::Delete,
                    SourceSiteId::SourceSiteId(source_site_id),
                )?
            }
            ChangelogSyncType::SyncTypeV7 { changelog_row } => changelog_row,
        };

        repo._delete(&self.0)?;
        ChangelogRepository::new(con).insert(&changelog)?;
        Ok(())
    }

    // Test only
    fn assert_deleted(&self, con: &StorageConnection) {
        assert_eq!(
            ItemDirectionRowRepository::new(con).find_one_by_id(&self.0),
            Ok(None)
        )
    }
}
