/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type BatchStockMovementLineVariables = {
  storeId: string;
  input: {
    upsert?: Array<{
    id: string;
    stockRelocationId: string;
    stockLineId: string;
    numberOfPacks: number;
    destinationLocationId?: string | null;
  }> | null;
    delete?: Array<string> | null;
    continueOnError?: boolean | null;
  };
};

export type BatchStockMovementLineResult = {
  batchStockRelocationLine: {
  upsert: Array<{
  id: string;
  response: ({
  __typename: "StockRelocationLineNode";
} & {
  id: string;
}) | ({
  __typename: "UpsertStockRelocationLineError";
} & {
  error: ({
  __typename: "NotEnoughStock";
} & {
  stockLineId: string;
} & {
  description: string;
}) | ({
  __typename: "LocationOnHold";
} & {
  locationId: string;
} & {
  description: string;
});
});
}> | null;
  delete: Array<{
  id: string;
  response: ({
  id: string;
});
}> | null;
};
};

export const BatchStockMovementLine = {
  query: "mutation BatchStockMovementLine($storeId: String!, $input: BatchStockRelocationLineInput!) {\n  batchStockRelocationLine(storeId: $storeId, input: $input) {\n    upsert {\n      id\n      response {\n        __typename\n        ... on StockRelocationLineNode {\n          id\n        }\n        ... on UpsertStockRelocationLineError {\n          error {\n            __typename\n            description\n            ... on NotEnoughStock {\n              stockLineId\n            }\n            ... on LocationOnHold {\n              locationId\n            }\n          }\n        }\n      }\n    }\n    delete {\n      id\n      response {\n        ... on DeleteResponse {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<BatchStockMovementLineResult, BatchStockMovementLineVariables>;
