/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type RequisitionRowFragment = {
  id: string;
  requisitionNumber: number;
  status: "DRAFT" | "NEW" | "SENT" | "FINALISED";
  createdDatetime: string;
  colour: string | null;
  comment: string | null;
  otherPartyName: string;
  otherParty: {
  store: {
  isDisabled: boolean;
} | null;
};
  approvalStatus: "NONE" | "PENDING" | "APPROVED" | "DENIED" | "AUTO_APPROVED" | "APPROVED_BY_ANOTHER" | "DENIED_BY_ANOTHER";
  programName: string | null;
  orderType: string | null;
  period: {
  name: string;
} | null;
  shipments: {
  totalCount: number;
};
};

export type RequisitionsVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    userId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    requisitionNumber?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    type?: {
    equalTo?: "REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY" | null;
    equalAny?: Array<"REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY"> | null;
    notEqualTo?: "REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY" | null;
    notEqualAll?: Array<"REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY"> | null;
  } | null;
    status?: {
    equalTo?: "DRAFT" | "NEW" | "SENT" | "FINALISED" | null;
    equalAny?: Array<"DRAFT" | "NEW" | "SENT" | "FINALISED"> | null;
    notEqualTo?: "DRAFT" | "NEW" | "SENT" | "FINALISED" | null;
    notEqualAll?: Array<"DRAFT" | "NEW" | "SENT" | "FINALISED"> | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    sentDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    finalisedDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    expectedDeliveryDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    otherPartyName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    otherPartyId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    colour?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    theirReference?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    comment?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    orderType?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    aShipmentHasBeenCreated?: boolean | null;
    periodId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    elmisCode?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isEmergency?: boolean | null;
    automaticallyCreated?: boolean | null;
    isProgramRequisition?: boolean | null;
    hasOutstandingLines?: boolean | null;
  } | null;
  sort?: Array<{
    key: "requisitionNumber" | "type" | "comment" | "status" | "otherPartyName" | "sentDatetime" | "createdDatetime" | "finalisedDatetime" | "expectedDeliveryDate" | "theirReference" | "orderType" | "programName" | "periodStartDate";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type RequisitionsResult = {
  requisitions: ({
  __typename: "RequisitionConnector";
} & {
  totalCount: number;
  nodes: Array<RequisitionRowFragment>;
});
};

export const Requisitions = {
  query: "query requisitions($storeId: String!, $filter: RequisitionFilterInput, $sort: [RequisitionSortInput!], $page: PaginationInput) {\n  requisitions(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on RequisitionConnector {\n      __typename\n      totalCount\n      nodes {\n        ...RequisitionRow\n      }\n    }\n  }\n}\n\nfragment RequisitionRow on RequisitionNode {\n  id\n  requisitionNumber\n  status\n  createdDatetime\n  colour\n  comment\n  otherPartyName\n  otherParty(storeId: $storeId) {\n    store {\n      isDisabled\n    }\n  }\n  approvalStatus\n  programName\n  orderType\n  period {\n    name\n  }\n  shipments {\n    totalCount\n  }\n}",
} as TypedDocument<RequisitionsResult, RequisitionsVariables>;

export type DeleteRequisitionsVariables = {
  storeId: string;
  ids: Array<{
    id: string;
  }>;
};

export type DeleteRequisitionsResult = {
  batchResponseRequisition: {
  deleteResponseRequisitions: Array<{
  id: string;
  response: ({
  __typename: "DeleteResponse";
} & {
  id: string;
}) | ({
  __typename: "DeleteResponseRequisitionError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
}> | null;
};
};

export const DeleteRequisitions = {
  query: "mutation deleteRequisitions($storeId: String!, $ids: [DeleteResponseRequisitionInput!]!) {\n  batchResponseRequisition(\n    storeId: $storeId\n    input: {deleteResponseRequisitions: $ids}\n  ) {\n    deleteResponseRequisitions {\n      id\n      response {\n        ... on DeleteResponse {\n          __typename\n          id\n        }\n        ... on DeleteResponseRequisitionError {\n          __typename\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteRequisitionsResult, DeleteRequisitionsVariables>;

export type UpdateRequisitionColourVariables = {
  storeId: string;
  input: {
    id: string;
    colour?: string | null;
    theirReference?: string | null;
    comment?: string | null;
    status?: "FINALISED" | null;
  };
};

export type UpdateRequisitionColourResult = {
  updateResponseRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
  colour: string | null;
});
};

export const UpdateRequisitionColour = {
  query: "mutation updateRequisitionColour($storeId: String!, $input: UpdateResponseRequisitionInput!) {\n  updateResponseRequisition(storeId: $storeId, input: $input) {\n    ... on RequisitionNode {\n      __typename\n      id\n      colour\n    }\n  }\n}",
} as TypedDocument<UpdateRequisitionColourResult, UpdateRequisitionColourVariables>;
