/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type InternalOrderRowFragment = {
  id: string;
  requisitionNumber: number;
  status: "DRAFT" | "NEW" | "SENT" | "FINALISED";
  createdDatetime: string;
  colour: string | null;
  theirReference: string | null;
  comment: string | null;
  otherPartyName: string;
  otherParty: {
  store: {
  isDisabled: boolean;
} | null;
};
  approvalStatus: "NONE" | "PENDING" | "APPROVED" | "DENIED" | "AUTO_APPROVED" | "APPROVED_BY_ANOTHER" | "DENIED_BY_ANOTHER";
  program: {
  name: string;
} | null;
  orderType: string | null;
  period: {
  name: string;
} | null;
  lines: {
  totalCount: number;
};
};

export type InternalOrdersVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    userId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    requisitionNumber?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    type?: {
    equalTo?: "REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY" | null;
    equalAny?: Array<"REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY"> | null;
    notEqualTo?: "REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY" | null;
    notEqualAll?: Array<"REQUEST" | "RESPONSE" | "IMPREST" | "STOCK_HISTORY"> | null;
  } | null;
    status?: {
    equalTo?: "DRAFT" | "NEW" | "SENT" | "FINALISED" | null;
    equalAny?: Array<"DRAFT" | "NEW" | "SENT" | "FINALISED"> | null;
    notEqualTo?: "DRAFT" | "NEW" | "SENT" | "FINALISED" | null;
    notEqualAll?: Array<"DRAFT" | "NEW" | "SENT" | "FINALISED"> | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    sentDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    finalisedDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    expectedDeliveryDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    otherPartyName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    otherPartyId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    colour?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    theirReference?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    comment?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    orderType?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    aShipmentHasBeenCreated?: boolean | null;
    periodId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    elmisCode?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isEmergency?: boolean | null;
    automaticallyCreated?: boolean | null;
    isProgramRequisition?: boolean | null;
    hasOutstandingLines?: boolean | null;
  } | null;
  sort?: Array<{
    key: "requisitionNumber" | "type" | "comment" | "status" | "otherPartyName" | "sentDatetime" | "createdDatetime" | "finalisedDatetime" | "expectedDeliveryDate" | "theirReference" | "orderType" | "programName" | "periodStartDate";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type InternalOrdersResult = {
  requisitions: ({
  __typename: "RequisitionConnector";
} & {
  totalCount: number;
  nodes: Array<InternalOrderRowFragment>;
});
};

export const InternalOrders = {
  query: "query internalOrders($storeId: String!, $filter: RequisitionFilterInput, $sort: [RequisitionSortInput!], $page: PaginationInput) {\n  requisitions(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on RequisitionConnector {\n      __typename\n      totalCount\n      nodes {\n        ...InternalOrderRow\n      }\n    }\n  }\n}\n\nfragment InternalOrderRow on RequisitionNode {\n  id\n  requisitionNumber\n  status\n  createdDatetime\n  colour\n  theirReference\n  comment\n  otherPartyName\n  otherParty(storeId: $storeId) {\n    store {\n      isDisabled\n    }\n  }\n  approvalStatus\n  program {\n    name\n  }\n  orderType\n  period {\n    name\n  }\n  lines {\n    totalCount\n  }\n}",
} as TypedDocument<InternalOrdersResult, InternalOrdersVariables>;

export type DeleteInternalOrdersVariables = {
  storeId: string;
  ids: Array<{
    id: string;
  }>;
};

export type DeleteInternalOrdersResult = {
  batchRequestRequisition: {
  deleteRequestRequisitions: Array<{
  id: string;
  response: ({
  __typename: "DeleteResponse";
} & {
  id: string;
}) | ({
  __typename: "DeleteRequestRequisitionError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
}> | null;
};
};

export const DeleteInternalOrders = {
  query: "mutation deleteInternalOrders($storeId: String!, $ids: [DeleteRequestRequisitionInput!]!) {\n  batchRequestRequisition(\n    storeId: $storeId\n    input: {deleteRequestRequisitions: $ids}\n  ) {\n    deleteRequestRequisitions {\n      id\n      response {\n        ... on DeleteResponse {\n          __typename\n          id\n        }\n        ... on DeleteRequestRequisitionError {\n          __typename\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteInternalOrdersResult, DeleteInternalOrdersVariables>;

export type UpdateInternalOrderColourVariables = {
  storeId: string;
  input: {
    id: string;
    colour?: string | null;
    theirReference?: string | null;
    comment?: string | null;
    maxMonthsOfStock?: number | null;
    minMonthsOfStock?: number | null;
    status?: "SENT" | null;
    otherPartyId?: string | null;
    expectedDeliveryDate?: string | null;
    destinationCustomerId?: {
    value?: string | null;
  } | null;
  };
};

export type UpdateInternalOrderColourResult = {
  updateRequestRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
  colour: string | null;
});
};

export const UpdateInternalOrderColour = {
  query: "mutation updateInternalOrderColour($storeId: String!, $input: UpdateRequestRequisitionInput!) {\n  updateRequestRequisition(storeId: $storeId, input: $input) {\n    ... on RequisitionNode {\n      __typename\n      id\n      colour\n    }\n  }\n}",
} as TypedDocument<UpdateInternalOrderColourResult, UpdateInternalOrderColourVariables>;
