/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type InternalOrderListContextVariables = {
  storeId: string;
};

export type InternalOrderListContextResult = {
  storePreferences: {
  requestRequisitionRequiresAuthorisation: boolean;
};
  supplierProgramRequisitionSettings: Array<{
  programId: string;
}>;
};

export const InternalOrderListContext = {
  query: "query internalOrderListContext($storeId: String!) {\n  storePreferences(storeId: $storeId) {\n    requestRequisitionRequiresAuthorisation\n  }\n  supplierProgramRequisitionSettings(storeId: $storeId) {\n    programId\n  }\n}",
} as TypedDocument<InternalOrderListContextResult, InternalOrderListContextVariables>;
