export const IPC_MESSAGES = {
  DISCOVERED_SERVERS: 'discovered-servers',
  START_SERVER_DISCOVERY: 'start-server-discovery',
  CONNECT_TO_SERVER: 'connect-to-server',
  CONNECTED_SERVER: 'connected-server',
  START_BARCODE_SCAN: 'start-barcode-scan',
  STOP_BARCODE_SCAN: 'stop-barcode-scan',
  ON_BARCODE_SCAN: 'on-barcode-scan',
  GO_BACK_TO_DISCOVERY: 'go-back-to-discovery',
  READ_LOG: 'read-log',
  GET_PREFERENCE: 'get-preference',
  SET_PREFERENCE: 'set-preference',
  LINKED_BARCODE_SCANNER_DEVICE: 'linked-barcode-scanner-device',
  START_DEVICE_SCAN: 'start-device-scan',
  ON_DEVICE_MATCHED: 'on-device-matched',
  SET_SCANNER_TYPE: 'set-scanner-type',
  GET_SCANNER_TYPE: 'get-scanner-type',
  SAVE_DATABASE: 'save-database',
  SAVE_FILE: 'save-file',
};
