/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type RequisitionLineChartVariables = {
  storeId: string;
  lineId: string;
};

export type RequisitionLineChartResult = {
  requisitionLineChart: ({
  __typename: "ItemChartNode";
} & {
  consumptionHistory: {
  nodes: Array<{
  date: string;
  consumption: number;
  averageMonthlyConsumption: number;
  isHistoric: boolean;
  isCurrent: boolean;
}>;
} | null;
  stockEvolution: {
  nodes: Array<{
  date: string;
  stockOnHand: number;
  minimumStockOnHand: number;
  maximumStockOnHand: number;
  isHistoric: boolean;
  isProjected: boolean;
}>;
} | null;
}) | ({
  __typename: "RequisitionLineChartError";
} & {
  error: {
  __typename: "RecordNotFound";
  description: string;
};
});
};

export const RequisitionLineChart = {
  query: "query requisitionLineChart($storeId: String!, $lineId: String!) {\n  requisitionLineChart(storeId: $storeId, requestRequisitionLineId: $lineId) {\n    __typename\n    ... on ItemChartNode {\n      consumptionHistory {\n        nodes {\n          date\n          consumption\n          averageMonthlyConsumption\n          isHistoric\n          isCurrent\n        }\n      }\n      stockEvolution {\n        nodes {\n          date\n          stockOnHand\n          minimumStockOnHand\n          maximumStockOnHand\n          isHistoric\n          isProjected\n        }\n      }\n    }\n    ... on RequisitionLineChartError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<RequisitionLineChartResult, RequisitionLineChartVariables>;
