/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type InternalOrderMasterListsVariables = {
  storeId: string;
};

export type InternalOrderMasterListsResult = {
  masterLists: ({
  __typename: "MasterListConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const InternalOrderMasterLists = {
  query: "query internalOrderMasterLists($storeId: String!) {\n  masterLists(\n    storeId: $storeId\n    filter: {existsForStoreId: {equalTo: $storeId}, isProgram: false}\n  ) {\n    ... on MasterListConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<InternalOrderMasterListsResult, InternalOrderMasterListsVariables>;

export type AddInternalOrderFromMasterListVariables = {
  storeId: string;
  input: {
    requestRequisitionId: string;
    masterListId: string;
  };
};

export type AddInternalOrderFromMasterListResult = {
  addFromMasterList: ({
  __typename: "RequisitionLineConnector";
} & {
  totalCount: number;
}) | ({
  __typename: "AddFromMasterListError";
} & {
  error: {
  description: string;
};
});
};

export const AddInternalOrderFromMasterList = {
  query: "mutation addInternalOrderFromMasterList($storeId: String!, $input: AddFromMasterListInput!) {\n  addFromMasterList(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionLineConnector {\n      __typename\n      totalCount\n    }\n    ... on AddFromMasterListError {\n      error {\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<AddInternalOrderFromMasterListResult, AddInternalOrderFromMasterListVariables>;
