/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "./graphql";

export type GlobalTableConfigsVariables = {
  storeId: string;
};

export type GlobalTableConfigsResult = {
  preferences: {
  globalTableConfigs: unknown;
};
};

export const GlobalTableConfigs = {
  query: "query globalTableConfigs($storeId: String!) {\n  preferences(storeId: $storeId) {\n    globalTableConfigs\n  }\n}",
} as TypedDocument<GlobalTableConfigsResult, GlobalTableConfigsVariables>;

export type SaveGlobalTableConfigsVariables = {
  storeId: string;
  input: {
    allowTrackingOfStockByDonor?: boolean | null;
    authorisePurchaseOrder?: boolean | null;
    customTranslations?: unknown | null;
    customTranslationsV2?: unknown | null;
    genderOptions?: Array<"FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY"> | null;
    preventTransfersMonthsBeforeInitialisation?: number | null;
    showContactTracing?: boolean | null;
    syncRecordsDisplayThreshold?: number | null;
    warningForExcessRequest?: boolean | null;
    adjustForNumberOfDaysOutOfStock?: boolean | null;
    daysInMonth?: number | null;
    expiredStockPreventIssue?: boolean | null;
    expiredStockIssueThreshold?: number | null;
    itemMarginOverridesSupplierMargin?: boolean | null;
    transferStockToInternalCustomersAtCostPrice?: boolean | null;
    isGaps?: boolean | null;
    displayPopulationBasedForecasting?: boolean | null;
    globalTableConfigs?: unknown | null;
    backdating?: {
    shipmentsEnabled: boolean;
    inventoryAdjustmentsEnabled: boolean;
    maxDays: number;
  } | null;
    receivePaymentsFromPrescriptions?: boolean | null;
    globalLogo?: string | null;
    blindStocktake?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    manageVaccinesInDoses?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    manageVvmStatusForStock?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    orderInPacks?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    useProcurementFunctionality?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    sortByVvmStatusThenExpiry?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    useSimplifiedMobileUi?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    disableManualReturns?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    requisitionAutoFinalise?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    inboundShipmentAutoVerify?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    canCreateInternalOrderFromARequisition?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    selectDestinationStoreForAnInternalOrder?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    externalInboundShipmentLinesMustBeAuthorised?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    numberOfMonthsToCheckForConsumptionWhenCalculatingOutOfStockProducts?: Array<{
    storeId: string;
    value: number;
  }> | null;
    numberOfMonthsThresholdToShowLowStockAlertsForProducts?: Array<{
    storeId: string;
    value: number;
  }> | null;
    numberOfMonthsThresholdToShowOverStockAlertsForProducts?: Array<{
    storeId: string;
    value: number;
  }> | null;
    firstThresholdForExpiringItems?: Array<{
    storeId: string;
    value: number;
  }> | null;
    secondThresholdForExpiringItems?: Array<{
    storeId: string;
    value: number;
  }> | null;
    warnWhenMissingRecentStocktake?: Array<{
    storeId: string;
    value: {
    enabled: boolean;
    maxAge: number;
    minItems: number;
  };
  }> | null;
    storeCustomColour?: Array<{
    storeId: string;
    value: string;
  }> | null;
    invoiceStatusOptions?: Array<{
    storeId: string;
    value: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED">;
  }> | null;
    showIndicativePriceInRequisitions?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
    doNotPrintPlaceholderLineLabels?: Array<{
    storeId: string;
    value: boolean;
  }> | null;
  };
};

export type SaveGlobalTableConfigsResult = {
  centralServer: {
  preferences: {
  upsertPreferences: {
  ok: boolean;
};
};
};
};

export const SaveGlobalTableConfigs = {
  query: "mutation saveGlobalTableConfigs($storeId: String!, $input: UpsertPreferencesInput!) {\n  centralServer {\n    preferences {\n      upsertPreferences(storeId: $storeId, input: $input) {\n        ok\n      }\n    }\n  }\n}",
} as TypedDocument<SaveGlobalTableConfigsResult, SaveGlobalTableConfigsVariables>;
