ALTER TYPE key_type
ADD VALUE
IF NOT EXISTS 'SETTINGS_DISPLAY_CUSTOM_THEME';
ALTER TYPE key_type
ADD VALUE
IF NOT EXISTS 'SETTINGS_DISPLAY_CUSTOM_LOGO';
ALTER TYPE key_type
ADD VALUE
IF NOT EXISTS 'SETTINGS_DISPLAY_DEFAULT_LANGUAGE';