/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type AllocatePatientCodeNumberVariables = {
  storeId: string;
};

export type AllocatePatientCodeNumberResult = {
  allocatePatientNumber: {
  number: number;
};
};

export const AllocatePatientCodeNumber = {
  query: "mutation allocatePatientCodeNumber($storeId: String!) {\n  allocatePatientNumber(storeId: $storeId) {\n    number\n  }\n}",
} as TypedDocument<AllocatePatientCodeNumberResult, AllocatePatientCodeNumberVariables>;
