/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type AllocatePatientCodeNumberVariables = {
  storeId: string;
  numberName: string;
};

export type AllocatePatientCodeNumberResult = {
  allocateProgramNumber: ({
  __typename: "NumberNode";
} & {
  number: number;
});
};

export const AllocatePatientCodeNumber = {
  query: "mutation allocatePatientCodeNumber($storeId: String!, $numberName: String!) {\n  allocateProgramNumber(storeId: $storeId, input: {numberName: $numberName}) {\n    ... on NumberNode {\n      __typename\n      number\n    }\n  }\n}",
} as TypedDocument<AllocatePatientCodeNumberResult, AllocatePatientCodeNumberVariables>;
