server:
  port: 8000
  #   one of: Auto | Enabled | Disabled - Auto will enable discovery if the server is running in development mode
  # discovery: Auto
  # debug_no_access_control: true # enable this if you want to ignore API authorisation (dummy user will be used for all operations)
  # danger_allow_http: true # allow http in production mode
  cors_origins: [
      http://localhost:3003,
      https://demo-open.msupply.org,
      http://localhost:8000,
    ] # Used to set the allowed Origin in Cross Origin Request Security
  base_dir: "app_data"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
logging:
  #   one of: All | Console | File
  mode: File
  #   one of:  Off | Error | Warn | Info (default) | Debug | Trace
  level: Info
  directory: log
  filename: remote_server.log
  max_file_count: 10
  max_file_size: 1
