/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type ManagedPluginsVariables = Record<string, never>;

export type ManagedPluginsResult = {
  centralServer: {
  plugin: {
  installedPlugins: {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  version: string;
  kind: "BACKEND" | "FRONTEND";
  types: Array<string>;
  hostRuntime: string | null;
}>;
};
};
};
};

export const ManagedPlugins = {
  query: "query ManagedPlugins {\n  centralServer {\n    plugin {\n      installedPlugins {\n        totalCount\n        nodes {\n          id\n          code\n          version\n          kind\n          types\n          hostRuntime\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<ManagedPluginsResult, ManagedPluginsVariables>;

export type InstallUploadedPluginVariables = {
  fileId: string;
};

export type InstallUploadedPluginResult = {
  centralServer: {
  plugins: {
  installUploadedPlugin: {
  pluginInfo: unknown;
};
};
};
};

export const InstallUploadedPlugin = {
  query: "mutation InstallUploadedPlugin($fileId: String!) {\n  centralServer {\n    plugins {\n      installUploadedPlugin(fileId: $fileId) {\n        pluginInfo\n      }\n    }\n  }\n}",
} as TypedDocument<InstallUploadedPluginResult, InstallUploadedPluginVariables>;

export type UninstallPluginVariables = {
  id: string;
};

export type UninstallPluginResult = {
  centralServer: {
  plugins: {
  uninstallPlugin: {
  id: string;
  code: string;
  kind: "BACKEND" | "FRONTEND";
};
};
};
};

export const UninstallPlugin = {
  query: "mutation UninstallPlugin($id: String!) {\n  centralServer {\n    plugins {\n      uninstallPlugin(id: $id) {\n        id\n        code\n        kind\n      }\n    }\n  }\n}",
} as TypedDocument<UninstallPluginResult, UninstallPluginVariables>;
