/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type SyncMessageRowFragment = {
  id: string;
  fromStore: {
  id: string;
  storeName: string;
} | null;
  toStore: {
  id: string;
  storeName: string;
} | null;
  body: string;
  createdDatetime: string;
  status: "new" | "inProgress" | "processed" | "error";
  type: "requestFieldChange" | "supportUpload" | "other";
  errorMessage: string | null;
};

export type SyncMessageFileFragment = {
  id: string;
  fileName: string;
  status: "NEW" | "IN_PROGRESS" | "DONE" | "ERROR" | "PERMANENT_FAILURE";
  error: string | null;
};

export type SyncMessagesVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    toStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    fromStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    status?: {
    equalTo?: "new" | "inProgress" | "processed" | "error" | null;
    equalAny?: Array<"new" | "inProgress" | "processed" | "error"> | null;
    notEqualTo?: "new" | "inProgress" | "processed" | "error" | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "id" | "createdDatetime" | "status";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type SyncMessagesResult = {
  centralServer: {
  syncMessage: {
  syncMessages: ({
  totalCount: number;
  nodes: Array<SyncMessageRowFragment>;
});
};
};
};

export const SyncMessages = {
  query: "query SyncMessages($storeId: String!, $filter: SyncMessageFilterInput, $sort: [SyncMessageSortInput!], $page: PaginationInput) {\n  centralServer {\n    syncMessage {\n      syncMessages(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n        ... on SyncMessageConnector {\n          totalCount\n          nodes {\n            ...SyncMessageRow\n          }\n        }\n      }\n    }\n  }\n}\n\nfragment SyncMessageRow on SyncMessageNode {\n  id\n  fromStore {\n    id\n    storeName\n  }\n  toStore {\n    id\n    storeName\n  }\n  body\n  createdDatetime\n  status\n  type\n  errorMessage\n}",
} as TypedDocument<SyncMessagesResult, SyncMessagesVariables>;

export type SyncMessageFilesVariables = {
  storeId: string;
  id: string;
};

export type SyncMessageFilesResult = {
  centralServer: {
  syncMessage: {
  syncMessage: ({
  files: {
  totalCount: number;
  nodes: Array<SyncMessageFileFragment>;
} | null;
});
};
};
};

export const SyncMessageFiles = {
  query: "query SyncMessageFiles($storeId: String!, $id: String!) {\n  centralServer {\n    syncMessage {\n      syncMessage(storeId: $storeId, id: $id) {\n        ... on SyncMessageNode {\n          files {\n            totalCount\n            nodes {\n              ...SyncMessageFile\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nfragment SyncMessageFile on SyncFileReferenceNode {\n  id\n  fileName\n  status\n  error\n}",
} as TypedDocument<SyncMessageFilesResult, SyncMessageFilesVariables>;

export type InsertSyncMessageVariables = {
  storeId: string;
  input: {
    id: string;
    toStoreId?: string | null;
    body?: string | null;
    type: "SUPPORT_UPLOAD";
  };
};

export type InsertSyncMessageResult = {
  insertSyncMessage: ({
  id: string;
});
};

export const InsertSyncMessage = {
  query: "mutation InsertSyncMessage($storeId: String!, $input: InsertSyncMessageInput!) {\n  insertSyncMessage(storeId: $storeId, input: $input) {\n    ... on IdResponse {\n      id\n    }\n  }\n}",
} as TypedDocument<InsertSyncMessageResult, InsertSyncMessageVariables>;
