/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type InsertRnrFormVariables = {
  storeId: string;
  input: {
    id: string;
    supplierId: string;
    programId: string;
    periodId: string;
  };
};

export type InsertRnrFormResult = {
  insertRnrForm: ({
  id: string;
});
};

export const InsertRnrForm = {
  query: "mutation InsertRnrForm($storeId: String!, $input: InsertRnRFormInput!) {\n  insertRnrForm(storeId: $storeId, input: $input) {\n    ... on RnRFormNode {\n      id\n    }\n  }\n}",
} as TypedDocument<InsertRnrFormResult, InsertRnrFormVariables>;
