/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type OutstandingLineRowFragment = {
  id: string;
  purchaseOrder: {
  id: string;
  number: number;
  reference: string | null;
  confirmedDatetime: string | null;
  user: {
  username: string;
} | null;
  supplier: {
  code: string;
  name: string;
} | null;
} | null;
  item: {
  name: string;
};
  expectedDeliveryDate: string | null;
  adjustedNumberOfUnits: number | null;
  receivedNumberOfUnits: number;
  outstandingNumberOfUnits: number;
};

export type OutstandingLinesVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    purchaseOrderId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    status?: {
    equalTo?: "NEW" | "SENT" | "CLOSED" | null;
    equalAny?: Array<"NEW" | "SENT" | "CLOSED"> | null;
    notEqualTo?: "NEW" | "SENT" | "CLOSED" | null;
    notEqualAll?: Array<"NEW" | "SENT" | "CLOSED"> | null;
  } | null;
    receivedLessThanAdjusted?: boolean | null;
    supplierName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    purchaseOrderNumber?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    itemName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    expectedDeliveryDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "itemName" | "lineNumber" | "requestedDeliveryDate" | "expectedDeliveryDate" | "purchaseOrderNumber" | "supplierName" | "purchaseOrderConfirmedDatetime" | "adjustedNumberOfUnits" | "receivedNumberOfUnits" | "outstandingNumberOfUnits";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type OutstandingLinesResult = {
  purchaseOrderLines: ({
  __typename: "PurchaseOrderLineConnector";
} & {
  totalCount: number;
  nodes: Array<OutstandingLineRowFragment>;
});
};

export const OutstandingLines = {
  query: "query outstandingLines($storeId: String!, $filter: PurchaseOrderLineFilterInput, $sort: [PurchaseOrderLineSortInput!], $page: PaginationInput) {\n  purchaseOrderLines(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on PurchaseOrderLineConnector {\n      __typename\n      totalCount\n      nodes {\n        ...OutstandingLineRow\n      }\n    }\n  }\n}\n\nfragment OutstandingLineRow on PurchaseOrderLineNode {\n  id\n  purchaseOrder {\n    id\n    number\n    reference\n    confirmedDatetime\n    user {\n      username\n    }\n    supplier {\n      code\n      name\n    }\n  }\n  item {\n    name\n  }\n  expectedDeliveryDate\n  adjustedNumberOfUnits\n  receivedNumberOfUnits\n  outstandingNumberOfUnits\n}",
} as TypedDocument<OutstandingLinesResult, OutstandingLinesVariables>;
