/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type InternalOrderDetailContextVariables = {
  storeId: string;
};

export type InternalOrderDetailContextResult = {
  preferences: {
  selectDestinationStoreForAnInternalOrder: boolean;
  manageVaccinesInDoses: boolean;
  showIndicativePriceInRequisitions: boolean;
  displayPopulationBasedForecasting: boolean;
  warningForExcessRequest: boolean;
  canCreateInternalOrderFromARequisition: boolean;
};
  storePreferences: {
  requestRequisitionRequiresAuthorisation: boolean;
  useConsumptionAndStockFromCustomersForInternalOrders: boolean;
};
};

export const InternalOrderDetailContext = {
  query: "query internalOrderDetailContext($storeId: String!) {\n  preferences(storeId: $storeId) {\n    selectDestinationStoreForAnInternalOrder\n    manageVaccinesInDoses\n    showIndicativePriceInRequisitions\n    displayPopulationBasedForecasting\n    warningForExcessRequest\n    canCreateInternalOrderFromARequisition\n  }\n  storePreferences(storeId: $storeId) {\n    requestRequisitionRequiresAuthorisation\n    useConsumptionAndStockFromCustomersForInternalOrders\n  }\n}",
} as TypedDocument<InternalOrderDetailContextResult, InternalOrderDetailContextVariables>;
