/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type StoreOwnNameVariables = {
  storeId: string;
};

export type StoreOwnNameResult = {
  stores: ({
  nodes: Array<{
  id: string;
  name: {
  id: string;
};
}>;
});
};

export const StoreOwnName = {
  query: "query storeOwnName($storeId: String!) {\n  stores(filter: {id: {equalTo: $storeId}}) {\n    ... on StoreConnector {\n      nodes {\n        id\n        name(storeId: $storeId) {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<StoreOwnNameResult, StoreOwnNameVariables>;

export type InternalOrderIndicatorsVariables = {
  storeId: string;
  programId: string;
  periodId: string;
  customerNameId: string;
};

export type InternalOrderIndicatorsResult = {
  programIndicators: ({
  __typename: "ProgramIndicatorConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string | null;
  lineAndColumns: Array<{
  line: {
  id: string;
  code: string;
  name: string;
  lineNumber: number;
  valueType: "STRING" | "NUMBER" | null;
  isActive: boolean;
};
  columns: Array<{
  id: string;
  name: string;
  columnNumber: number;
  valueType: "STRING" | "NUMBER" | null;
  value: {
  id: string;
  value: string;
} | null;
}>;
  customerIndicatorInfo: Array<{
  id: string;
  customer: {
  id: string;
  name: string;
};
  datetime: string | null;
  indicatorInformation: Array<{
  columnId: string;
  value: string;
}>;
}>;
}>;
}>;
});
};

export const InternalOrderIndicators = {
  query: "query internalOrderIndicators($storeId: String!, $programId: String!, $periodId: String!, $customerNameId: String!) {\n  programIndicators(storeId: $storeId, filter: {programId: {equalTo: $programId}}) {\n    ... on ProgramIndicatorConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        code\n        lineAndColumns {\n          line {\n            id\n            code\n            name\n            lineNumber\n            valueType\n            isActive\n          }\n          columns {\n            id\n            name\n            columnNumber\n            valueType\n            value(periodId: $periodId, storeId: $storeId, customerNameId: $customerNameId) {\n              id\n              value\n            }\n          }\n          customerIndicatorInfo(periodId: $periodId, storeId: $storeId) {\n            id\n            customer(storeId: $storeId) {\n              id\n              name\n            }\n            datetime\n            indicatorInformation {\n              columnId\n              value\n            }\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<InternalOrderIndicatorsResult, InternalOrderIndicatorsVariables>;

export type UpdateIndicatorValueVariables = {
  storeId: string;
  input: {
    id: string;
    value: string;
  };
};

export type UpdateIndicatorValueResult = {
  updateIndicatorValue: ({
  __typename: "IndicatorValueNode";
} & {
  id: string;
  value: string;
}) | ({
  __typename: "UpdateIndicatorValueError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const UpdateIndicatorValue = {
  query: "mutation updateIndicatorValue($storeId: String!, $input: UpdateIndicatorValueInput!) {\n  updateIndicatorValue(storeId: $storeId, input: $input) {\n    __typename\n    ... on IndicatorValueNode {\n      id\n      value\n    }\n    ... on UpdateIndicatorValueError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<UpdateIndicatorValueResult, UpdateIndicatorValueVariables>;
