/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type StoreOwnNameVariables = {
  storeId: string;
};

export type StoreOwnNameResult = {
  stores: ({
  nodes: Array<{
  id: string;
  name: {
  id: string;
};
}>;
});
};

export const StoreOwnName = {
  query: "query storeOwnName($storeId: String!) {\n  stores(filter: {id: {equalTo: $storeId}}) {\n    ... on StoreConnector {\n      nodes {\n        id\n        name(storeId: $storeId) {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<StoreOwnNameResult, StoreOwnNameVariables>;
