/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type NewStockItemVariables = {
  storeId: string;
  itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
};

export type NewStockItemResult = {
  items: ({
  __typename: "ItemConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  unitName: string | null;
  isVaccine: boolean;
  doses: number;
  defaultPackSize: number;
  restrictedLocationTypeId: string | null;
  restrictedLocationType: {
  id: string;
  name: string;
} | null;
  itemStoreProperties: {
  defaultSellPricePerPack: number;
} | null;
  variants: Array<{
  id: string;
  name: string;
  manufacturerId: string | null;
  manufacturer: {
  id: string;
  name: string;
} | null;
  packagingVariants: Array<{
  id: string;
  packagingLevel: number;
  packSize: number | null;
  volumePerUnit: number | null;
}>;
}>;
}>;
});
};

export const NewStockItem = {
  query: "query newStockItem($storeId: String!, $itemId: EqualFilterStringInput) {\n  items(storeId: $storeId, filter: {id: $itemId}) {\n    ... on ItemConnector {\n      __typename\n      nodes {\n        id\n        code\n        name\n        unitName\n        isVaccine\n        doses\n        defaultPackSize\n        restrictedLocationTypeId\n        restrictedLocationType {\n          id\n          name\n        }\n        itemStoreProperties(storeId: $storeId) {\n          defaultSellPricePerPack\n        }\n        variants {\n          id\n          name\n          manufacturerId\n          manufacturer(storeId: $storeId) {\n            id\n            name\n          }\n          packagingVariants {\n            id\n            packagingLevel\n            packSize\n            volumePerUnit\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<NewStockItemResult, NewStockItemVariables>;

export type InsertStockLineVariables = {
  storeId: string;
  input: {
    id: string;
    itemId: string;
    numberOfPacks: number;
    costPricePerPack: number;
    sellPricePerPack: number;
    packSize: number;
    onHold: boolean;
    batch?: string | null;
    location?: {
    value?: string | null;
  } | null;
    expiryDate?: string | null;
    manufactureDate?: string | null;
    inventoryAdjustmentReasonId?: string | null;
    reasonOptionId?: string | null;
    barcode?: string | null;
    itemVariantId?: string | null;
    vvmStatusId?: string | null;
    donorId?: string | null;
    campaignId?: string | null;
    programId?: string | null;
    volumePerPack?: number | null;
    manufacturerId?: string | null;
  };
};

export type InsertStockLineResult = {
  insertStockLine: ({
  __typename: "StockLineNode";
} & {
  id: string;
}) | ({
  __typename: "InsertStockLineError";
} & {
  error: {
  __typename: "AdjustmentReasonNotProvided";
  description: string;
};
});
};

export const InsertStockLine = {
  query: "mutation insertStockLine($storeId: String!, $input: InsertStockLineInput!) {\n  insertStockLine(storeId: $storeId, input: $input) {\n    __typename\n    ... on StockLineNode {\n      id\n    }\n    ... on InsertStockLineError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertStockLineResult, InsertStockLineVariables>;
