/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type StockLineRowFragment = {
  id: string;
  itemId: string;
  itemName: string;
  batch: string | null;
  expiryDate: string | null;
  manufactureDate: string | null;
  packSize: number;
  totalNumberOfPacks: number;
  availableNumberOfPacks: number;
  costPricePerPack: number;
  sellPricePerPack: number;
  onHold: boolean;
  supplierName: string | null;
  locationName: string | null;
  volumePerPack: number;
  totalVolume: number;
  location: {
  id: string;
  code: string;
  name: string;
} | null;
  vvmStatus: {
  id: string;
  description: string;
} | null;
  item: {
  id: string;
  code: string;
  unitName: string | null;
  isVaccine: boolean;
  doses: number;
  masterLists: Array<{
  id: string;
  name: string;
}> | null;
};
  manufacturer: {
  id: string;
  name: string;
} | null;
};

export type StockLinesVariables = {
  storeId: string;
  filter?: {
    expiryDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isAvailable?: boolean | null;
    itemCodeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    search?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    vvmStatusId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    hasPacksInStore?: boolean | null;
    location?: {
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    onHold?: boolean | null;
    assignedToAsset?: boolean | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationTypeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
    masterList?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    description?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    existsForName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    existsForNameId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    existsForStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isProgram?: boolean | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
    isActive?: boolean | null;
    isProgramStockLine?: boolean | null;
    campaignId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "expiryDate" | "manufactureDate" | "numberOfPacks" | "itemCode" | "itemName" | "batch" | "packSize" | "supplierName" | "locationCode" | "costPricePerPack" | "sellPricePerPack" | "vvmStatusThenExpiry" | "campaign";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type StockLinesResult = {
  stockLines: ({
  __typename: "StockLineConnector";
} & {
  totalCount: number;
  nodes: Array<StockLineRowFragment>;
});
};

export const StockLines = {
  query: "query stockLines($storeId: String!, $filter: StockLineFilterInput, $sort: [StockLineSortInput!], $page: PaginationInput) {\n  stockLines(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on StockLineConnector {\n      __typename\n      totalCount\n      nodes {\n        ...StockLineRow\n      }\n    }\n  }\n}\n\nfragment StockLineRow on StockLineNode {\n  id\n  itemId\n  itemName\n  batch\n  expiryDate\n  manufactureDate\n  packSize\n  totalNumberOfPacks\n  availableNumberOfPacks\n  costPricePerPack\n  sellPricePerPack\n  onHold\n  supplierName\n  locationName\n  volumePerPack\n  totalVolume\n  location {\n    id\n    code\n    name\n  }\n  vvmStatus {\n    id\n    description\n  }\n  item {\n    id\n    code\n    unitName\n    isVaccine\n    doses\n    masterLists(storeId: $storeId) {\n      id\n      name\n    }\n  }\n  manufacturer(storeId: $storeId) {\n    id\n    name\n  }\n}",
} as TypedDocument<StockLinesResult, StockLinesVariables>;
