/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type ProgramEnrolmentRowFragment = {
  __typename: "ProgramEnrolmentNode";
  id: string;
  type: string;
  programEnrolmentId: string | null;
  status: string | null;
  enrolmentDatetime: string;
  isImmunisationProgram: boolean;
  document: {
  __typename: "DocumentNode";
  documentRegistry: {
  __typename: "DocumentRegistryNode";
  name: string | null;
} | null;
};
};

export type EncounterRowFragment = {
  __typename: "EncounterNode";
  id: string;
  type: string;
  startDatetime: string;
  status: "PENDING" | "VISITED" | "CANCELLED" | "DELETED" | null;
  document: {
  __typename: "DocumentNode";
  documentRegistry: {
  __typename: "DocumentRegistryNode";
  name: string | null;
} | null;
};
  programEnrolment: {
  __typename: "ProgramEnrolmentNode";
  document: {
  __typename: "DocumentNode";
  documentRegistry: {
  __typename: "DocumentRegistryNode";
  name: string | null;
} | null;
};
} | null;
};

export type PatientProgramEnrolmentsVariables = {
  storeId: string;
  filter?: {
    patientId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    enrolmentDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    programEnrolmentId?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    status?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    type?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    documentName?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isImmunisationProgram?: boolean | null;
  } | null;
  sort?: {
    key: "type" | "patientId" | "enrolmentDatetime" | "programEnrolmentId" | "status";
    desc?: boolean | null;
  } | null;
};

export type PatientProgramEnrolmentsResult = {
  programEnrolments: ({
  __typename: "ProgramEnrolmentConnector";
} & {
  totalCount: number;
  nodes: Array<ProgramEnrolmentRowFragment>;
});
};

export const PatientProgramEnrolments = {
  query: "query patientProgramEnrolments($storeId: String!, $filter: ProgramEnrolmentFilterInput, $sort: ProgramEnrolmentSortInput) {\n  programEnrolments(storeId: $storeId, filter: $filter, sort: $sort) {\n    ... on ProgramEnrolmentConnector {\n      __typename\n      totalCount\n      nodes {\n        ...ProgramEnrolmentRow\n      }\n    }\n  }\n}\n\nfragment ProgramEnrolmentRow on ProgramEnrolmentNode {\n  __typename\n  id\n  type\n  programEnrolmentId\n  status\n  enrolmentDatetime\n  isImmunisationProgram\n  document {\n    __typename\n    documentRegistry {\n      __typename\n      name\n    }\n  }\n}",
} as TypedDocument<PatientProgramEnrolmentsResult, PatientProgramEnrolmentsVariables>;

export type PatientEncountersVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    patientId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    startDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    endDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    status?: {
    equalTo?: "PENDING" | "VISITED" | "CANCELLED" | "DELETED" | null;
    equalAny?: Array<"PENDING" | "VISITED" | "CANCELLED" | "DELETED"> | null;
    notEqualTo?: "PENDING" | "VISITED" | "CANCELLED" | "DELETED" | null;
    notEqualAll?: Array<"PENDING" | "VISITED" | "CANCELLED" | "DELETED"> | null;
  } | null;
    clinicianId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    documentName?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    documentData?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    patient?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code2?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    firstName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    lastName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    gender?: {
    equalTo?: "FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY" | null;
    equalAny?: Array<"FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY"> | null;
    notEqualTo?: "FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY" | null;
    notEqualAll?: Array<"FEMALE" | "MALE" | "TRANSGENDER" | "TRANSGENDER_MALE" | "TRANSGENDER_MALE_HORMONE" | "TRANSGENDER_MALE_SURGICAL" | "TRANSGENDER_FEMALE" | "TRANSGENDER_FEMALE_HORMONE" | "TRANSGENDER_FEMALE_SURGICAL" | "UNKNOWN" | "NON_BINARY"> | null;
  } | null;
    dateOfBirth?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    phone?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    address1?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    address2?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    country?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    email?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    identifier?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    dateOfDeath?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    programEnrolmentName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    nextOfKinName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    dynamicFilter?: unknown | null;
  } | null;
    programEnrolment?: {
    patientId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    enrolmentDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    programEnrolmentId?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    status?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    type?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    documentName?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    programName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isImmunisationProgram?: boolean | null;
  } | null;
    includeDeleted?: boolean | null;
  } | null;
  sort?: {
    key: "Type" | "patientId" | "Program" | "createdDatetime" | "startDatetime" | "endDatetime" | "status";
    desc?: boolean | null;
  } | null;
};

export type PatientEncountersResult = {
  encounters: ({
  __typename: "EncounterConnector";
} & {
  totalCount: number;
  nodes: Array<EncounterRowFragment>;
});
};

export const PatientEncounters = {
  query: "query patientEncounters($storeId: String!, $filter: EncounterFilterInput, $sort: EncounterSortInput) {\n  encounters(storeId: $storeId, filter: $filter, sort: $sort) {\n    ... on EncounterConnector {\n      __typename\n      totalCount\n      nodes {\n        ...EncounterRow\n      }\n    }\n  }\n}\n\nfragment EncounterRow on EncounterNode {\n  __typename\n  id\n  type\n  startDatetime\n  status\n  document {\n    __typename\n    documentRegistry {\n      __typename\n      name\n    }\n  }\n  programEnrolment {\n    __typename\n    document {\n      __typename\n      documentRegistry {\n        __typename\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<PatientEncountersResult, PatientEncountersVariables>;
