/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type ReasonOptionsVariables = Record<string, never>;

export type ReasonOptionsResult = {
  reasonOptions: ({
  __typename: "ReasonOptionConnector";
  nodes: Array<{
  id: string;
  type: "POSITIVE_INVENTORY_ADJUSTMENT" | "NEGATIVE_INVENTORY_ADJUSTMENT" | "OPEN_VIAL_WASTAGE" | "RETURN_REASON" | "REQUISITION_LINE_VARIANCE" | "CLOSED_VIAL_WASTAGE" | "SHIPMENT_VARIANCE";
  reason: string;
}>;
});
};

export const ReasonOptions = {
  query: "query reasonOptions {\n  reasonOptions(filter: {isActive: true}) {\n    ... on ReasonOptionConnector {\n      __typename\n      nodes {\n        id\n        type\n        reason\n      }\n    }\n  }\n}",
} as TypedDocument<ReasonOptionsResult, ReasonOptionsVariables>;
