/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStoreIdRouteImport } from './routes/_authenticated/$storeId'
import { Route as AuthenticatedStoreIdIndexRouteImport } from './routes/_authenticated/$storeId/index'
import { Route as AuthenticatedStoreIdSettingsRouteImport } from './routes/_authenticated/$storeId/settings'
import { Route as AuthenticatedStoreIdReportsRouteImport } from './routes/_authenticated/$storeId/reports'
import { Route as AuthenticatedStoreIdStocktakeIndexRouteImport } from './routes/_authenticated/$storeId/stocktake/index'
import { Route as AuthenticatedStoreIdStockIndexRouteImport } from './routes/_authenticated/$storeId/stock/index'
import { Route as AuthenticatedStoreIdStocktakeStocktakeIdRouteImport } from './routes/_authenticated/$storeId/stocktake/$stocktakeId'
import { Route as AuthenticatedStoreIdStockStockLineIdRouteImport } from './routes/_authenticated/$storeId/stock/$stockLineId'
import { Route as AuthenticatedStoreIdManageStoresRouteImport } from './routes/_authenticated/$storeId/manage/stores'
import { Route as AuthenticatedStoreIdManageGlobalPreferencesRouteImport } from './routes/_authenticated/$storeId/manage/global-preferences'
import { Route as AuthenticatedStoreIdManageCampaignsRouteImport } from './routes/_authenticated/$storeId/manage/campaigns'
import { Route as AuthenticatedStoreIdInventoryLocationsRouteImport } from './routes/_authenticated/$storeId/inventory/locations'
import { Route as AuthenticatedStoreIdDispensaryPrescriptionRouteImport } from './routes/_authenticated/$storeId/dispensary/prescription'
import { Route as AuthenticatedStoreIdDispensaryPatientsRouteImport } from './routes/_authenticated/$storeId/dispensary/patients'
import { Route as AuthenticatedStoreIdDispensaryCliniciansRouteImport } from './routes/_authenticated/$storeId/dispensary/clinicians'
import { Route as AuthenticatedStoreIdColdChainSensorsRouteImport } from './routes/_authenticated/$storeId/cold-chain/sensors'
import { Route as AuthenticatedStoreIdColdChainMonitoringRouteImport } from './routes/_authenticated/$storeId/cold-chain/monitoring'
import { Route as AuthenticatedStoreIdColdChainEquipmentRouteImport } from './routes/_authenticated/$storeId/cold-chain/equipment'
import { Route as AuthenticatedStoreIdCatalogueMasterListsRouteImport } from './routes/_authenticated/$storeId/catalogue/master-lists'
import { Route as AuthenticatedStoreIdCatalogueItemsRouteImport } from './routes/_authenticated/$storeId/catalogue/items'
import { Route as AuthenticatedStoreIdCatalogueAssetsRouteImport } from './routes/_authenticated/$storeId/catalogue/assets'
import { Route as AuthenticatedStoreIdReplenishmentSuppliersIndexRouteImport } from './routes/_authenticated/$storeId/replenishment/suppliers/index'
import { Route as AuthenticatedStoreIdReplenishmentSupplierReturnIndexRouteImport } from './routes/_authenticated/$storeId/replenishment/supplier-return/index'
import { Route as AuthenticatedStoreIdReplenishmentInternalOrderIndexRouteImport } from './routes/_authenticated/$storeId/replenishment/internal-order/index'
import { Route as AuthenticatedStoreIdReplenishmentInboundShipmentIndexRouteImport } from './routes/_authenticated/$storeId/replenishment/inbound-shipment/index'
import { Route as AuthenticatedStoreIdDistributionOutboundShipmentIndexRouteImport } from './routes/_authenticated/$storeId/distribution/outbound-shipment/index'
import { Route as AuthenticatedStoreIdDistributionCustomersIndexRouteImport } from './routes/_authenticated/$storeId/distribution/customers/index'
import { Route as AuthenticatedStoreIdDistributionCustomerReturnIndexRouteImport } from './routes/_authenticated/$storeId/distribution/customer-return/index'
import { Route as AuthenticatedStoreIdDistributionCustomerRequisitionIndexRouteImport } from './routes/_authenticated/$storeId/distribution/customer-requisition/index'
import { Route as AuthenticatedStoreIdReplenishmentSuppliersNameIdRouteImport } from './routes/_authenticated/$storeId/replenishment/suppliers/$nameId'
import { Route as AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRouteImport } from './routes/_authenticated/$storeId/replenishment/supplier-return/$invoiceId'
import { Route as AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRouteImport } from './routes/_authenticated/$storeId/replenishment/internal-order/$requisitionId'
import { Route as AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRouteImport } from './routes/_authenticated/$storeId/replenishment/inbound-shipment/$invoiceId'
import { Route as AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRouteImport } from './routes/_authenticated/$storeId/distribution/outbound-shipment/$invoiceId'
import { Route as AuthenticatedStoreIdDistributionCustomersNameIdRouteImport } from './routes/_authenticated/$storeId/distribution/customers/$nameId'
import { Route as AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRouteImport } from './routes/_authenticated/$storeId/distribution/customer-return/$invoiceId'
import { Route as AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRouteImport } from './routes/_authenticated/$storeId/distribution/customer-requisition/$requisitionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreIdRoute = AuthenticatedStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreIdIndexRoute =
  AuthenticatedStoreIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsRoute =
  AuthenticatedStoreIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReportsRoute =
  AuthenticatedStoreIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdStocktakeIndexRoute =
  AuthenticatedStoreIdStocktakeIndexRouteImport.update({
    id: '/stocktake/',
    path: '/stocktake/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdStockIndexRoute =
  AuthenticatedStoreIdStockIndexRouteImport.update({
    id: '/stock/',
    path: '/stock/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdStocktakeStocktakeIdRoute =
  AuthenticatedStoreIdStocktakeStocktakeIdRouteImport.update({
    id: '/stocktake/$stocktakeId',
    path: '/stocktake/$stocktakeId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdStockStockLineIdRoute =
  AuthenticatedStoreIdStockStockLineIdRouteImport.update({
    id: '/stock/$stockLineId',
    path: '/stock/$stockLineId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdManageStoresRoute =
  AuthenticatedStoreIdManageStoresRouteImport.update({
    id: '/manage/stores',
    path: '/manage/stores',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdManageGlobalPreferencesRoute =
  AuthenticatedStoreIdManageGlobalPreferencesRouteImport.update({
    id: '/manage/global-preferences',
    path: '/manage/global-preferences',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdManageCampaignsRoute =
  AuthenticatedStoreIdManageCampaignsRouteImport.update({
    id: '/manage/campaigns',
    path: '/manage/campaigns',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdInventoryLocationsRoute =
  AuthenticatedStoreIdInventoryLocationsRouteImport.update({
    id: '/inventory/locations',
    path: '/inventory/locations',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDispensaryPrescriptionRoute =
  AuthenticatedStoreIdDispensaryPrescriptionRouteImport.update({
    id: '/dispensary/prescription',
    path: '/dispensary/prescription',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDispensaryPatientsRoute =
  AuthenticatedStoreIdDispensaryPatientsRouteImport.update({
    id: '/dispensary/patients',
    path: '/dispensary/patients',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDispensaryCliniciansRoute =
  AuthenticatedStoreIdDispensaryCliniciansRouteImport.update({
    id: '/dispensary/clinicians',
    path: '/dispensary/clinicians',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdColdChainSensorsRoute =
  AuthenticatedStoreIdColdChainSensorsRouteImport.update({
    id: '/cold-chain/sensors',
    path: '/cold-chain/sensors',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdColdChainMonitoringRoute =
  AuthenticatedStoreIdColdChainMonitoringRouteImport.update({
    id: '/cold-chain/monitoring',
    path: '/cold-chain/monitoring',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdColdChainEquipmentRoute =
  AuthenticatedStoreIdColdChainEquipmentRouteImport.update({
    id: '/cold-chain/equipment',
    path: '/cold-chain/equipment',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCatalogueMasterListsRoute =
  AuthenticatedStoreIdCatalogueMasterListsRouteImport.update({
    id: '/catalogue/master-lists',
    path: '/catalogue/master-lists',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCatalogueItemsRoute =
  AuthenticatedStoreIdCatalogueItemsRouteImport.update({
    id: '/catalogue/items',
    path: '/catalogue/items',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCatalogueAssetsRoute =
  AuthenticatedStoreIdCatalogueAssetsRouteImport.update({
    id: '/catalogue/assets',
    path: '/catalogue/assets',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentSuppliersIndexRoute =
  AuthenticatedStoreIdReplenishmentSuppliersIndexRouteImport.update({
    id: '/replenishment/suppliers/',
    path: '/replenishment/suppliers/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute =
  AuthenticatedStoreIdReplenishmentSupplierReturnIndexRouteImport.update({
    id: '/replenishment/supplier-return/',
    path: '/replenishment/supplier-return/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute =
  AuthenticatedStoreIdReplenishmentInternalOrderIndexRouteImport.update({
    id: '/replenishment/internal-order/',
    path: '/replenishment/internal-order/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute =
  AuthenticatedStoreIdReplenishmentInboundShipmentIndexRouteImport.update({
    id: '/replenishment/inbound-shipment/',
    path: '/replenishment/inbound-shipment/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute =
  AuthenticatedStoreIdDistributionOutboundShipmentIndexRouteImport.update({
    id: '/distribution/outbound-shipment/',
    path: '/distribution/outbound-shipment/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomersIndexRoute =
  AuthenticatedStoreIdDistributionCustomersIndexRouteImport.update({
    id: '/distribution/customers/',
    path: '/distribution/customers/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomerReturnIndexRoute =
  AuthenticatedStoreIdDistributionCustomerReturnIndexRouteImport.update({
    id: '/distribution/customer-return/',
    path: '/distribution/customer-return/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute =
  AuthenticatedStoreIdDistributionCustomerRequisitionIndexRouteImport.update({
    id: '/distribution/customer-requisition/',
    path: '/distribution/customer-requisition/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute =
  AuthenticatedStoreIdReplenishmentSuppliersNameIdRouteImport.update({
    id: '/replenishment/suppliers/$nameId',
    path: '/replenishment/suppliers/$nameId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute =
  AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRouteImport.update({
    id: '/replenishment/supplier-return/$invoiceId',
    path: '/replenishment/supplier-return/$invoiceId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute =
  AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRouteImport.update(
    {
      id: '/replenishment/internal-order/$requisitionId',
      path: '/replenishment/internal-order/$requisitionId',
      getParentRoute: () => AuthenticatedStoreIdRoute,
    } as any,
  )
const AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute =
  AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRouteImport.update({
    id: '/replenishment/inbound-shipment/$invoiceId',
    path: '/replenishment/inbound-shipment/$invoiceId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute =
  AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRouteImport.update({
    id: '/distribution/outbound-shipment/$invoiceId',
    path: '/distribution/outbound-shipment/$invoiceId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomersNameIdRoute =
  AuthenticatedStoreIdDistributionCustomersNameIdRouteImport.update({
    id: '/distribution/customers/$nameId',
    path: '/distribution/customers/$nameId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute =
  AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRouteImport.update({
    id: '/distribution/customer-return/$invoiceId',
    path: '/distribution/customer-return/$invoiceId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute =
  AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRouteImport.update(
    {
      id: '/distribution/customer-requisition/$requisitionId',
      path: '/distribution/customer-requisition/$requisitionId',
      getParentRoute: () => AuthenticatedStoreIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/$storeId/reports': typeof AuthenticatedStoreIdReportsRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/catalogue/assets': typeof AuthenticatedStoreIdCatalogueAssetsRoute
  '/$storeId/catalogue/items': typeof AuthenticatedStoreIdCatalogueItemsRoute
  '/$storeId/catalogue/master-lists': typeof AuthenticatedStoreIdCatalogueMasterListsRoute
  '/$storeId/cold-chain/equipment': typeof AuthenticatedStoreIdColdChainEquipmentRoute
  '/$storeId/cold-chain/monitoring': typeof AuthenticatedStoreIdColdChainMonitoringRoute
  '/$storeId/cold-chain/sensors': typeof AuthenticatedStoreIdColdChainSensorsRoute
  '/$storeId/dispensary/clinicians': typeof AuthenticatedStoreIdDispensaryCliniciansRoute
  '/$storeId/dispensary/patients': typeof AuthenticatedStoreIdDispensaryPatientsRoute
  '/$storeId/dispensary/prescription': typeof AuthenticatedStoreIdDispensaryPrescriptionRoute
  '/$storeId/inventory/locations': typeof AuthenticatedStoreIdInventoryLocationsRoute
  '/$storeId/manage/campaigns': typeof AuthenticatedStoreIdManageCampaignsRoute
  '/$storeId/manage/global-preferences': typeof AuthenticatedStoreIdManageGlobalPreferencesRoute
  '/$storeId/manage/stores': typeof AuthenticatedStoreIdManageStoresRoute
  '/$storeId/stock/$stockLineId': typeof AuthenticatedStoreIdStockStockLineIdRoute
  '/$storeId/stocktake/$stocktakeId': typeof AuthenticatedStoreIdStocktakeStocktakeIdRoute
  '/$storeId/stock/': typeof AuthenticatedStoreIdStockIndexRoute
  '/$storeId/stocktake/': typeof AuthenticatedStoreIdStocktakeIndexRoute
  '/$storeId/distribution/customer-requisition/$requisitionId': typeof AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute
  '/$storeId/distribution/customer-return/$invoiceId': typeof AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute
  '/$storeId/distribution/customers/$nameId': typeof AuthenticatedStoreIdDistributionCustomersNameIdRoute
  '/$storeId/distribution/outbound-shipment/$invoiceId': typeof AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute
  '/$storeId/replenishment/inbound-shipment/$invoiceId': typeof AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute
  '/$storeId/replenishment/internal-order/$requisitionId': typeof AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute
  '/$storeId/replenishment/supplier-return/$invoiceId': typeof AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute
  '/$storeId/replenishment/suppliers/$nameId': typeof AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute
  '/$storeId/distribution/customer-requisition/': typeof AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute
  '/$storeId/distribution/customer-return/': typeof AuthenticatedStoreIdDistributionCustomerReturnIndexRoute
  '/$storeId/distribution/customers/': typeof AuthenticatedStoreIdDistributionCustomersIndexRoute
  '/$storeId/distribution/outbound-shipment/': typeof AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute
  '/$storeId/replenishment/inbound-shipment/': typeof AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute
  '/$storeId/replenishment/internal-order/': typeof AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute
  '/$storeId/replenishment/supplier-return/': typeof AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute
  '/$storeId/replenishment/suppliers/': typeof AuthenticatedStoreIdReplenishmentSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/$storeId/reports': typeof AuthenticatedStoreIdReportsRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/$storeId': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/catalogue/assets': typeof AuthenticatedStoreIdCatalogueAssetsRoute
  '/$storeId/catalogue/items': typeof AuthenticatedStoreIdCatalogueItemsRoute
  '/$storeId/catalogue/master-lists': typeof AuthenticatedStoreIdCatalogueMasterListsRoute
  '/$storeId/cold-chain/equipment': typeof AuthenticatedStoreIdColdChainEquipmentRoute
  '/$storeId/cold-chain/monitoring': typeof AuthenticatedStoreIdColdChainMonitoringRoute
  '/$storeId/cold-chain/sensors': typeof AuthenticatedStoreIdColdChainSensorsRoute
  '/$storeId/dispensary/clinicians': typeof AuthenticatedStoreIdDispensaryCliniciansRoute
  '/$storeId/dispensary/patients': typeof AuthenticatedStoreIdDispensaryPatientsRoute
  '/$storeId/dispensary/prescription': typeof AuthenticatedStoreIdDispensaryPrescriptionRoute
  '/$storeId/inventory/locations': typeof AuthenticatedStoreIdInventoryLocationsRoute
  '/$storeId/manage/campaigns': typeof AuthenticatedStoreIdManageCampaignsRoute
  '/$storeId/manage/global-preferences': typeof AuthenticatedStoreIdManageGlobalPreferencesRoute
  '/$storeId/manage/stores': typeof AuthenticatedStoreIdManageStoresRoute
  '/$storeId/stock/$stockLineId': typeof AuthenticatedStoreIdStockStockLineIdRoute
  '/$storeId/stocktake/$stocktakeId': typeof AuthenticatedStoreIdStocktakeStocktakeIdRoute
  '/$storeId/stock': typeof AuthenticatedStoreIdStockIndexRoute
  '/$storeId/stocktake': typeof AuthenticatedStoreIdStocktakeIndexRoute
  '/$storeId/distribution/customer-requisition/$requisitionId': typeof AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute
  '/$storeId/distribution/customer-return/$invoiceId': typeof AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute
  '/$storeId/distribution/customers/$nameId': typeof AuthenticatedStoreIdDistributionCustomersNameIdRoute
  '/$storeId/distribution/outbound-shipment/$invoiceId': typeof AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute
  '/$storeId/replenishment/inbound-shipment/$invoiceId': typeof AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute
  '/$storeId/replenishment/internal-order/$requisitionId': typeof AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute
  '/$storeId/replenishment/supplier-return/$invoiceId': typeof AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute
  '/$storeId/replenishment/suppliers/$nameId': typeof AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute
  '/$storeId/distribution/customer-requisition': typeof AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute
  '/$storeId/distribution/customer-return': typeof AuthenticatedStoreIdDistributionCustomerReturnIndexRoute
  '/$storeId/distribution/customers': typeof AuthenticatedStoreIdDistributionCustomersIndexRoute
  '/$storeId/distribution/outbound-shipment': typeof AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute
  '/$storeId/replenishment/inbound-shipment': typeof AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute
  '/$storeId/replenishment/internal-order': typeof AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute
  '/$storeId/replenishment/supplier-return': typeof AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute
  '/$storeId/replenishment/suppliers': typeof AuthenticatedStoreIdReplenishmentSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$storeId/reports': typeof AuthenticatedStoreIdReportsRoute
  '/_authenticated/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/_authenticated/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/_authenticated/$storeId/catalogue/assets': typeof AuthenticatedStoreIdCatalogueAssetsRoute
  '/_authenticated/$storeId/catalogue/items': typeof AuthenticatedStoreIdCatalogueItemsRoute
  '/_authenticated/$storeId/catalogue/master-lists': typeof AuthenticatedStoreIdCatalogueMasterListsRoute
  '/_authenticated/$storeId/cold-chain/equipment': typeof AuthenticatedStoreIdColdChainEquipmentRoute
  '/_authenticated/$storeId/cold-chain/monitoring': typeof AuthenticatedStoreIdColdChainMonitoringRoute
  '/_authenticated/$storeId/cold-chain/sensors': typeof AuthenticatedStoreIdColdChainSensorsRoute
  '/_authenticated/$storeId/dispensary/clinicians': typeof AuthenticatedStoreIdDispensaryCliniciansRoute
  '/_authenticated/$storeId/dispensary/patients': typeof AuthenticatedStoreIdDispensaryPatientsRoute
  '/_authenticated/$storeId/dispensary/prescription': typeof AuthenticatedStoreIdDispensaryPrescriptionRoute
  '/_authenticated/$storeId/inventory/locations': typeof AuthenticatedStoreIdInventoryLocationsRoute
  '/_authenticated/$storeId/manage/campaigns': typeof AuthenticatedStoreIdManageCampaignsRoute
  '/_authenticated/$storeId/manage/global-preferences': typeof AuthenticatedStoreIdManageGlobalPreferencesRoute
  '/_authenticated/$storeId/manage/stores': typeof AuthenticatedStoreIdManageStoresRoute
  '/_authenticated/$storeId/stock/$stockLineId': typeof AuthenticatedStoreIdStockStockLineIdRoute
  '/_authenticated/$storeId/stocktake/$stocktakeId': typeof AuthenticatedStoreIdStocktakeStocktakeIdRoute
  '/_authenticated/$storeId/stock/': typeof AuthenticatedStoreIdStockIndexRoute
  '/_authenticated/$storeId/stocktake/': typeof AuthenticatedStoreIdStocktakeIndexRoute
  '/_authenticated/$storeId/distribution/customer-requisition/$requisitionId': typeof AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute
  '/_authenticated/$storeId/distribution/customer-return/$invoiceId': typeof AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute
  '/_authenticated/$storeId/distribution/customers/$nameId': typeof AuthenticatedStoreIdDistributionCustomersNameIdRoute
  '/_authenticated/$storeId/distribution/outbound-shipment/$invoiceId': typeof AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute
  '/_authenticated/$storeId/replenishment/inbound-shipment/$invoiceId': typeof AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute
  '/_authenticated/$storeId/replenishment/internal-order/$requisitionId': typeof AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute
  '/_authenticated/$storeId/replenishment/supplier-return/$invoiceId': typeof AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute
  '/_authenticated/$storeId/replenishment/suppliers/$nameId': typeof AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute
  '/_authenticated/$storeId/distribution/customer-requisition/': typeof AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute
  '/_authenticated/$storeId/distribution/customer-return/': typeof AuthenticatedStoreIdDistributionCustomerReturnIndexRoute
  '/_authenticated/$storeId/distribution/customers/': typeof AuthenticatedStoreIdDistributionCustomersIndexRoute
  '/_authenticated/$storeId/distribution/outbound-shipment/': typeof AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute
  '/_authenticated/$storeId/replenishment/inbound-shipment/': typeof AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute
  '/_authenticated/$storeId/replenishment/internal-order/': typeof AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute
  '/_authenticated/$storeId/replenishment/supplier-return/': typeof AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute
  '/_authenticated/$storeId/replenishment/suppliers/': typeof AuthenticatedStoreIdReplenishmentSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$storeId'
    | '/$storeId/reports'
    | '/$storeId/settings'
    | '/$storeId/'
    | '/$storeId/catalogue/assets'
    | '/$storeId/catalogue/items'
    | '/$storeId/catalogue/master-lists'
    | '/$storeId/cold-chain/equipment'
    | '/$storeId/cold-chain/monitoring'
    | '/$storeId/cold-chain/sensors'
    | '/$storeId/dispensary/clinicians'
    | '/$storeId/dispensary/patients'
    | '/$storeId/dispensary/prescription'
    | '/$storeId/inventory/locations'
    | '/$storeId/manage/campaigns'
    | '/$storeId/manage/global-preferences'
    | '/$storeId/manage/stores'
    | '/$storeId/stock/$stockLineId'
    | '/$storeId/stocktake/$stocktakeId'
    | '/$storeId/stock/'
    | '/$storeId/stocktake/'
    | '/$storeId/distribution/customer-requisition/$requisitionId'
    | '/$storeId/distribution/customer-return/$invoiceId'
    | '/$storeId/distribution/customers/$nameId'
    | '/$storeId/distribution/outbound-shipment/$invoiceId'
    | '/$storeId/replenishment/inbound-shipment/$invoiceId'
    | '/$storeId/replenishment/internal-order/$requisitionId'
    | '/$storeId/replenishment/supplier-return/$invoiceId'
    | '/$storeId/replenishment/suppliers/$nameId'
    | '/$storeId/distribution/customer-requisition/'
    | '/$storeId/distribution/customer-return/'
    | '/$storeId/distribution/customers/'
    | '/$storeId/distribution/outbound-shipment/'
    | '/$storeId/replenishment/inbound-shipment/'
    | '/$storeId/replenishment/internal-order/'
    | '/$storeId/replenishment/supplier-return/'
    | '/$storeId/replenishment/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/$storeId/reports'
    | '/$storeId/settings'
    | '/$storeId'
    | '/$storeId/catalogue/assets'
    | '/$storeId/catalogue/items'
    | '/$storeId/catalogue/master-lists'
    | '/$storeId/cold-chain/equipment'
    | '/$storeId/cold-chain/monitoring'
    | '/$storeId/cold-chain/sensors'
    | '/$storeId/dispensary/clinicians'
    | '/$storeId/dispensary/patients'
    | '/$storeId/dispensary/prescription'
    | '/$storeId/inventory/locations'
    | '/$storeId/manage/campaigns'
    | '/$storeId/manage/global-preferences'
    | '/$storeId/manage/stores'
    | '/$storeId/stock/$stockLineId'
    | '/$storeId/stocktake/$stocktakeId'
    | '/$storeId/stock'
    | '/$storeId/stocktake'
    | '/$storeId/distribution/customer-requisition/$requisitionId'
    | '/$storeId/distribution/customer-return/$invoiceId'
    | '/$storeId/distribution/customers/$nameId'
    | '/$storeId/distribution/outbound-shipment/$invoiceId'
    | '/$storeId/replenishment/inbound-shipment/$invoiceId'
    | '/$storeId/replenishment/internal-order/$requisitionId'
    | '/$storeId/replenishment/supplier-return/$invoiceId'
    | '/$storeId/replenishment/suppliers/$nameId'
    | '/$storeId/distribution/customer-requisition'
    | '/$storeId/distribution/customer-return'
    | '/$storeId/distribution/customers'
    | '/$storeId/distribution/outbound-shipment'
    | '/$storeId/replenishment/inbound-shipment'
    | '/$storeId/replenishment/internal-order'
    | '/$storeId/replenishment/supplier-return'
    | '/$storeId/replenishment/suppliers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$storeId'
    | '/_authenticated/'
    | '/_authenticated/$storeId/reports'
    | '/_authenticated/$storeId/settings'
    | '/_authenticated/$storeId/'
    | '/_authenticated/$storeId/catalogue/assets'
    | '/_authenticated/$storeId/catalogue/items'
    | '/_authenticated/$storeId/catalogue/master-lists'
    | '/_authenticated/$storeId/cold-chain/equipment'
    | '/_authenticated/$storeId/cold-chain/monitoring'
    | '/_authenticated/$storeId/cold-chain/sensors'
    | '/_authenticated/$storeId/dispensary/clinicians'
    | '/_authenticated/$storeId/dispensary/patients'
    | '/_authenticated/$storeId/dispensary/prescription'
    | '/_authenticated/$storeId/inventory/locations'
    | '/_authenticated/$storeId/manage/campaigns'
    | '/_authenticated/$storeId/manage/global-preferences'
    | '/_authenticated/$storeId/manage/stores'
    | '/_authenticated/$storeId/stock/$stockLineId'
    | '/_authenticated/$storeId/stocktake/$stocktakeId'
    | '/_authenticated/$storeId/stock/'
    | '/_authenticated/$storeId/stocktake/'
    | '/_authenticated/$storeId/distribution/customer-requisition/$requisitionId'
    | '/_authenticated/$storeId/distribution/customer-return/$invoiceId'
    | '/_authenticated/$storeId/distribution/customers/$nameId'
    | '/_authenticated/$storeId/distribution/outbound-shipment/$invoiceId'
    | '/_authenticated/$storeId/replenishment/inbound-shipment/$invoiceId'
    | '/_authenticated/$storeId/replenishment/internal-order/$requisitionId'
    | '/_authenticated/$storeId/replenishment/supplier-return/$invoiceId'
    | '/_authenticated/$storeId/replenishment/suppliers/$nameId'
    | '/_authenticated/$storeId/distribution/customer-requisition/'
    | '/_authenticated/$storeId/distribution/customer-return/'
    | '/_authenticated/$storeId/distribution/customers/'
    | '/_authenticated/$storeId/distribution/outbound-shipment/'
    | '/_authenticated/$storeId/replenishment/inbound-shipment/'
    | '/_authenticated/$storeId/replenishment/internal-order/'
    | '/_authenticated/$storeId/replenishment/supplier-return/'
    | '/_authenticated/$storeId/replenishment/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$storeId': {
      id: '/_authenticated/$storeId'
      path: '/$storeId'
      fullPath: '/$storeId'
      preLoaderRoute: typeof AuthenticatedStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$storeId/': {
      id: '/_authenticated/$storeId/'
      path: '/'
      fullPath: '/$storeId/'
      preLoaderRoute: typeof AuthenticatedStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings': {
      id: '/_authenticated/$storeId/settings'
      path: '/settings'
      fullPath: '/$storeId/settings'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/reports': {
      id: '/_authenticated/$storeId/reports'
      path: '/reports'
      fullPath: '/$storeId/reports'
      preLoaderRoute: typeof AuthenticatedStoreIdReportsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/stocktake/': {
      id: '/_authenticated/$storeId/stocktake/'
      path: '/stocktake'
      fullPath: '/$storeId/stocktake/'
      preLoaderRoute: typeof AuthenticatedStoreIdStocktakeIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/stock/': {
      id: '/_authenticated/$storeId/stock/'
      path: '/stock'
      fullPath: '/$storeId/stock/'
      preLoaderRoute: typeof AuthenticatedStoreIdStockIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/stocktake/$stocktakeId': {
      id: '/_authenticated/$storeId/stocktake/$stocktakeId'
      path: '/stocktake/$stocktakeId'
      fullPath: '/$storeId/stocktake/$stocktakeId'
      preLoaderRoute: typeof AuthenticatedStoreIdStocktakeStocktakeIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/stock/$stockLineId': {
      id: '/_authenticated/$storeId/stock/$stockLineId'
      path: '/stock/$stockLineId'
      fullPath: '/$storeId/stock/$stockLineId'
      preLoaderRoute: typeof AuthenticatedStoreIdStockStockLineIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/manage/stores': {
      id: '/_authenticated/$storeId/manage/stores'
      path: '/manage/stores'
      fullPath: '/$storeId/manage/stores'
      preLoaderRoute: typeof AuthenticatedStoreIdManageStoresRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/manage/global-preferences': {
      id: '/_authenticated/$storeId/manage/global-preferences'
      path: '/manage/global-preferences'
      fullPath: '/$storeId/manage/global-preferences'
      preLoaderRoute: typeof AuthenticatedStoreIdManageGlobalPreferencesRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/manage/campaigns': {
      id: '/_authenticated/$storeId/manage/campaigns'
      path: '/manage/campaigns'
      fullPath: '/$storeId/manage/campaigns'
      preLoaderRoute: typeof AuthenticatedStoreIdManageCampaignsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/inventory/locations': {
      id: '/_authenticated/$storeId/inventory/locations'
      path: '/inventory/locations'
      fullPath: '/$storeId/inventory/locations'
      preLoaderRoute: typeof AuthenticatedStoreIdInventoryLocationsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/dispensary/prescription': {
      id: '/_authenticated/$storeId/dispensary/prescription'
      path: '/dispensary/prescription'
      fullPath: '/$storeId/dispensary/prescription'
      preLoaderRoute: typeof AuthenticatedStoreIdDispensaryPrescriptionRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/dispensary/patients': {
      id: '/_authenticated/$storeId/dispensary/patients'
      path: '/dispensary/patients'
      fullPath: '/$storeId/dispensary/patients'
      preLoaderRoute: typeof AuthenticatedStoreIdDispensaryPatientsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/dispensary/clinicians': {
      id: '/_authenticated/$storeId/dispensary/clinicians'
      path: '/dispensary/clinicians'
      fullPath: '/$storeId/dispensary/clinicians'
      preLoaderRoute: typeof AuthenticatedStoreIdDispensaryCliniciansRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/cold-chain/sensors': {
      id: '/_authenticated/$storeId/cold-chain/sensors'
      path: '/cold-chain/sensors'
      fullPath: '/$storeId/cold-chain/sensors'
      preLoaderRoute: typeof AuthenticatedStoreIdColdChainSensorsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/cold-chain/monitoring': {
      id: '/_authenticated/$storeId/cold-chain/monitoring'
      path: '/cold-chain/monitoring'
      fullPath: '/$storeId/cold-chain/monitoring'
      preLoaderRoute: typeof AuthenticatedStoreIdColdChainMonitoringRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/cold-chain/equipment': {
      id: '/_authenticated/$storeId/cold-chain/equipment'
      path: '/cold-chain/equipment'
      fullPath: '/$storeId/cold-chain/equipment'
      preLoaderRoute: typeof AuthenticatedStoreIdColdChainEquipmentRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/catalogue/master-lists': {
      id: '/_authenticated/$storeId/catalogue/master-lists'
      path: '/catalogue/master-lists'
      fullPath: '/$storeId/catalogue/master-lists'
      preLoaderRoute: typeof AuthenticatedStoreIdCatalogueMasterListsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/catalogue/items': {
      id: '/_authenticated/$storeId/catalogue/items'
      path: '/catalogue/items'
      fullPath: '/$storeId/catalogue/items'
      preLoaderRoute: typeof AuthenticatedStoreIdCatalogueItemsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/catalogue/assets': {
      id: '/_authenticated/$storeId/catalogue/assets'
      path: '/catalogue/assets'
      fullPath: '/$storeId/catalogue/assets'
      preLoaderRoute: typeof AuthenticatedStoreIdCatalogueAssetsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/suppliers/': {
      id: '/_authenticated/$storeId/replenishment/suppliers/'
      path: '/replenishment/suppliers'
      fullPath: '/$storeId/replenishment/suppliers/'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/supplier-return/': {
      id: '/_authenticated/$storeId/replenishment/supplier-return/'
      path: '/replenishment/supplier-return'
      fullPath: '/$storeId/replenishment/supplier-return/'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentSupplierReturnIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/internal-order/': {
      id: '/_authenticated/$storeId/replenishment/internal-order/'
      path: '/replenishment/internal-order'
      fullPath: '/$storeId/replenishment/internal-order/'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentInternalOrderIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/inbound-shipment/': {
      id: '/_authenticated/$storeId/replenishment/inbound-shipment/'
      path: '/replenishment/inbound-shipment'
      fullPath: '/$storeId/replenishment/inbound-shipment/'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentInboundShipmentIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/outbound-shipment/': {
      id: '/_authenticated/$storeId/distribution/outbound-shipment/'
      path: '/distribution/outbound-shipment'
      fullPath: '/$storeId/distribution/outbound-shipment/'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionOutboundShipmentIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customers/': {
      id: '/_authenticated/$storeId/distribution/customers/'
      path: '/distribution/customers'
      fullPath: '/$storeId/distribution/customers/'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customer-return/': {
      id: '/_authenticated/$storeId/distribution/customer-return/'
      path: '/distribution/customer-return'
      fullPath: '/$storeId/distribution/customer-return/'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomerReturnIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customer-requisition/': {
      id: '/_authenticated/$storeId/distribution/customer-requisition/'
      path: '/distribution/customer-requisition'
      fullPath: '/$storeId/distribution/customer-requisition/'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomerRequisitionIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/suppliers/$nameId': {
      id: '/_authenticated/$storeId/replenishment/suppliers/$nameId'
      path: '/replenishment/suppliers/$nameId'
      fullPath: '/$storeId/replenishment/suppliers/$nameId'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentSuppliersNameIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/supplier-return/$invoiceId': {
      id: '/_authenticated/$storeId/replenishment/supplier-return/$invoiceId'
      path: '/replenishment/supplier-return/$invoiceId'
      fullPath: '/$storeId/replenishment/supplier-return/$invoiceId'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/internal-order/$requisitionId': {
      id: '/_authenticated/$storeId/replenishment/internal-order/$requisitionId'
      path: '/replenishment/internal-order/$requisitionId'
      fullPath: '/$storeId/replenishment/internal-order/$requisitionId'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/replenishment/inbound-shipment/$invoiceId': {
      id: '/_authenticated/$storeId/replenishment/inbound-shipment/$invoiceId'
      path: '/replenishment/inbound-shipment/$invoiceId'
      fullPath: '/$storeId/replenishment/inbound-shipment/$invoiceId'
      preLoaderRoute: typeof AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/outbound-shipment/$invoiceId': {
      id: '/_authenticated/$storeId/distribution/outbound-shipment/$invoiceId'
      path: '/distribution/outbound-shipment/$invoiceId'
      fullPath: '/$storeId/distribution/outbound-shipment/$invoiceId'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customers/$nameId': {
      id: '/_authenticated/$storeId/distribution/customers/$nameId'
      path: '/distribution/customers/$nameId'
      fullPath: '/$storeId/distribution/customers/$nameId'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomersNameIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customer-return/$invoiceId': {
      id: '/_authenticated/$storeId/distribution/customer-return/$invoiceId'
      path: '/distribution/customer-return/$invoiceId'
      fullPath: '/$storeId/distribution/customer-return/$invoiceId'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/distribution/customer-requisition/$requisitionId': {
      id: '/_authenticated/$storeId/distribution/customer-requisition/$requisitionId'
      path: '/distribution/customer-requisition/$requisitionId'
      fullPath: '/$storeId/distribution/customer-requisition/$requisitionId'
      preLoaderRoute: typeof AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
  }
}

interface AuthenticatedStoreIdRouteChildren {
  AuthenticatedStoreIdReportsRoute: typeof AuthenticatedStoreIdReportsRoute
  AuthenticatedStoreIdSettingsRoute: typeof AuthenticatedStoreIdSettingsRoute
  AuthenticatedStoreIdIndexRoute: typeof AuthenticatedStoreIdIndexRoute
  AuthenticatedStoreIdCatalogueAssetsRoute: typeof AuthenticatedStoreIdCatalogueAssetsRoute
  AuthenticatedStoreIdCatalogueItemsRoute: typeof AuthenticatedStoreIdCatalogueItemsRoute
  AuthenticatedStoreIdCatalogueMasterListsRoute: typeof AuthenticatedStoreIdCatalogueMasterListsRoute
  AuthenticatedStoreIdColdChainEquipmentRoute: typeof AuthenticatedStoreIdColdChainEquipmentRoute
  AuthenticatedStoreIdColdChainMonitoringRoute: typeof AuthenticatedStoreIdColdChainMonitoringRoute
  AuthenticatedStoreIdColdChainSensorsRoute: typeof AuthenticatedStoreIdColdChainSensorsRoute
  AuthenticatedStoreIdDispensaryCliniciansRoute: typeof AuthenticatedStoreIdDispensaryCliniciansRoute
  AuthenticatedStoreIdDispensaryPatientsRoute: typeof AuthenticatedStoreIdDispensaryPatientsRoute
  AuthenticatedStoreIdDispensaryPrescriptionRoute: typeof AuthenticatedStoreIdDispensaryPrescriptionRoute
  AuthenticatedStoreIdInventoryLocationsRoute: typeof AuthenticatedStoreIdInventoryLocationsRoute
  AuthenticatedStoreIdManageCampaignsRoute: typeof AuthenticatedStoreIdManageCampaignsRoute
  AuthenticatedStoreIdManageGlobalPreferencesRoute: typeof AuthenticatedStoreIdManageGlobalPreferencesRoute
  AuthenticatedStoreIdManageStoresRoute: typeof AuthenticatedStoreIdManageStoresRoute
  AuthenticatedStoreIdStockStockLineIdRoute: typeof AuthenticatedStoreIdStockStockLineIdRoute
  AuthenticatedStoreIdStocktakeStocktakeIdRoute: typeof AuthenticatedStoreIdStocktakeStocktakeIdRoute
  AuthenticatedStoreIdStockIndexRoute: typeof AuthenticatedStoreIdStockIndexRoute
  AuthenticatedStoreIdStocktakeIndexRoute: typeof AuthenticatedStoreIdStocktakeIndexRoute
  AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute: typeof AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute
  AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute: typeof AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute
  AuthenticatedStoreIdDistributionCustomersNameIdRoute: typeof AuthenticatedStoreIdDistributionCustomersNameIdRoute
  AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute: typeof AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute
  AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute: typeof AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute
  AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute: typeof AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute
  AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute: typeof AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute
  AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute: typeof AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute
  AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute: typeof AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute
  AuthenticatedStoreIdDistributionCustomerReturnIndexRoute: typeof AuthenticatedStoreIdDistributionCustomerReturnIndexRoute
  AuthenticatedStoreIdDistributionCustomersIndexRoute: typeof AuthenticatedStoreIdDistributionCustomersIndexRoute
  AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute: typeof AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute
  AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute: typeof AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute
  AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute: typeof AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute
  AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute: typeof AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute
  AuthenticatedStoreIdReplenishmentSuppliersIndexRoute: typeof AuthenticatedStoreIdReplenishmentSuppliersIndexRoute
}

const AuthenticatedStoreIdRouteChildren: AuthenticatedStoreIdRouteChildren = {
  AuthenticatedStoreIdReportsRoute: AuthenticatedStoreIdReportsRoute,
  AuthenticatedStoreIdSettingsRoute: AuthenticatedStoreIdSettingsRoute,
  AuthenticatedStoreIdIndexRoute: AuthenticatedStoreIdIndexRoute,
  AuthenticatedStoreIdCatalogueAssetsRoute:
    AuthenticatedStoreIdCatalogueAssetsRoute,
  AuthenticatedStoreIdCatalogueItemsRoute:
    AuthenticatedStoreIdCatalogueItemsRoute,
  AuthenticatedStoreIdCatalogueMasterListsRoute:
    AuthenticatedStoreIdCatalogueMasterListsRoute,
  AuthenticatedStoreIdColdChainEquipmentRoute:
    AuthenticatedStoreIdColdChainEquipmentRoute,
  AuthenticatedStoreIdColdChainMonitoringRoute:
    AuthenticatedStoreIdColdChainMonitoringRoute,
  AuthenticatedStoreIdColdChainSensorsRoute:
    AuthenticatedStoreIdColdChainSensorsRoute,
  AuthenticatedStoreIdDispensaryCliniciansRoute:
    AuthenticatedStoreIdDispensaryCliniciansRoute,
  AuthenticatedStoreIdDispensaryPatientsRoute:
    AuthenticatedStoreIdDispensaryPatientsRoute,
  AuthenticatedStoreIdDispensaryPrescriptionRoute:
    AuthenticatedStoreIdDispensaryPrescriptionRoute,
  AuthenticatedStoreIdInventoryLocationsRoute:
    AuthenticatedStoreIdInventoryLocationsRoute,
  AuthenticatedStoreIdManageCampaignsRoute:
    AuthenticatedStoreIdManageCampaignsRoute,
  AuthenticatedStoreIdManageGlobalPreferencesRoute:
    AuthenticatedStoreIdManageGlobalPreferencesRoute,
  AuthenticatedStoreIdManageStoresRoute: AuthenticatedStoreIdManageStoresRoute,
  AuthenticatedStoreIdStockStockLineIdRoute:
    AuthenticatedStoreIdStockStockLineIdRoute,
  AuthenticatedStoreIdStocktakeStocktakeIdRoute:
    AuthenticatedStoreIdStocktakeStocktakeIdRoute,
  AuthenticatedStoreIdStockIndexRoute: AuthenticatedStoreIdStockIndexRoute,
  AuthenticatedStoreIdStocktakeIndexRoute:
    AuthenticatedStoreIdStocktakeIndexRoute,
  AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute:
    AuthenticatedStoreIdDistributionCustomerRequisitionRequisitionIdRoute,
  AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute:
    AuthenticatedStoreIdDistributionCustomerReturnInvoiceIdRoute,
  AuthenticatedStoreIdDistributionCustomersNameIdRoute:
    AuthenticatedStoreIdDistributionCustomersNameIdRoute,
  AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute:
    AuthenticatedStoreIdDistributionOutboundShipmentInvoiceIdRoute,
  AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute:
    AuthenticatedStoreIdReplenishmentInboundShipmentInvoiceIdRoute,
  AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute:
    AuthenticatedStoreIdReplenishmentInternalOrderRequisitionIdRoute,
  AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute:
    AuthenticatedStoreIdReplenishmentSupplierReturnInvoiceIdRoute,
  AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute:
    AuthenticatedStoreIdReplenishmentSuppliersNameIdRoute,
  AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute:
    AuthenticatedStoreIdDistributionCustomerRequisitionIndexRoute,
  AuthenticatedStoreIdDistributionCustomerReturnIndexRoute:
    AuthenticatedStoreIdDistributionCustomerReturnIndexRoute,
  AuthenticatedStoreIdDistributionCustomersIndexRoute:
    AuthenticatedStoreIdDistributionCustomersIndexRoute,
  AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute:
    AuthenticatedStoreIdDistributionOutboundShipmentIndexRoute,
  AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute:
    AuthenticatedStoreIdReplenishmentInboundShipmentIndexRoute,
  AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute:
    AuthenticatedStoreIdReplenishmentInternalOrderIndexRoute,
  AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute:
    AuthenticatedStoreIdReplenishmentSupplierReturnIndexRoute,
  AuthenticatedStoreIdReplenishmentSuppliersIndexRoute:
    AuthenticatedStoreIdReplenishmentSuppliersIndexRoute,
}

const AuthenticatedStoreIdRouteWithChildren =
  AuthenticatedStoreIdRoute._addFileChildren(AuthenticatedStoreIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStoreIdRoute: typeof AuthenticatedStoreIdRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStoreIdRoute: AuthenticatedStoreIdRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
