/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type CliniciansVariables = {
  storeId: string;
};

export type CliniciansResult = {
  clinicians: ({
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  firstName: string | null;
  lastName: string;
  initials: string;
}>;
});
};

export const Clinicians = {
  query: "query clinicians($storeId: String!) {\n  clinicians(storeId: $storeId, filter: {isActive: true}, page: {first: 1000}) {\n    ... on ClinicianConnector {\n      totalCount\n      nodes {\n        id\n        code\n        firstName\n        lastName\n        initials\n      }\n    }\n  }\n}",
} as TypedDocument<CliniciansResult, CliniciansVariables>;
