/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type SiteRowFragment = {
  __typename: "SiteNode";
  id: number;
  code: string;
  name: string;
  hardwareId: string | null;
  syncVersion: "V5V6" | "V7";
  appVersion: string | null;
  lastConnectionDatetime: string | null;
  lastSyncDatetime: string | null;
  isMultiDevice: boolean;
};

export type SiteStoreRowFragment = {
  __typename: "StoreNode";
  id: string;
  code: string;
  storeName: string;
  siteId: number;
};

export type SitesVariables = {
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
  filter?: {
    id?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "id" | "code" | "name";
    desc?: boolean | null;
  }> | null;
};

export type SitesResult = {
  centralServer: {
  site: {
  sites: ({
  __typename: "SiteConnector";
} & {
  totalCount: number;
  nodes: Array<SiteRowFragment>;
});
};
};
};

export const Sites = {
  query: "query sites($page: PaginationInput, $filter: SiteFilterInput, $sort: [SiteSortInput!]) {\n  centralServer {\n    site {\n      sites(page: $page, filter: $filter, sort: $sort) {\n        ... on SiteConnector {\n          __typename\n          totalCount\n          nodes {\n            ...SiteRow\n          }\n        }\n      }\n    }\n  }\n}\n\nfragment SiteRow on SiteNode {\n  __typename\n  id\n  code\n  name\n  hardwareId\n  syncVersion\n  appVersion\n  lastConnectionDatetime\n  lastSyncDatetime\n  isMultiDevice\n}",
} as TypedDocument<SitesResult, SitesVariables>;

export type SiteDeploymentVariables = Record<string, never>;

export type SiteDeploymentResult = {
  isCentralStandalone: boolean;
  featureFlags: unknown;
  syncSettings: {
  centralServerSiteId: number;
  syncSiteId: number | null;
} | null;
};

export const SiteDeployment = {
  query: "query siteDeployment {\n  isCentralStandalone\n  featureFlags\n  syncSettings {\n    centralServerSiteId\n    syncSiteId\n  }\n}",
} as TypedDocument<SiteDeploymentResult, SiteDeploymentVariables>;

export type StoresBySiteVariables = {
  siteId: number;
};

export type StoresBySiteResult = {
  stores: ({
  __typename: "StoreConnector";
} & {
  totalCount: number;
  nodes: Array<SiteStoreRowFragment>;
});
};

export const StoresBySite = {
  query: "query storesBySite($siteId: Int!) {\n  stores(filter: {siteId: {equalTo: $siteId}}, page: {first: 1000}) {\n    ... on StoreConnector {\n      __typename\n      totalCount\n      nodes {\n        ...SiteStoreRow\n      }\n    }\n  }\n}\n\nfragment SiteStoreRow on StoreNode {\n  __typename\n  id\n  code\n  storeName\n  siteId\n}",
} as TypedDocument<StoresBySiteResult, StoresBySiteVariables>;

export type StoreSearchVariables = {
  search?: string | null;
  excludeIds?: Array<string> | null;
  first?: number | null;
  offset?: number | null;
};

export type StoreSearchResult = {
  stores: ({
  __typename: "StoreConnector";
} & {
  totalCount: number;
  nodes: Array<SiteStoreRowFragment>;
});
};

export const StoreSearch = {
  query: "query storeSearch($search: String, $excludeIds: [String!], $first: Int, $offset: Int) {\n  stores(\n    page: {first: $first, offset: $offset}\n    filter: {codeOrName: {like: $search}, id: {notEqualAll: $excludeIds}}\n    sort: [{key: name}]\n  ) {\n    ... on StoreConnector {\n      __typename\n      totalCount\n      nodes {\n        ...SiteStoreRow\n      }\n    }\n  }\n}\n\nfragment SiteStoreRow on StoreNode {\n  __typename\n  id\n  code\n  storeName\n  siteId\n}",
} as TypedDocument<StoreSearchResult, StoreSearchVariables>;

export type UpsertSiteVariables = {
  input: {
    id: number;
    code?: string | null;
    name: string;
    password?: string | null;
  };
};

export type UpsertSiteResult = {
  centralServer: {
  site: {
  upsertSite: ({
  __typename: "SiteNode";
} & SiteRowFragment) | ({
  __typename: "UpsertSiteError";
} & {
  error: ({
  __typename: "CodeRequired";
} & {
  description: string;
}) | ({
  __typename: "NameRequired";
} & {
  description: string;
}) | ({
  __typename: "PasswordRequired";
} & {
  description: string;
}) | ({
  __typename: "UniqueValueViolation";
} & {
  field: "code" | "serial" | "name";
} & {
  description: string;
});
});
};
};
};

export const UpsertSite = {
  query: "mutation upsertSite($input: UpsertSiteInput!) {\n  centralServer {\n    site {\n      upsertSite(input: $input) {\n        __typename\n        ... on SiteNode {\n          ...SiteRow\n        }\n        ... on UpsertSiteError {\n          __typename\n          error {\n            __typename\n            description\n            ... on CodeRequired {\n              __typename\n            }\n            ... on NameRequired {\n              __typename\n            }\n            ... on PasswordRequired {\n              __typename\n            }\n            ... on UniqueValueViolation {\n              __typename\n              field\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nfragment SiteRow on SiteNode {\n  __typename\n  id\n  code\n  name\n  hardwareId\n  syncVersion\n  appVersion\n  lastConnectionDatetime\n  lastSyncDatetime\n  isMultiDevice\n}",
} as TypedDocument<UpsertSiteResult, UpsertSiteVariables>;

export type AssignStoresToSiteVariables = {
  input: {
    siteId: number;
    storeIds: Array<string>;
  };
};

export type AssignStoresToSiteResult = {
  centralServer: {
  site: {
  assignStoresToSite: {
  siteId: number;
  storeIds: Array<string>;
};
};
};
};

export const AssignStoresToSite = {
  query: "mutation assignStoresToSite($input: AssignStoresToSiteInput!) {\n  centralServer {\n    site {\n      assignStoresToSite(input: $input) {\n        siteId\n        storeIds\n      }\n    }\n  }\n}",
} as TypedDocument<AssignStoresToSiteResult, AssignStoresToSiteVariables>;

export type DeleteSiteVariables = {
  siteId: number;
};

export type DeleteSiteResult = {
  centralServer: {
  site: {
  deleteSite: ({
  __typename: "DeleteSiteNode";
} & {
  id: number;
}) | ({
  __typename: "DeleteSiteError";
} & {
  error: ({
  __typename: "SiteHasStores";
} & {
  description: string;
}) | ({
  __typename: "CannotDeleteCentralSite";
} & {
  description: string;
});
});
};
};
};

export const DeleteSite = {
  query: "mutation deleteSite($siteId: Int!) {\n  centralServer {\n    site {\n      deleteSite(siteId: $siteId) {\n        __typename\n        ... on DeleteSiteNode {\n          id\n        }\n        ... on DeleteSiteError {\n          __typename\n          error {\n            __typename\n            description\n            ... on SiteHasStores {\n              __typename\n            }\n            ... on CannotDeleteCentralSite {\n              __typename\n            }\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteSiteResult, DeleteSiteVariables>;

export type ClearSiteHardwareIdVariables = {
  siteId: number;
};

export type ClearSiteHardwareIdResult = {
  centralServer: {
  site: {
  clearSiteHardwareId: {
  id: number;
};
};
};
};

export const ClearSiteHardwareId = {
  query: "mutation clearSiteHardwareId($siteId: Int!) {\n  centralServer {\n    site {\n      clearSiteHardwareId(siteId: $siteId) {\n        id\n      }\n    }\n  }\n}",
} as TypedDocument<ClearSiteHardwareIdResult, ClearSiteHardwareIdVariables>;

export type ClearSiteTokenVariables = {
  siteId: number;
};

export type ClearSiteTokenResult = {
  centralServer: {
  site: {
  clearSiteToken: {
  id: number;
};
};
};
};

export const ClearSiteToken = {
  query: "mutation clearSiteToken($siteId: Int!) {\n  centralServer {\n    site {\n      clearSiteToken(siteId: $siteId) {\n        id\n      }\n    }\n  }\n}",
} as TypedDocument<ClearSiteTokenResult, ClearSiteTokenVariables>;

export type SetSiteMultiDeviceVariables = {
  siteId: number;
  isMultiDevice: boolean;
};

export type SetSiteMultiDeviceResult = {
  centralServer: {
  site: {
  setSiteMultiDevice: {
  id: number;
};
};
};
};

export const SetSiteMultiDevice = {
  query: "mutation setSiteMultiDevice($siteId: Int!, $isMultiDevice: Boolean!) {\n  centralServer {\n    site {\n      setSiteMultiDevice(siteId: $siteId, isMultiDevice: $isMultiDevice) {\n        id\n      }\n    }\n  }\n}",
} as TypedDocument<SetSiteMultiDeviceResult, SetSiteMultiDeviceVariables>;
