/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type ActiveVvmStatusesVariables = {
  storeId: string;
};

export type ActiveVvmStatusesResult = {
  activeVvmStatuses: ({
  __typename: "VvmstatusConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  description: string;
  priority: number;
}>;
});
};

export const ActiveVvmStatuses = {
  query: "query activeVvmStatuses($storeId: String!) {\n  activeVvmStatuses(storeId: $storeId) {\n    ... on VvmstatusConnector {\n      __typename\n      nodes {\n        id\n        code\n        description\n        priority\n      }\n    }\n  }\n}",
} as TypedDocument<ActiveVvmStatusesResult, ActiveVvmStatusesVariables>;
