/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type RnrFormLineFragment = {
  id: string;
  item: {
  id: string;
  code: string;
  name: string;
  unitName: string | null;
  venCategory: "V" | "E" | "N" | "NOT_ASSIGNED";
};
  previousMonthlyConsumptionValues: string;
  averageMonthlyConsumption: number;
  initialBalance: number;
  quantityReceived: number;
  quantityConsumed: number;
  adjustedQuantityConsumed: number;
  losses: number;
  adjustments: number;
  stockOutDuration: number;
  finalBalance: number;
  minimumQuantity: number;
  maximumQuantity: number;
  expiryDate: string | null;
  calculatedRequestedQuantity: number;
  enteredRequestedQuantity: number | null;
  lowStock: "BELOW_QUARTER" | "BELOW_HALF" | "OK";
  comment: string | null;
  confirmed: boolean;
  approvedQuantity: number | null;
};

export type RnrFormInfoFragment = {
  id: string;
  status: "DRAFT" | "FINALISED";
  createdDatetime: string;
  theirReference: string | null;
  comment: string | null;
  periodLength: number;
  programId: string;
  programName: string;
  supplierId: string;
  supplierName: string;
  period: {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
};
};

export type RnrFormDetailVariables = {
  storeId: string;
  id: string;
};

export type RnrFormDetailResult = {
  rAndRForm: ({
  __typename: "RnRFormNode";
} & {
  lines: Array<RnrFormLineFragment>;
} & RnrFormInfoFragment) | ({
  __typename: "NodeError";
} & {
  error: {
  __typename: "DatabaseError" | "RecordNotFound";
  description: string;
};
});
};

export const RnrFormDetail = {
  query: "query RnrFormDetail($storeId: String!, $id: String!) {\n  rAndRForm(storeId: $storeId, rnrFormId: $id) {\n    __typename\n    ... on RnRFormNode {\n      ...RnrFormInfo\n      lines {\n        ...RnrFormLine\n      }\n    }\n    ... on NodeError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}\n\nfragment RnrFormInfo on RnRFormNode {\n  id\n  status\n  createdDatetime\n  theirReference\n  comment\n  periodLength\n  programId\n  programName\n  supplierId\n  supplierName\n  period {\n    id\n    name\n    startDate\n    endDate\n  }\n}\n\nfragment RnrFormLine on RnRFormLineNode {\n  id\n  item {\n    id\n    code\n    name\n    unitName\n    venCategory\n  }\n  previousMonthlyConsumptionValues\n  averageMonthlyConsumption\n  initialBalance\n  quantityReceived\n  quantityConsumed\n  adjustedQuantityConsumed\n  losses\n  adjustments\n  stockOutDuration\n  finalBalance\n  minimumQuantity\n  maximumQuantity\n  expiryDate\n  calculatedRequestedQuantity\n  enteredRequestedQuantity\n  lowStock\n  comment\n  confirmed\n  approvedQuantity\n}",
} as TypedDocument<RnrFormDetailResult, RnrFormDetailVariables>;

export type RnrFormDetailContextVariables = {
  storeId: string;
};

export type RnrFormDetailContextResult = {
  storePreferences: {
  id: string;
  monthsOverstock: number;
  monthsUnderstock: number;
};
};

export const RnrFormDetailContext = {
  query: "query RnrFormDetailContext($storeId: String!) {\n  storePreferences(storeId: $storeId) {\n    id\n    monthsOverstock\n    monthsUnderstock\n  }\n}",
} as TypedDocument<RnrFormDetailContextResult, RnrFormDetailContextVariables>;

export type UpdateRnrFormVariables = {
  storeId: string;
  input: {
    id: string;
    lines: Array<{
    id: string;
    quantityReceived?: number | null;
    quantityConsumed?: number | null;
    losses?: number | null;
    adjustments?: number | null;
    expiryDate?: string | null;
    stockOutDuration: number;
    adjustedQuantityConsumed: number;
    averageMonthlyConsumption: number;
    initialBalance: number;
    finalBalance: number;
    minimumQuantity: number;
    maximumQuantity: number;
    calculatedRequestedQuantity: number;
    enteredRequestedQuantity?: number | null;
    lowStock: "BELOW_QUARTER" | "BELOW_HALF" | "OK";
    comment?: string | null;
    confirmed: boolean;
  }>;
    theirReference?: string | null;
    comment?: string | null;
  };
};

export type UpdateRnrFormResult = {
  updateRnrForm: ({
  __typename: "RnRFormNode";
} & {
  lines: Array<RnrFormLineFragment>;
} & RnrFormInfoFragment);
};

export const UpdateRnrForm = {
  query: "mutation UpdateRnrForm($storeId: String!, $input: UpdateRnRFormInput!) {\n  updateRnrForm(storeId: $storeId, input: $input) {\n    ... on RnRFormNode {\n      __typename\n      ...RnrFormInfo\n      lines {\n        ...RnrFormLine\n      }\n    }\n  }\n}\n\nfragment RnrFormInfo on RnRFormNode {\n  id\n  status\n  createdDatetime\n  theirReference\n  comment\n  periodLength\n  programId\n  programName\n  supplierId\n  supplierName\n  period {\n    id\n    name\n    startDate\n    endDate\n  }\n}\n\nfragment RnrFormLine on RnRFormLineNode {\n  id\n  item {\n    id\n    code\n    name\n    unitName\n    venCategory\n  }\n  previousMonthlyConsumptionValues\n  averageMonthlyConsumption\n  initialBalance\n  quantityReceived\n  quantityConsumed\n  adjustedQuantityConsumed\n  losses\n  adjustments\n  stockOutDuration\n  finalBalance\n  minimumQuantity\n  maximumQuantity\n  expiryDate\n  calculatedRequestedQuantity\n  enteredRequestedQuantity\n  lowStock\n  comment\n  confirmed\n  approvedQuantity\n}",
} as TypedDocument<UpdateRnrFormResult, UpdateRnrFormVariables>;

export type FinaliseRnrFormVariables = {
  storeId: string;
  input: {
    id: string;
  };
};

export type FinaliseRnrFormResult = {
  finaliseRnrForm: ({
  __typename: "RnRFormNode";
} & {
  lines: Array<RnrFormLineFragment>;
} & RnrFormInfoFragment);
};

export const FinaliseRnrForm = {
  query: "mutation FinaliseRnrForm($storeId: String!, $input: FinaliseRnRFormInput!) {\n  finaliseRnrForm(storeId: $storeId, input: $input) {\n    ... on RnRFormNode {\n      __typename\n      ...RnrFormInfo\n      lines {\n        ...RnrFormLine\n      }\n    }\n  }\n}\n\nfragment RnrFormInfo on RnRFormNode {\n  id\n  status\n  createdDatetime\n  theirReference\n  comment\n  periodLength\n  programId\n  programName\n  supplierId\n  supplierName\n  period {\n    id\n    name\n    startDate\n    endDate\n  }\n}\n\nfragment RnrFormLine on RnRFormLineNode {\n  id\n  item {\n    id\n    code\n    name\n    unitName\n    venCategory\n  }\n  previousMonthlyConsumptionValues\n  averageMonthlyConsumption\n  initialBalance\n  quantityReceived\n  quantityConsumed\n  adjustedQuantityConsumed\n  losses\n  adjustments\n  stockOutDuration\n  finalBalance\n  minimumQuantity\n  maximumQuantity\n  expiryDate\n  calculatedRequestedQuantity\n  enteredRequestedQuantity\n  lowStock\n  comment\n  confirmed\n  approvedQuantity\n}",
} as TypedDocument<FinaliseRnrFormResult, FinaliseRnrFormVariables>;
