use repository::{syncv7::SyncRecordSerializeError, *};
use serde::de::DeserializeOwned;

use crate::sync_v7::{
    translations::{invoice_line::translate_invoice_line, store::translate_store},
    validate_translate_integrate::{create_changelog, SyncContext},
};

/// Deserialise `data` as `T`, then map it into a `Row` variant via `wrap` (e.g.
/// `Row::Invoice`). The wrapper is passed explicitly per table since there is no
/// blanket `From<XRow> for Row`.
fn from_value<T: DeserializeOwned>(
    data: serde_json::Value,
    wrap: impl FnOnce(T) -> Row,
) -> Result<Row, SyncRecordSerializeError> {
    serde_json::from_value::<T>(data)
        .map(|r| wrap(r))
        .map_err(|e| SyncRecordSerializeError::SerdeError(e.to_string()))
}

pub fn serialize(row: &Row) -> Result<serde_json::Value, SyncRecordSerializeError> {
    let map_serde_err = |e: serde_json::Error| SyncRecordSerializeError::SerdeError(e.to_string());

    match row {
        Row::Unit(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Currency(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Name(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Store(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::LocationType(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Item(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::StockLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Invoice(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::InvoiceLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ActivityLog(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Barcode(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Clinician(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ClinicianStoreJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Document(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::IndicatorValue(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::InsuranceProvider(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Location(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::LocationMovement(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameInsuranceJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameStoreJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::PurchaseOrder(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::PurchaseOrderLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Sensor(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Stocktake(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::StocktakeLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::TemperatureBreach(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::TemperatureLog(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VVMStatusLog(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Requisition(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::RequisitionLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetCatalogueItem(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetCategory(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetClass(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetLogReason(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetProperty(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::BackendPlugin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AncillaryItem(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::BundledItem(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Campaign(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Demographic(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::FormSchema(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::FrontendPlugin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ItemVariant(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameProperty(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::PackagingVariant(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Property(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Report(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VaccineCourse(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VaccineCourseDose(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VaccineCourseItem(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VaccineCourseStoreConfig(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::MasterList(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Asset(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetInternalLocation(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetLog(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Encounter(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::RnrForm(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::RnrFormLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::SyncMessage(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Vaccination(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::SyncFileReference(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::PluginData(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Preference(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ContactForm(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::SystemLog(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Abbreviation(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Category(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Contact(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ContactTrace(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Context(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::DemographicIndicator(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Diagnosis(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::DocumentRegistry(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::IndicatorColumn(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::IndicatorLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ItemCategoryJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ItemDirection(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ItemStoreJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ItemWarningJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::MasterListLine(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::MasterListNameJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameTag(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameTagJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Period(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::PeriodSchedule(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Printer(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Program(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ProgramEnrolment(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ProgramEvent(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ProgramIndicator(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ProgramRequisitionOrderType(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ProgramRequisitionSettings(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ReasonOption(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::ShippingMethod(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::StorePreference(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::UserAccount(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::UserPermission(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::UserStoreJoin(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::VVMStatus(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::NameOmsFields(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::Site(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::AssetCatalogueType(r) => serde_json::to_value(r).map_err(map_serde_err),
        Row::SyncRequest(r) => serde_json::to_value(r).map_err(map_serde_err),
    }
}

pub(crate) fn deserialize(
    connection: &StorageConnection,
    table_name: &ChangelogTableName,
    row: SyncBufferRow,
    sync_context: &SyncContext,
) -> Result<Vec<(Row, String, Option<ChangeLogInsertRow>)>, SyncRecordSerializeError> {
    let changelog_insert = create_changelog(table_name.clone(), RowActionType::Upsert, &row);
    let data = row.data.0;
    let record_id = row.record_id.clone();
    let upsert = match table_name {
        // Special
        ChangelogTableName::Store => {
            return translate_store(connection, record_id, changelog_insert, data)
        }
        ChangelogTableName::InvoiceLine => {
            return translate_invoice_line(
                record_id,
                changelog_insert,
                row.store_id.as_deref(),
                data,
                sync_context,
            )
        }
        // Basic
        ChangelogTableName::Unit => from_value(data, Row::Unit),
        ChangelogTableName::Currency => from_value(data, Row::Currency),
        ChangelogTableName::Name => from_value(data, Row::Name),
        ChangelogTableName::LocationType => from_value(data, Row::LocationType),
        ChangelogTableName::Item => from_value(data, Row::Item),
        ChangelogTableName::StockLine => from_value(data, Row::StockLine),
        ChangelogTableName::Invoice => from_value(data, Row::Invoice),
        ChangelogTableName::ActivityLog => from_value(data, Row::ActivityLog),
        ChangelogTableName::Barcode => from_value(data, Row::Barcode),
        ChangelogTableName::Clinician => from_value(data, Row::Clinician),
        ChangelogTableName::ClinicianStoreJoin => from_value(data, Row::ClinicianStoreJoin),
        ChangelogTableName::Document => from_value(data, Row::Document),
        ChangelogTableName::IndicatorValue => from_value(data, Row::IndicatorValue),
        ChangelogTableName::InsuranceProvider => from_value(data, Row::InsuranceProvider),
        ChangelogTableName::Location => from_value(data, Row::Location),
        ChangelogTableName::LocationMovement => from_value(data, Row::LocationMovement),
        ChangelogTableName::NameInsuranceJoin => from_value(data, Row::NameInsuranceJoin),
        ChangelogTableName::NameStoreJoin => from_value(data, Row::NameStoreJoin),
        ChangelogTableName::PurchaseOrder => from_value(data, Row::PurchaseOrder),
        ChangelogTableName::PurchaseOrderLine => from_value(data, Row::PurchaseOrderLine),
        ChangelogTableName::Sensor => from_value(data, Row::Sensor),
        ChangelogTableName::Stocktake => from_value(data, Row::Stocktake),
        ChangelogTableName::StocktakeLine => from_value(data, Row::StocktakeLine),
        ChangelogTableName::TemperatureBreach => from_value(data, Row::TemperatureBreach),
        ChangelogTableName::TemperatureLog => from_value(data, Row::TemperatureLog),
        ChangelogTableName::VVMStatusLog => from_value(data, Row::VVMStatusLog),
        ChangelogTableName::Requisition => from_value(data, Row::Requisition),
        ChangelogTableName::RequisitionLine => from_value(data, Row::RequisitionLine),
        ChangelogTableName::AssetCatalogueItem => from_value(data, Row::AssetCatalogueItem),
        ChangelogTableName::AssetCatalogueType => from_value(data, Row::AssetCatalogueType),
        ChangelogTableName::AssetCategory => from_value(data, Row::AssetCategory),
        ChangelogTableName::AssetClass => from_value(data, Row::AssetClass),
        ChangelogTableName::AssetLogReason => from_value(data, Row::AssetLogReason),
        ChangelogTableName::AssetProperty => from_value(data, Row::AssetProperty),
        ChangelogTableName::BackendPlugin => from_value(data, Row::BackendPlugin),
        ChangelogTableName::AncillaryItem => from_value(data, Row::AncillaryItem),
        ChangelogTableName::BundledItem => from_value(data, Row::BundledItem),
        ChangelogTableName::Campaign => from_value(data, Row::Campaign),
        ChangelogTableName::Demographic => from_value(data, Row::Demographic),
        ChangelogTableName::FormSchema => from_value(data, Row::FormSchema),
        ChangelogTableName::FrontendPlugin => from_value(data, Row::FrontendPlugin),
        ChangelogTableName::ItemVariant => from_value(data, Row::ItemVariant),
        ChangelogTableName::NameOmsFields => from_value(data, Row::NameOmsFields),
        ChangelogTableName::NameProperty => from_value(data, Row::NameProperty),
        ChangelogTableName::PackagingVariant => from_value(data, Row::PackagingVariant),
        ChangelogTableName::Property => from_value(data, Row::Property),
        ChangelogTableName::Report => from_value(data, Row::Report),
        ChangelogTableName::VaccineCourse => from_value(data, Row::VaccineCourse),
        ChangelogTableName::VaccineCourseDose => from_value(data, Row::VaccineCourseDose),
        ChangelogTableName::VaccineCourseItem => from_value(data, Row::VaccineCourseItem),
        ChangelogTableName::VaccineCourseStoreConfig => {
            from_value(data, Row::VaccineCourseStoreConfig)
        }
        ChangelogTableName::Abbreviation => from_value(data, Row::Abbreviation),
        ChangelogTableName::Category => from_value(data, Row::Category),
        ChangelogTableName::Contact => from_value(data, Row::Contact),
        ChangelogTableName::ContactTrace => from_value(data, Row::ContactTrace),
        ChangelogTableName::Context => from_value(data, Row::Context),
        ChangelogTableName::DemographicIndicator => from_value(data, Row::DemographicIndicator),
        ChangelogTableName::Diagnosis => from_value(data, Row::Diagnosis),
        ChangelogTableName::DocumentRegistry => from_value(data, Row::DocumentRegistry),
        ChangelogTableName::IndicatorColumn => from_value(data, Row::IndicatorColumn),
        ChangelogTableName::IndicatorLine => from_value(data, Row::IndicatorLine),
        ChangelogTableName::ItemCategoryJoin => from_value(data, Row::ItemCategoryJoin),
        ChangelogTableName::ItemDirection => from_value(data, Row::ItemDirection),
        ChangelogTableName::ItemStoreJoin => from_value(data, Row::ItemStoreJoin),
        ChangelogTableName::ItemWarningJoin => from_value(data, Row::ItemWarningJoin),
        ChangelogTableName::MasterList => from_value(data, Row::MasterList),
        ChangelogTableName::MasterListLine => from_value(data, Row::MasterListLine),
        ChangelogTableName::MasterListNameJoin => from_value(data, Row::MasterListNameJoin),
        ChangelogTableName::NameTag => from_value(data, Row::NameTag),
        ChangelogTableName::NameTagJoin => from_value(data, Row::NameTagJoin),
        ChangelogTableName::Period => from_value(data, Row::Period),
        ChangelogTableName::PeriodSchedule => from_value(data, Row::PeriodSchedule),
        ChangelogTableName::Printer => from_value(data, Row::Printer),
        ChangelogTableName::Program => from_value(data, Row::Program),
        ChangelogTableName::ProgramEnrolment => from_value(data, Row::ProgramEnrolment),
        ChangelogTableName::ProgramEvent => from_value(data, Row::ProgramEvent),
        ChangelogTableName::ProgramIndicator => from_value(data, Row::ProgramIndicator),
        ChangelogTableName::ProgramRequisitionOrderType => {
            from_value(data, Row::ProgramRequisitionOrderType)
        }
        ChangelogTableName::ProgramRequisitionSettings => {
            from_value(data, Row::ProgramRequisitionSettings)
        }
        ChangelogTableName::ReasonOption => from_value(data, Row::ReasonOption),
        ChangelogTableName::ShippingMethod => from_value(data, Row::ShippingMethod),
        ChangelogTableName::StorePreference => from_value(data, Row::StorePreference),
        ChangelogTableName::UserAccount => from_value(data, Row::UserAccount),
        ChangelogTableName::UserPermission => from_value(data, Row::UserPermission),
        ChangelogTableName::UserStoreJoin => from_value(data, Row::UserStoreJoin),
        ChangelogTableName::VVMStatus => from_value(data, Row::VVMStatus),
        ChangelogTableName::Site => from_value(data, Row::Site),
        ChangelogTableName::Asset => from_value(data, Row::Asset),
        ChangelogTableName::AssetInternalLocation => from_value(data, Row::AssetInternalLocation),
        ChangelogTableName::AssetLog => from_value(data, Row::AssetLog),
        ChangelogTableName::Encounter => from_value(data, Row::Encounter),
        ChangelogTableName::RnrForm => from_value(data, Row::RnrForm),
        ChangelogTableName::RnrFormLine => from_value(data, Row::RnrFormLine),
        ChangelogTableName::SyncMessage => from_value(data, Row::SyncMessage),
        ChangelogTableName::Vaccination => from_value(data, Row::Vaccination),
        ChangelogTableName::SyncFileReference => from_value(data, Row::SyncFileReference),
        ChangelogTableName::PluginData => from_value(data, Row::PluginData),
        ChangelogTableName::Preference => from_value(data, Row::Preference),
        ChangelogTableName::ContactForm => from_value(data, Row::ContactForm),
        ChangelogTableName::SystemLog => from_value(data, Row::SystemLog),
    }?;

    Ok(vec![(upsert, record_id, Some(changelog_insert))])
}
