/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type FacilitiesVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isCustomer?: boolean | null;
    isSupplier?: boolean | null;
    isManufacturer?: boolean | null;
    isDonor?: boolean | null;
    isStore?: boolean | null;
    storeCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isVisible?: boolean | null;
    isSystemName?: boolean | null;
    type?: {
    equalTo?: "FACILITY" | "INVAD" | "REPACK" | "STORE" | null;
    equalAny?: Array<"FACILITY" | "INVAD" | "REPACK" | "STORE"> | null;
    notEqualTo?: "FACILITY" | "INVAD" | "REPACK" | "STORE" | null;
    notEqualAll?: Array<"FACILITY" | "INVAD" | "REPACK" | "STORE"> | null;
  } | null;
    phone?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    address1?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    address2?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    country?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    email?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    supplyingStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    dynamicFilter?: unknown | null;
  } | null;
  sort?: Array<{
    key: "name" | "code";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type FacilitiesResult = {
  names: ({
  __typename: "NameConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  isSupplier: boolean;
  isCustomer: boolean;
  isDonor: boolean;
  isOnHold: boolean;
  store: {
  id: string;
  code: string;
  isDisabled: boolean;
} | null;
  properties: string;
}>;
});
};

export const Facilities = {
  query: "query facilities($storeId: String!, $filter: NameFilterInput, $sort: [NameSortInput!], $page: PaginationInput) {\n  names(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on NameConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        code\n        name\n        isSupplier\n        isCustomer\n        isDonor\n        isOnHold\n        store {\n          id\n          code\n          isDisabled\n        }\n        properties\n      }\n    }\n  }\n}",
} as TypedDocument<FacilitiesResult, FacilitiesVariables>;

export type UpdateFacilityPropertiesVariables = {
  storeId: string;
  id: string;
  properties: string;
};

export type UpdateFacilityPropertiesResult = {
  updateNameProperties: ({
  __typename: "NameNode";
} & {
  id: string;
}) | ({
  __typename: "UpdateNamePropertiesError";
} & {
  error: {
  description: string;
};
});
};

export const UpdateFacilityProperties = {
  query: "mutation updateFacilityProperties($storeId: String!, $id: String!, $properties: String!) {\n  updateNameProperties(\n    storeId: $storeId\n    input: {id: $id, properties: $properties}\n  ) {\n    ... on NameNode {\n      __typename\n      id\n    }\n    ... on UpdateNamePropertiesError {\n      __typename\n      error {\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<UpdateFacilityPropertiesResult, UpdateFacilityPropertiesVariables>;
