/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type OutboundPreferencesVariables = {
  storeId: string;
};

export type OutboundPreferencesResult = {
  preferences: {
  manageVaccinesInDoses: boolean;
  manageVvmStatusForStock: boolean;
  sortByVvmStatusThenExpiry: boolean;
  allowTrackingOfStockByDonor: boolean;
  expiredStockPreventIssue: boolean;
  expiredStockIssueThreshold: number;
  invoiceStatusOptions: Array<"NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED">;
  backdating: {
  shipmentsEnabled: boolean;
  maxDays: number;
};
};
  storePreferences: {
  issueInForeignCurrency: boolean;
  monthsLeadTime: number;
};
};

export const OutboundPreferences = {
  query: "query outboundPreferences($storeId: String!) {\n  preferences(storeId: $storeId) {\n    manageVaccinesInDoses\n    manageVvmStatusForStock\n    sortByVvmStatusThenExpiry\n    allowTrackingOfStockByDonor\n    expiredStockPreventIssue\n    expiredStockIssueThreshold\n    invoiceStatusOptions\n    backdating {\n      shipmentsEnabled\n      maxDays\n    }\n  }\n  storePreferences(storeId: $storeId) {\n    issueInForeignCurrency\n    monthsLeadTime\n  }\n}",
} as TypedDocument<OutboundPreferencesResult, OutboundPreferencesVariables>;
