/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type PrescriptionOrdersVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    status?: {
    equalTo?: "NEW" | "READY_TO_DISPENSE" | "DISPENSED" | null;
    equalAny?: Array<"NEW" | "READY_TO_DISPENSE" | "DISPENSED"> | null;
    notEqualTo?: "NEW" | "READY_TO_DISPENSE" | "DISPENSED" | null;
    notEqualAll?: Array<"NEW" | "READY_TO_DISPENSE" | "DISPENSED"> | null;
  } | null;
    prescriptionOrderNumber?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    patientId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    patientName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    prescriptionDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "prescriptionOrderNumber" | "createdDatetime" | "prescriptionDatetime" | "status";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type PrescriptionOrdersResult = {
  prescriptionOrders: ({
  totalCount: number;
  nodes: Array<{
  id: string;
  prescriptionOrderNumber: number;
  status: "NEW" | "READY_TO_DISPENSE" | "DISPENSED";
  createdDatetime: string;
  prescriptionDatetime: string;
  comment: string | null;
  patient: {
  id: string;
  name: string;
} | null;
}>;
});
};

export const PrescriptionOrders = {
  query: "query prescriptionOrders($storeId: String!, $filter: PrescriptionOrderFilterInput, $sort: [PrescriptionOrderSortInput!], $page: PaginationInput) {\n  prescriptionOrders(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on PrescriptionOrderConnector {\n      totalCount\n      nodes {\n        id\n        prescriptionOrderNumber\n        status\n        createdDatetime\n        prescriptionDatetime\n        comment\n        patient {\n          id\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<PrescriptionOrdersResult, PrescriptionOrdersVariables>;

export type DeletePrescriptionOrderVariables = {
  storeId: string;
  id: string;
};

export type DeletePrescriptionOrderResult = {
  deletePrescriptionOrder: ({
  id: string;
});
};

export const DeletePrescriptionOrder = {
  query: "mutation deletePrescriptionOrder($storeId: String!, $id: String!) {\n  deletePrescriptionOrder(storeId: $storeId, id: $id) {\n    ... on DeleteResponse {\n      id\n    }\n  }\n}",
} as TypedDocument<DeletePrescriptionOrderResult, DeletePrescriptionOrderVariables>;
