/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type PrescriptionRequestFieldsFragment = {
  id: string;
  prescriptionRequestNumber: number;
  status: "NEW" | "READY_TO_DISPENSE" | "DISPENSED";
  createdDatetime: string;
  prescriptionDatetime: string;
  readyDatetime: string | null;
  dispensedDatetime: string | null;
  comment: string | null;
  customFields: unknown | null;
  patientId: string;
  patient: {
  id: string;
  name: string;
  code: string;
  dateOfBirth: string | null;
};
  diagnosisId: string | null;
  programId: string | null;
  user: {
  username: string;
  email: string | null;
} | null;
  lines: {
  totalCount: number;
  nodes: Array<{
  id: string;
  itemId: string;
  numberOfUnits: number;
  note: string | null;
  item: {
  id: string;
  code: string;
  name: string;
  unitName: string | null;
} | null;
}>;
};
};

export type PrescriptionRequestDetailVariables = {
  storeId: string;
  id: string;
};

export type PrescriptionRequestDetailResult = {
  prescriptionRequest: ({
  __typename: "PrescriptionRequestNode";
} & PrescriptionRequestFieldsFragment) | ({
  __typename: "RecordNotFound";
} & {
  description: string;
});
};

export const PrescriptionRequestDetail = {
  query: "query prescriptionRequestDetail($storeId: String!, $id: String!) {\n  prescriptionRequest(storeId: $storeId, id: $id) {\n    __typename\n    ... on PrescriptionRequestNode {\n      ...PrescriptionRequestFields\n    }\n    ... on RecordNotFound {\n      description\n    }\n  }\n}\n\nfragment PrescriptionRequestFields on PrescriptionRequestNode {\n  id\n  prescriptionRequestNumber\n  status\n  createdDatetime\n  prescriptionDatetime\n  readyDatetime\n  dispensedDatetime\n  comment\n  customFields\n  patientId\n  patient {\n    id\n    name\n    code\n    dateOfBirth\n  }\n  diagnosisId\n  programId\n  user {\n    username\n    email\n  }\n  lines {\n    totalCount\n    nodes {\n      id\n      itemId\n      numberOfUnits\n      note\n      item {\n        id\n        code\n        name\n        unitName\n      }\n    }\n  }\n}",
} as TypedDocument<PrescriptionRequestDetailResult, PrescriptionRequestDetailVariables>;

export type UpdatePrescriptionRequestVariables = {
  storeId: string;
  input: {
    id: string;
    patientId?: string | null;
    diagnosisId?: {
    value?: string | null;
  } | null;
    programId?: {
    value?: string | null;
  } | null;
    prescriptionDatetime?: string | null;
    comment?: {
    value?: string | null;
  } | null;
    customFields?: unknown | null;
    status?: "READY_TO_DISPENSE" | null;
    clinicianId?: string | null;
  };
};

export type UpdatePrescriptionRequestResult = {
  updatePrescriptionRequest: (PrescriptionRequestFieldsFragment);
};

export const UpdatePrescriptionRequest = {
  query: "mutation updatePrescriptionRequest($storeId: String!, $input: UpdatePrescriptionRequestInput!) {\n  updatePrescriptionRequest(storeId: $storeId, input: $input) {\n    ... on PrescriptionRequestNode {\n      ...PrescriptionRequestFields\n    }\n  }\n}\n\nfragment PrescriptionRequestFields on PrescriptionRequestNode {\n  id\n  prescriptionRequestNumber\n  status\n  createdDatetime\n  prescriptionDatetime\n  readyDatetime\n  dispensedDatetime\n  comment\n  customFields\n  patientId\n  patient {\n    id\n    name\n    code\n    dateOfBirth\n  }\n  diagnosisId\n  programId\n  user {\n    username\n    email\n  }\n  lines {\n    totalCount\n    nodes {\n      id\n      itemId\n      numberOfUnits\n      note\n      item {\n        id\n        code\n        name\n        unitName\n      }\n    }\n  }\n}",
} as TypedDocument<UpdatePrescriptionRequestResult, UpdatePrescriptionRequestVariables>;

export type DeletePrescriptionRequestByIdVariables = {
  storeId: string;
  id: string;
};

export type DeletePrescriptionRequestByIdResult = {
  deletePrescriptionRequest: ({
  id: string;
});
};

export const DeletePrescriptionRequestById = {
  query: "mutation deletePrescriptionRequestById($storeId: String!, $id: String!) {\n  deletePrescriptionRequest(storeId: $storeId, id: $id) {\n    ... on DeleteResponse {\n      id\n    }\n  }\n}",
} as TypedDocument<DeletePrescriptionRequestByIdResult, DeletePrescriptionRequestByIdVariables>;

export type RequestDiagnosesActiveVariables = Record<string, never>;

export type RequestDiagnosesActiveResult = {
  diagnosesActive: Array<{
  id: string;
  code: string;
  description: string;
}>;
};

export const RequestDiagnosesActive = {
  query: "query requestDiagnosesActive {\n  diagnosesActive {\n    id\n    code\n    description\n  }\n}",
} as TypedDocument<RequestDiagnosesActiveResult, RequestDiagnosesActiveVariables>;

export type GeneratedDispensationsVariables = {
  storeId: string;
  prescriptionRequestId: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  };
};

export type GeneratedDispensationsResult = {
  invoices: ({
  nodes: Array<{
  id: string;
  invoiceNumber: number;
  status: "NEW" | "ALLOCATED" | "PICKED" | "SHIPPED" | "DELIVERED" | "RECEIVED" | "VERIFIED" | "CANCELLED";
}>;
});
};

export const GeneratedDispensations = {
  query: "query generatedDispensations($storeId: String!, $prescriptionRequestId: EqualFilterStringInput!) {\n  invoices(\n    storeId: $storeId\n    filter: {prescriptionRequestId: $prescriptionRequestId}\n    type: [PRESCRIPTION]\n  ) {\n    ... on InvoiceConnector {\n      nodes {\n        id\n        invoiceNumber\n        status\n      }\n    }\n  }\n}",
} as TypedDocument<GeneratedDispensationsResult, GeneratedDispensationsVariables>;

export type DeletePrescriptionRequestLinesVariables = {
  storeId: string;
  ids: string[];
};

export type DeletePrescriptionRequestLinesResult = {
  batchPrescriptionRequest: {
  deletePrescriptionRequestLines?: Array<{
  id: string;
  response: ({
  id: string;
});
}> | null;
};
};

export const DeletePrescriptionRequestLines = {
  query: "mutation deletePrescriptionRequestLines($storeId: String!, $ids: [String!]!) {\n  batchPrescriptionRequest(\n    storeId: $storeId\n    input: {deletePrescriptionRequestLines: $ids}\n  ) {\n    deletePrescriptionRequestLines {\n      id\n      response {\n        ... on DeleteResponse {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeletePrescriptionRequestLinesResult, DeletePrescriptionRequestLinesVariables>;
