/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type PrescriptionRequestsVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    status?: {
    equalTo?: "NEW" | "READY_TO_DISPENSE" | "DISPENSED" | null;
    equalAny?: Array<"NEW" | "READY_TO_DISPENSE" | "DISPENSED"> | null;
    notEqualTo?: "NEW" | "READY_TO_DISPENSE" | "DISPENSED" | null;
    notEqualAll?: Array<"NEW" | "READY_TO_DISPENSE" | "DISPENSED"> | null;
  } | null;
    prescriptionRequestNumber?: {
    equalTo?: number | null;
    equalAny?: Array<number> | null;
    notEqualTo?: number | null;
    equalAnyOrNull?: Array<number> | null;
    notEqualAll?: Array<number> | null;
  } | null;
    patientId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    patientName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    prescriptionDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "prescriptionRequestNumber" | "createdDatetime" | "prescriptionDatetime" | "status";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type PrescriptionRequestsResult = {
  prescriptionRequests: ({
  totalCount: number;
  nodes: Array<{
  id: string;
  prescriptionRequestNumber: number;
  status: "NEW" | "READY_TO_DISPENSE" | "DISPENSED";
  createdDatetime: string;
  prescriptionDatetime: string;
  comment: string | null;
  patient: {
  id: string;
  name: string;
} | null;
}>;
});
};

export const PrescriptionRequests = {
  query: "query prescriptionRequests($storeId: String!, $filter: PrescriptionRequestFilterInput, $sort: [PrescriptionRequestSortInput!], $page: PaginationInput) {\n  prescriptionRequests(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on PrescriptionRequestConnector {\n      totalCount\n      nodes {\n        id\n        prescriptionRequestNumber\n        status\n        createdDatetime\n        prescriptionDatetime\n        comment\n        patient {\n          id\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<PrescriptionRequestsResult, PrescriptionRequestsVariables>;

export type DeletePrescriptionRequestVariables = {
  storeId: string;
  id: string;
};

export type DeletePrescriptionRequestResult = {
  deletePrescriptionRequest: ({
  id: string;
});
};

export const DeletePrescriptionRequest = {
  query: "mutation deletePrescriptionRequest($storeId: String!, $id: String!) {\n  deletePrescriptionRequest(storeId: $storeId, id: $id) {\n    ... on DeleteResponse {\n      id\n    }\n  }\n}",
} as TypedDocument<DeletePrescriptionRequestResult, DeletePrescriptionRequestVariables>;
