/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../api/graphql";

export type PluginDataRowFragment = {
  id: string;
  dataIdentifier: string;
  relatedRecordId: string | null;
  storeId: string | null;
  data: string;
  datetime: string | null;
};

export type PluginDataListVariables = {
  storeId: string;
  pluginCode: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    relatedRecordId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    dataIdentifier?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    datetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "id" | "pluginCode" | "datetime";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type PluginDataListResult = {
  pluginData: ({
  __typename: "PluginDataConnector";
} & {
  totalCount: number;
  nodes: Array<PluginDataRowFragment>;
});
};

export const PluginDataList = {
  query: "query pluginDataList($storeId: String!, $pluginCode: String!, $filter: PluginDataFilterInput, $sort: [PluginDataSortInput!], $page: PaginationInput) {\n  pluginData(\n    storeId: $storeId\n    pluginCode: $pluginCode\n    filter: $filter\n    sort: $sort\n    page: $page\n  ) {\n    ... on PluginDataConnector {\n      __typename\n      totalCount\n      nodes {\n        ...pluginDataRow\n      }\n    }\n  }\n}\n\nfragment pluginDataRow on PluginDataNode {\n  id\n  dataIdentifier\n  relatedRecordId\n  storeId\n  data\n  datetime\n}",
} as TypedDocument<PluginDataListResult, PluginDataListVariables>;

export type PluginDataInsertVariables = {
  storeId: string;
  input: {
    id: string;
    storeId?: string | null;
    pluginCode: string;
    relatedRecordId?: string | null;
    dataIdentifier: string;
    data: string;
    datetime?: string | null;
  };
};

export type PluginDataInsertResult = {
  insertPluginData: ({
  __typename: "PluginDataNode";
} & PluginDataRowFragment);
};

export const PluginDataInsert = {
  query: "mutation pluginDataInsert($storeId: String!, $input: InsertPluginDataInput!) {\n  insertPluginData(storeId: $storeId, input: $input) {\n    ... on PluginDataNode {\n      __typename\n      ...pluginDataRow\n    }\n  }\n}\n\nfragment pluginDataRow on PluginDataNode {\n  id\n  dataIdentifier\n  relatedRecordId\n  storeId\n  data\n  datetime\n}",
} as TypedDocument<PluginDataInsertResult, PluginDataInsertVariables>;

export type PluginDataUpdateVariables = {
  storeId: string;
  input: {
    id: string;
    storeId?: string | null;
    pluginCode: string;
    relatedRecordId?: string | null;
    dataIdentifier: string;
    data: string;
    datetime?: string | null;
  };
};

export type PluginDataUpdateResult = {
  updatePluginData: ({
  __typename: "PluginDataNode";
} & PluginDataRowFragment);
};

export const PluginDataUpdate = {
  query: "mutation pluginDataUpdate($storeId: String!, $input: UpdatePluginDataInput!) {\n  updatePluginData(storeId: $storeId, input: $input) {\n    ... on PluginDataNode {\n      __typename\n      ...pluginDataRow\n    }\n  }\n}\n\nfragment pluginDataRow on PluginDataNode {\n  id\n  dataIdentifier\n  relatedRecordId\n  storeId\n  data\n  datetime\n}",
} as TypedDocument<PluginDataUpdateResult, PluginDataUpdateVariables>;

export type PluginDataDeleteVariables = {
  storeId: string;
  id: string;
};

export type PluginDataDeleteResult = {
  deletePluginData: ({
  __typename: "DeleteResponse";
} & {
  id: string;
});
};

export const PluginDataDelete = {
  query: "mutation pluginDataDelete($storeId: String!, $id: String!) {\n  deletePluginData(storeId: $storeId, id: $id) {\n    ... on DeleteResponse {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<PluginDataDeleteResult, PluginDataDeleteVariables>;
