/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type AssetCatalogueItemsVariables = {
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    category?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    categoryId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    class?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    classId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    manufacturer?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    model?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    type?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    typeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    search?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    subCatalogue?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "catalogue" | "code" | "manufacturer" | "model";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type AssetCatalogueItemsResult = {
  assetCatalogueItems: ({
  __typename: "AssetCatalogueItemConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  subCatalogue: string;
  code: string;
  manufacturer: string | null;
  model: string;
  assetClassId: string;
  assetCategoryId: string;
  assetTypeId: string;
  assetClass: {
  name: string;
} | null;
  assetCategory: {
  name: string;
} | null;
  assetType: {
  name: string;
} | null;
}>;
});
};

export const AssetCatalogueItems = {
  query: "query assetCatalogueItems($filter: AssetCatalogueItemFilterInput, $sort: [AssetCatalogueItemSortInput!], $page: PaginationInput) {\n  assetCatalogueItems(filter: $filter, sort: $sort, page: $page) {\n    ... on AssetCatalogueItemConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        subCatalogue\n        code\n        manufacturer\n        model\n        assetClassId\n        assetCategoryId\n        assetTypeId\n        assetClass {\n          name\n        }\n        assetCategory {\n          name\n        }\n        assetType {\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<AssetCatalogueItemsResult, AssetCatalogueItemsVariables>;

export type AssetCategoriesVariables = Record<string, never>;

export type AssetCategoriesResult = {
  assetCategories: ({
  __typename: "AssetCategoryConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
  classId: string;
}>;
});
};

export const AssetCategories = {
  query: "query assetCategories {\n  assetCategories(sort: [{key: name}]) {\n    ... on AssetCategoryConnector {\n      __typename\n      nodes {\n        id\n        name\n        classId\n      }\n    }\n  }\n}",
} as TypedDocument<AssetCategoriesResult, AssetCategoriesVariables>;

export type AssetTypesVariables = Record<string, never>;

export type AssetTypesResult = {
  assetTypes: ({
  __typename: "AssetTypeConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
  categoryId: string;
}>;
});
};

export const AssetTypes = {
  query: "query assetTypes {\n  assetTypes(sort: [{key: name}]) {\n    ... on AssetTypeConnector {\n      __typename\n      nodes {\n        id\n        name\n        categoryId\n      }\n    }\n  }\n}",
} as TypedDocument<AssetTypesResult, AssetTypesVariables>;

export type DeleteAssetCatalogueItemVariables = {
  id: string;
};

export type DeleteAssetCatalogueItemResult = {
  centralServer: {
  assetCatalogue: {
  deleteAssetCatalogueItem: ({
  __typename: "DeleteResponse";
} & {
  id: string;
});
};
};
};

export const DeleteAssetCatalogueItem = {
  query: "mutation deleteAssetCatalogueItem($id: String!) {\n  centralServer {\n    assetCatalogue {\n      deleteAssetCatalogueItem(assetCatalogueItemId: $id) {\n        __typename\n        ... on DeleteResponse {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteAssetCatalogueItemResult, DeleteAssetCatalogueItemVariables>;
