ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_LOCATION_CHANGE';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_COST_PRICE_CHANGE';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_SELL_PRICE_CHANGE';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_EXPIRY_DATE_CHANGE';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_BATCH_CHANGE';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_ON_HOLD';
ALTER TYPE activity_log_type ADD VALUE IF NOT EXISTS 'STOCK_OFF_HOLD';
