/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type TemperatureLogRowFragment = {
  __typename: "TemperatureLogNode";
  id: string;
  datetime: string;
  temperature: number;
  sensorId: string;
  sensor: {
  id: string;
  name: string;
} | null;
  location: {
  id: string;
  code: string;
} | null;
  temperatureBreach: {
  id: string;
  type: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION";
} | null;
};

export type TemperatureBreachRowFragment = {
  __typename: "TemperatureBreachNode";
  id: string;
  sensorId: string;
  sensor: {
  id: string;
  name: string;
} | null;
  startDatetime: string;
  endDatetime: string | null;
  unacknowledged: boolean;
  durationMilliseconds: number;
  type: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION";
  location: {
  id: string;
  code: string;
  name: string;
} | null;
  maxOrMinTemperature: number | null;
  comment: string | null;
};

export type TemperatureLogsVariables = {
  storeId: string;
  filter?: {
    datetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    sensor?: {
    serial?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isActive?: boolean | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    equalAny?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
    notEqualTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    notEqualAll?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
  } | null;
    locationCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
    location?: {
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    onHold?: boolean | null;
    assignedToAsset?: boolean | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationTypeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
    temperatureBreach?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    startDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    endDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    type?: {
    equalTo?: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION" | null;
    equalAny?: Array<"COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION"> | null;
    notEqualTo?: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION" | null;
    notEqualAll?: Array<"COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION"> | null;
  } | null;
    unacknowledged?: boolean | null;
    sensor?: {
    serial?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isActive?: boolean | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    equalAny?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
    notEqualTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    notEqualAll?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
  } | null;
    locationCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
    location?: {
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    onHold?: boolean | null;
    assignedToAsset?: boolean | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationTypeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "datetime" | "temperature";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type TemperatureLogsResult = {
  temperatureLogs: ({
  __typename: "TemperatureLogConnector";
} & {
  totalCount: number;
  nodes: Array<TemperatureLogRowFragment>;
});
};

export const TemperatureLogs = {
  query: "query temperatureLogs($storeId: String!, $filter: TemperatureLogFilterInput, $sort: [TemperatureLogSortInput!], $page: PaginationInput) {\n  temperatureLogs(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on TemperatureLogConnector {\n      __typename\n      totalCount\n      nodes {\n        ...TemperatureLogRow\n      }\n    }\n  }\n}\n\nfragment TemperatureLogRow on TemperatureLogNode {\n  __typename\n  id\n  datetime\n  temperature\n  sensorId\n  sensor {\n    id\n    name\n  }\n  location {\n    id\n    code\n  }\n  temperatureBreach {\n    id\n    type\n  }\n}",
} as TypedDocument<TemperatureLogsResult, TemperatureLogsVariables>;

export type TemperatureBreachesVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    startDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    endDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    type?: {
    equalTo?: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION" | null;
    equalAny?: Array<"COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION"> | null;
    notEqualTo?: "COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION" | null;
    notEqualAll?: Array<"COLD_CONSECUTIVE" | "COLD_CUMULATIVE" | "HOT_CONSECUTIVE" | "HOT_CUMULATIVE" | "EXCURSION"> | null;
  } | null;
    unacknowledged?: boolean | null;
    sensor?: {
    serial?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    isActive?: boolean | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    type?: {
    equalTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    equalAny?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
    notEqualTo?: "BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG" | null;
    notEqualAll?: Array<"BLUE_MAESTRO" | "LAIRD" | "BERLINGER" | "LOG_TAG"> | null;
  } | null;
    locationCode?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
  } | null;
    location?: {
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    onHold?: boolean | null;
    assignedToAsset?: boolean | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationTypeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "startDatetime" | "endDatetime";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type TemperatureBreachesResult = {
  temperatureBreaches: ({
  __typename: "TemperatureBreachConnector";
} & {
  totalCount: number;
  nodes: Array<TemperatureBreachRowFragment>;
});
};

export const TemperatureBreaches = {
  query: "query temperatureBreaches($storeId: String!, $filter: TemperatureBreachFilterInput, $sort: [TemperatureBreachSortInput!], $page: PaginationInput) {\n  temperatureBreaches(\n    storeId: $storeId\n    filter: $filter\n    sort: $sort\n    page: $page\n  ) {\n    ... on TemperatureBreachConnector {\n      __typename\n      totalCount\n      nodes {\n        ...TemperatureBreachRow\n      }\n    }\n  }\n}\n\nfragment TemperatureBreachRow on TemperatureBreachNode {\n  __typename\n  id\n  sensorId\n  sensor {\n    id\n    name\n  }\n  startDatetime\n  endDatetime\n  unacknowledged\n  durationMilliseconds\n  type\n  location {\n    id\n    code\n    name\n  }\n  maxOrMinTemperature\n  comment\n}",
} as TypedDocument<TemperatureBreachesResult, TemperatureBreachesVariables>;

export type BreachSummaryVariables = {
  storeId: string;
  id: string;
};

export type BreachSummaryResult = {
  temperatureBreaches: ({
  __typename: "TemperatureBreachConnector";
} & {
  nodes: Array<TemperatureBreachRowFragment>;
});
};

export const BreachSummary = {
  query: "query breachSummary($storeId: String!, $id: String!) {\n  temperatureBreaches(\n    storeId: $storeId\n    filter: {id: {equalTo: $id}}\n    page: {first: 1}\n  ) {\n    ... on TemperatureBreachConnector {\n      __typename\n      nodes {\n        ...TemperatureBreachRow\n      }\n    }\n  }\n}\n\nfragment TemperatureBreachRow on TemperatureBreachNode {\n  __typename\n  id\n  sensorId\n  sensor {\n    id\n    name\n  }\n  startDatetime\n  endDatetime\n  unacknowledged\n  durationMilliseconds\n  type\n  location {\n    id\n    code\n    name\n  }\n  maxOrMinTemperature\n  comment\n}",
} as TypedDocument<BreachSummaryResult, BreachSummaryVariables>;

export type TemperatureNotificationsVariables = {
  storeId: string;
};

export type TemperatureNotificationsResult = {
  temperatureNotifications: ({
  __typename: "TemperatureNotificationConnector";
} & {
  breaches: {
  totalCount: number;
  nodes: Array<{
  id: string;
  sensorId: string;
  sensor: {
  id: string;
  name: string;
} | null;
  startDatetime: string;
  location: {
  id: string;
  name: string;
} | null;
  maxOrMinTemperature: number | null;
}>;
};
  excursions: {
  totalCount: number;
  nodes: Array<{
  id: string;
  sensorId: string;
  sensor: {
  id: string;
  name: string;
} | null;
  startDatetime: string;
  location: {
  id: string;
  name: string;
} | null;
  maxOrMinTemperature: number;
}>;
};
});
};

export const TemperatureNotifications = {
  query: "query temperatureNotifications($storeId: String!) {\n  temperatureNotifications(storeId: $storeId, page: {first: 1}) {\n    ... on TemperatureNotificationConnector {\n      __typename\n      breaches {\n        totalCount\n        nodes {\n          id\n          sensorId\n          sensor {\n            id\n            name\n          }\n          startDatetime\n          location {\n            id\n            name\n          }\n          maxOrMinTemperature\n        }\n      }\n      excursions {\n        totalCount\n        nodes {\n          id\n          sensorId\n          sensor {\n            id\n            name\n          }\n          startDatetime\n          location {\n            id\n            name\n          }\n          maxOrMinTemperature\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<TemperatureNotificationsResult, TemperatureNotificationsVariables>;

export type UpdateTemperatureBreachVariables = {
  storeId: string;
  input: {
    id: string;
    unacknowledged: boolean;
    comment?: string | null;
  };
};

export type UpdateTemperatureBreachResult = {
  updateTemperatureBreach: (TemperatureBreachRowFragment);
};

export const UpdateTemperatureBreach = {
  query: "mutation updateTemperatureBreach($storeId: String!, $input: UpdateTemperatureBreachInput!) {\n  updateTemperatureBreach(storeId: $storeId, input: $input) {\n    ... on TemperatureBreachNode {\n      ...TemperatureBreachRow\n    }\n  }\n}\n\nfragment TemperatureBreachRow on TemperatureBreachNode {\n  __typename\n  id\n  sensorId\n  sensor {\n    id\n    name\n  }\n  startDatetime\n  endDatetime\n  unacknowledged\n  durationMilliseconds\n  type\n  location {\n    id\n    code\n    name\n  }\n  maxOrMinTemperature\n  comment\n}",
} as TypedDocument<UpdateTemperatureBreachResult, UpdateTemperatureBreachVariables>;

export type SensorNameVariables = {
  storeId: string;
  id: string;
};

export type SensorNameResult = {
  sensors: ({
  __typename: "SensorConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const SensorName = {
  query: "query sensorName($storeId: String!, $id: String!) {\n  sensors(storeId: $storeId, filter: {id: {equalTo: $id}}, page: {first: 1}) {\n    ... on SensorConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<SensorNameResult, SensorNameVariables>;
