/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../api/graphql";

export type FrontendPluginMetadataVariables = Record<string, never>;

export type FrontendPluginMetadataResult = {
  frontendPluginMetadata: Array<{
  code: string;
  path: string;
  hash: string;
}>;
};

export const FrontendPluginMetadata = {
  query: "query frontendPluginMetadata {\n  frontendPluginMetadata {\n    code\n    path\n    hash\n  }\n}",
} as TypedDocument<FrontendPluginMetadataResult, FrontendPluginMetadataVariables>;
