/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../api/graphql";

export type FrontendPluginMetadataVariables = {
  pluginApiVersion?: number | null;
  pluginApiMinSupported?: number | null;
};

export type FrontendPluginMetadataResult = {
  frontendPluginMetadata: Array<{
  code: string;
  path: string;
  hash: string;
}>;
};

export const FrontendPluginMetadata = {
  query: "query frontendPluginMetadata($pluginApiVersion: Int, $pluginApiMinSupported: Int) {\n  frontendPluginMetadata(\n    pluginApiVersion: $pluginApiVersion\n    pluginApiMinSupported: $pluginApiMinSupported\n  ) {\n    code\n    path\n    hash\n  }\n}",
} as TypedDocument<FrontendPluginMetadataResult, FrontendPluginMetadataVariables>;
