#[cfg(feature = "postgres")]
pub(crate) const DATE: &str = "DATE";
#[cfg(not(feature = "postgres"))]
pub(crate) const DATE: &str = "TEXT";
#[cfg(feature = "postgres")]
pub(crate) const DATETIME: &str = "TIMESTAMP";
#[cfg(not(feature = "postgres"))]
pub(crate) const DATETIME: &str = "TEXT";
#[cfg(feature = "postgres")]
pub(crate) const DOUBLE: &str = "DOUBLE PRECISION";
#[cfg(not(feature = "postgres"))]
pub(crate) const DOUBLE: &str = "REAL";
#[cfg(feature = "postgres")]
pub(crate) const DEFAULT_TIMESTAMP: &str = "'epoch'";
#[cfg(not(feature = "postgres"))]
pub(crate) const DEFAULT_TIMESTAMP: &str = "0";
#[cfg(feature = "postgres")]
pub(crate) const JSON: &str = "TEXT"; // Should be JSONB Ideally, but difficult to use with diesel
#[cfg(not(feature = "postgres"))]
pub(crate) const JSON: &str = "TEXT";
