use super::DeletePrescriptionError;
use crate::invoice::{
    check_invoice_exists, check_invoice_is_editable, check_invoice_type, check_store,
};
use repository::{InvoiceRow, InvoiceType, StorageConnection};

pub fn validate(
    id: &str,
    store_id: &str,
    connection: &StorageConnection,
) -> Result<InvoiceRow, DeletePrescriptionError> {
    use DeletePrescriptionError::*;

    let invoice = check_invoice_exists(id, connection)?.ok_or(InvoiceDoesNotExist)?;
    if !check_store(&invoice, store_id) {
        return Err(NotThisStoreInvoice);
    }
    if !check_invoice_is_editable(&invoice) {
        return Err(CannotEditFinalised);
    }
    if !check_invoice_type(&invoice, InvoiceType::Prescription) {
        return Err(NotAPrescriptionInvoice);
    }
    // A dispensation generated by a hand-over is the only record of that
    // request ever being filled: deleting it would strand the request on Ready
    // to dispense with nothing left to dispense against, and nothing in the
    // prescriber's screens can make another one. Cancelling the dispensation
    // once it is Verified is the supported way out.
    if invoice.prescription_request_id.is_some() {
        return Err(CannotDeleteGeneratedDispensation);
    }

    Ok(invoice)
}
