/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type ImmunisationProgramsVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    contextId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isImmunisation?: boolean | null;
    existsForStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    elmisCode?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
  sort?: {
    key: "name";
    desc?: boolean | null;
  } | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type ImmunisationProgramsResult = {
  programs: ({
  __typename: "ProgramConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  name: string;
  vaccineCourses: Array<{
  id: string;
  name: string;
}> | null;
}>;
});
};

export const ImmunisationPrograms = {
  query: "query immunisationPrograms($storeId: String!, $filter: ProgramFilterInput, $sort: ProgramSortInput, $page: PaginationInput) {\n  programs(storeId: $storeId, filter: $filter, sort: $sort, page: $page) {\n    ... on ProgramConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        name\n        vaccineCourses {\n          id\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<ImmunisationProgramsResult, ImmunisationProgramsVariables>;

export type ImmunisationProgramVariables = {
  storeId: string;
  id: string;
};

export type ImmunisationProgramResult = {
  programs: ({
  __typename: "ProgramConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const ImmunisationProgram = {
  query: "query immunisationProgram($storeId: String!, $id: String!) {\n  programs(\n    storeId: $storeId\n    filter: {id: {equalTo: $id}, isImmunisation: true}\n    page: {first: 1}\n  ) {\n    ... on ProgramConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<ImmunisationProgramResult, ImmunisationProgramVariables>;

export type VaccineCourseRowsVariables = {
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    programId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
  sort?: Array<{
    key: "name";
    desc?: boolean | null;
  }> | null;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
};

export type VaccineCourseRowsResult = {
  vaccineCourses: ({
  __typename: "VaccineCourseConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  name: string;
  demographic: {
  id: string;
  name: string;
} | null;
  vaccineCourseDoses: Array<{
  id: string;
}> | null;
}>;
});
};

export const VaccineCourseRows = {
  query: "query vaccineCourseRows($filter: VaccineCourseFilterInput, $sort: [VaccineCourseSortInput!], $page: PaginationInput) {\n  vaccineCourses(filter: $filter, sort: $sort, page: $page) {\n    ... on VaccineCourseConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        name\n        demographic {\n          id\n          name\n        }\n        vaccineCourseDoses {\n          id\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<VaccineCourseRowsResult, VaccineCourseRowsVariables>;

export type VaccineCourseForEditVariables = {
  id: string;
};

export type VaccineCourseForEditResult = {
  vaccineCourses: ({
  __typename: "VaccineCourseConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
  programId: string;
  demographicId: string | null;
  coverageRate: number;
  wastageRate: number;
  useInGapsCalculations: boolean;
  canSkipDose: boolean;
  demographic: {
  id: string;
  name: string;
} | null;
  vaccineCourseItems: Array<{
  id: string;
  itemId: string;
  name: string;
}> | null;
  vaccineCourseDoses: Array<{
  id: string;
  label: string;
  minAgeMonths: number;
  maxAgeMonths: number;
  customAgeLabel: string | null;
  minIntervalDays: number;
}> | null;
  storeConfigs: Array<{
  id: string;
  storeId: string;
  wastageRate: number | null;
  coverageRate: number | null;
}> | null;
}>;
});
};

export const VaccineCourseForEdit = {
  query: "query vaccineCourseForEdit($id: String!) {\n  vaccineCourses(filter: {id: {equalTo: $id}}, page: {first: 1}) {\n    ... on VaccineCourseConnector {\n      __typename\n      nodes {\n        id\n        name\n        programId\n        demographicId\n        coverageRate\n        wastageRate\n        useInGapsCalculations\n        canSkipDose\n        demographic {\n          id\n          name\n        }\n        vaccineCourseItems {\n          id\n          itemId\n          name\n        }\n        vaccineCourseDoses {\n          id\n          label\n          minAgeMonths\n          maxAgeMonths\n          customAgeLabel\n          minIntervalDays\n        }\n        storeConfigs {\n          id\n          storeId\n          wastageRate\n          coverageRate\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<VaccineCourseForEditResult, VaccineCourseForEditVariables>;

export type DemographicGroupsVariables = {
  storeId: string;
};

export type DemographicGroupsResult = {
  demographics: ({
  __typename: "DemographicConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const DemographicGroups = {
  query: "query demographicGroups($storeId: String!) {\n  demographics(\n    storeId: $storeId\n    page: {first: 1000}\n    sort: [{key: name, desc: false}]\n  ) {\n    ... on DemographicConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<DemographicGroupsResult, DemographicGroupsVariables>;

export type VaccineItemsVariables = {
  storeId: string;
};

export type VaccineItemsResult = {
  items: ({
  __typename: "ItemConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const VaccineItems = {
  query: "query vaccineItems($storeId: String!) {\n  items(\n    storeId: $storeId\n    filter: {isVaccine: true, isActive: true, isVisible: true}\n    sort: [{key: name, desc: false}]\n    page: {first: 1000}\n  ) {\n    ... on ItemConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<VaccineItemsResult, VaccineItemsVariables>;

export type StoresForRatesVariables = Record<string, never>;

export type StoresForRatesResult = {
  stores: ({
  __typename: "StoreConnector";
} & {
  totalCount: number;
  nodes: Array<{
  id: string;
  code: string;
  storeName: string;
}>;
});
};

export const StoresForRates = {
  query: "query storesForRates {\n  stores(sort: [{key: name, desc: false}], page: {first: 1000}) {\n    ... on StoreConnector {\n      __typename\n      totalCount\n      nodes {\n        id\n        code\n        storeName\n      }\n    }\n  }\n}",
} as TypedDocument<StoresForRatesResult, StoresForRatesVariables>;

export type InsertVaccineCourseVariables = {
  storeId: string;
  input: {
    id: string;
    name: string;
    programId: string;
    vaccineItems: Array<{
    id: string;
    itemId: string;
  }>;
    doses: Array<{
    id: string;
    label: string;
    minAge: number;
    maxAge: number;
    minIntervalDays: number;
    customAgeLabel?: string | null;
  }>;
    storeConfigs?: Array<{
    id: string;
    storeId: string;
    wastageRate?: {
    value?: number | null;
  } | null;
    coverageRate?: {
    value?: number | null;
  } | null;
  }> | null;
    demographicId?: string | null;
    coverageRate: number;
    useInGapsCalculations: boolean;
    wastageRate: number;
    canSkipDose: boolean;
  };
};

export type InsertVaccineCourseResult = {
  centralServer: {
  vaccineCourse: {
  insertVaccineCourse: ({
  __typename: "VaccineCourseNode";
} & {
  id: string;
  name: string;
}) | ({
  __typename: "InsertVaccineCourseError";
} & {
  error: {
  __typename: "RecordAlreadyExist" | "RecordProgramCombinationAlreadyExists";
  description: string;
};
});
};
};
};

export const InsertVaccineCourse = {
  query: "mutation insertVaccineCourse($storeId: String!, $input: InsertVaccineCourseInput!) {\n  centralServer {\n    vaccineCourse {\n      insertVaccineCourse(storeId: $storeId, input: $input) {\n        __typename\n        ... on VaccineCourseNode {\n          id\n          name\n        }\n        ... on InsertVaccineCourseError {\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<InsertVaccineCourseResult, InsertVaccineCourseVariables>;

export type UpdateVaccineCourseVariables = {
  storeId: string;
  input: {
    id: string;
    name?: string | null;
    vaccineItems: Array<{
    id: string;
    itemId: string;
  }>;
    doses: Array<{
    id: string;
    label: string;
    minAge: number;
    maxAge: number;
    minIntervalDays: number;
    customAgeLabel?: string | null;
  }>;
    storeConfigs?: Array<{
    id: string;
    storeId: string;
    wastageRate?: {
    value?: number | null;
  } | null;
    coverageRate?: {
    value?: number | null;
  } | null;
  }> | null;
    demographicId?: string | null;
    coverageRate: number;
    useInGapsCalculations: boolean;
    wastageRate: number;
    canSkipDose?: boolean | null;
  };
};

export type UpdateVaccineCourseResult = {
  centralServer: {
  vaccineCourse: {
  updateVaccineCourse: ({
  __typename: "VaccineCourseNode";
} & {
  id: string;
  name: string;
}) | ({
  __typename: "UpdateVaccineCourseError";
} & {
  error: {
  __typename: "RecordProgramCombinationAlreadyExists" | "VaccineDosesInUse";
  description: string;
};
});
};
};
};

export const UpdateVaccineCourse = {
  query: "mutation updateVaccineCourse($storeId: String!, $input: UpdateVaccineCourseInput!) {\n  centralServer {\n    vaccineCourse {\n      updateVaccineCourse(storeId: $storeId, input: $input) {\n        __typename\n        ... on VaccineCourseNode {\n          id\n          name\n        }\n        ... on UpdateVaccineCourseError {\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<UpdateVaccineCourseResult, UpdateVaccineCourseVariables>;

export type DeleteVaccineCourseVariables = {
  vaccineCourseId: string;
};

export type DeleteVaccineCourseResult = {
  centralServer: {
  vaccineCourse: {
  deleteVaccineCourse: ({
  __typename: "DeleteResponse";
} & {
  id: string;
}) | ({
  __typename: "DeleteVaccineCourseError";
} & {
  error: {
  __typename: "VaccineCourseInUse";
  description: string;
};
});
};
};
};

export const DeleteVaccineCourse = {
  query: "mutation deleteVaccineCourse($vaccineCourseId: String!) {\n  centralServer {\n    vaccineCourse {\n      deleteVaccineCourse(vaccineCourseId: $vaccineCourseId) {\n        __typename\n        ... on DeleteResponse {\n          id\n        }\n        ... on DeleteVaccineCourseError {\n          error {\n            __typename\n            description\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<DeleteVaccineCourseResult, DeleteVaccineCourseVariables>;
