/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type InsurancePolicyFragment = {
  __typename: "InsurancePolicyNode";
  id: string;
  insuranceProviderId: string;
  policyNumberPerson: string | null;
  policyNumberFamily: string | null;
  policyNumber: string;
  policyType: "PERSONAL" | "BUSINESS";
  discountPercentage: number;
  expiryDate: string;
  isActive: boolean;
  nameOfInsured: string | null;
  insuranceProviders: {
  __typename: "InsuranceProviderNode";
  id: string;
  providerName: string;
} | null;
};

export type InsurancePoliciesVariables = {
  storeId: string;
  nameId: string;
  sort?: Array<{
    key: "expiryDate" | "isActive";
    desc?: boolean | null;
  }> | null;
};

export type InsurancePoliciesResult = {
  insurancePolicies: ({
  __typename: "InsuranceConnector";
} & {
  nodes: Array<InsurancePolicyFragment>;
});
};

export const InsurancePolicies = {
  query: "query insurancePolicies($storeId: String!, $nameId: String!, $sort: [InsuranceSortInput!]) {\n  insurancePolicies(storeId: $storeId, nameId: $nameId, sort: $sort) {\n    ... on InsuranceConnector {\n      __typename\n      nodes {\n        ...InsurancePolicy\n      }\n    }\n  }\n}\n\nfragment InsurancePolicy on InsurancePolicyNode {\n  __typename\n  id\n  insuranceProviderId\n  policyNumberPerson\n  policyNumberFamily\n  policyNumber\n  policyType\n  discountPercentage\n  expiryDate\n  isActive\n  nameOfInsured\n  insuranceProviders {\n    __typename\n    id\n    providerName\n  }\n}",
} as TypedDocument<InsurancePoliciesResult, InsurancePoliciesVariables>;

export type InsuranceProvidersVariables = {
  storeId: string;
};

export type InsuranceProvidersResult = {
  insuranceProviders: ({
  __typename: "InsuranceProvidersConnector";
} & {
  nodes: Array<{
  __typename: "InsuranceProvidersNode";
  id: string;
  providerName: string;
}>;
});
};

export const InsuranceProviders = {
  query: "query insuranceProviders($storeId: String!) {\n  insuranceProviders(storeId: $storeId) {\n    ... on InsuranceProvidersConnector {\n      __typename\n      nodes {\n        __typename\n        id\n        providerName\n      }\n    }\n  }\n}",
} as TypedDocument<InsuranceProvidersResult, InsuranceProvidersVariables>;

export type InsertInsuranceVariables = {
  storeId: string;
  input: {
    id: string;
    nameId: string;
    insuranceProviderId: string;
    policyNumberPerson: string;
    policyNumberFamily: string;
    policyType: "PERSONAL" | "BUSINESS";
    discountPercentage: number;
    expiryDate: string;
    isActive: boolean;
    nameOfInsured?: string | null;
  };
};

export type InsertInsuranceResult = {
  insertInsurance: ({
  __typename: "IdResponse";
} & {
  id: string;
});
};

export const InsertInsurance = {
  query: "mutation insertInsurance($storeId: String!, $input: InsertInsuranceInput!) {\n  insertInsurance(storeId: $storeId, input: $input) {\n    ... on IdResponse {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<InsertInsuranceResult, InsertInsuranceVariables>;

export type UpdateInsuranceVariables = {
  storeId: string;
  input: {
    id: string;
    insuranceProviderId?: string | null;
    policyType?: "PERSONAL" | "BUSINESS" | null;
    discountPercentage?: number | null;
    expiryDate?: string | null;
    isActive?: boolean | null;
    nameOfInsured?: string | null;
  };
};

export type UpdateInsuranceResult = {
  updateInsurance: ({
  __typename: "IdResponse";
} & {
  id: string;
});
};

export const UpdateInsurance = {
  query: "mutation updateInsurance($storeId: String!, $input: UpdateInsuranceInput!) {\n  updateInsurance(storeId: $storeId, input: $input) {\n    ... on IdResponse {\n      __typename\n      id\n    }\n  }\n}",
} as TypedDocument<UpdateInsuranceResult, UpdateInsuranceVariables>;
