/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type LinkPurchaseOrderRowFragment = {
  id: string;
  number: number;
  reference: string | null;
  comment: string | null;
  status: "NEW" | "REQUEST_APPROVAL" | "CONFIRMED" | "SENT" | "FINALISED";
  supplier: {
  id: string;
  name: string;
  code: string;
} | null;
};

export type InsertInboundShipmentVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    onHold?: boolean | null;
    comment?: string | null;
    theirReference?: string | null;
    colour?: string | null;
    requisitionId?: string | null;
    purchaseOrderId?: string | null;
    insertLinesFromPurchaseOrder?: boolean | null;
  };
};

export type InsertInboundShipmentResult = {
  insertInboundShipment: ({
  __typename: "InvoiceNode";
} & {
  id: string;
  invoiceNumber: number;
}) | ({
  __typename: "InsertInboundShipmentError";
} & {
  error: {
  __typename: "OtherPartyNotASupplier" | "OtherPartyNotVisible";
  description: string;
};
});
};

export const InsertInboundShipment = {
  query: "mutation insertInboundShipment($storeId: String!, $input: InsertInboundShipmentInput!) {\n  insertInboundShipment(storeId: $storeId, input: $input) {\n    __typename\n    ... on InvoiceNode {\n      id\n      invoiceNumber\n    }\n    ... on InsertInboundShipmentError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertInboundShipmentResult, InsertInboundShipmentVariables>;

export type InsertInboundShipmentExternalVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    onHold?: boolean | null;
    comment?: string | null;
    theirReference?: string | null;
    colour?: string | null;
    requisitionId?: string | null;
    purchaseOrderId?: string | null;
    insertLinesFromPurchaseOrder?: boolean | null;
  };
};

export type InsertInboundShipmentExternalResult = {
  insertInboundShipmentExternal: ({
  __typename: "InvoiceNode";
} & {
  id: string;
  invoiceNumber: number;
}) | ({
  __typename: "InsertInboundShipmentError";
} & {
  error: {
  __typename: "OtherPartyNotASupplier" | "OtherPartyNotVisible";
  description: string;
};
});
};

export const InsertInboundShipmentExternal = {
  query: "mutation insertInboundShipmentExternal($storeId: String!, $input: InsertInboundShipmentInput!) {\n  insertInboundShipmentExternal(storeId: $storeId, input: $input) {\n    __typename\n    ... on InvoiceNode {\n      id\n      invoiceNumber\n    }\n    ... on InsertInboundShipmentError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertInboundShipmentExternalResult, InsertInboundShipmentExternalVariables>;

export type DuplicateInboundShipmentVariables = {
  storeId: string;
  id: string;
};

export type DuplicateInboundShipmentResult = {
  duplicateInboundShipment: ({
  __typename: "DuplicateInboundShipmentNode";
} & {
  invoice: {
  id: string;
  invoiceNumber: number;
};
  skippedItemCount: number;
}) | ({
  __typename: "DuplicateInboundShipmentError";
} & {
  error: {
  __typename: "SupplierIsInactive";
  description: string;
};
});
};

export const DuplicateInboundShipment = {
  query: "mutation duplicateInboundShipment($storeId: String!, $id: String!) {\n  duplicateInboundShipment(storeId: $storeId, id: $id) {\n    __typename\n    ... on DuplicateInboundShipmentNode {\n      invoice {\n        id\n        invoiceNumber\n      }\n      skippedItemCount\n    }\n    ... on DuplicateInboundShipmentError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<DuplicateInboundShipmentResult, DuplicateInboundShipmentVariables>;

export type SentPurchaseOrdersVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    createdDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    status?: {
    equalTo?: "NEW" | "REQUEST_APPROVAL" | "CONFIRMED" | "SENT" | "FINALISED" | null;
    equalAny?: Array<"NEW" | "REQUEST_APPROVAL" | "CONFIRMED" | "SENT" | "FINALISED"> | null;
    notEqualTo?: "NEW" | "REQUEST_APPROVAL" | "CONFIRMED" | "SENT" | "FINALISED" | null;
    notEqualAll?: Array<"NEW" | "REQUEST_APPROVAL" | "CONFIRMED" | "SENT" | "FINALISED"> | null;
  } | null;
    supplier?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    confirmedDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    requestedDeliveryDate?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
    sentDatetime?: {
    equalTo?: string | null;
    beforeOrEqualTo?: string | null;
    afterOrEqualTo?: string | null;
  } | null;
  } | null;
};

export type SentPurchaseOrdersResult = {
  purchaseOrders: ({
  __typename: "PurchaseOrderConnector";
} & {
  totalCount: number;
  nodes: Array<LinkPurchaseOrderRowFragment>;
});
};

export const SentPurchaseOrders = {
  query: "query sentPurchaseOrders($storeId: String!, $filter: PurchaseOrderFilterInput) {\n  purchaseOrders(\n    storeId: $storeId\n    filter: $filter\n    sort: [{key: number, desc: true}]\n  ) {\n    ... on PurchaseOrderConnector {\n      __typename\n      totalCount\n      nodes {\n        ...LinkPurchaseOrderRow\n      }\n    }\n  }\n}\n\nfragment LinkPurchaseOrderRow on PurchaseOrderNode {\n  id\n  number\n  reference\n  comment\n  status\n  supplier {\n    id\n    name\n    code\n  }\n}",
} as TypedDocument<SentPurchaseOrdersResult, SentPurchaseOrdersVariables>;
