/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type LocationsVariables = {
  storeId: string;
  filter?: {
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    codeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    onHold?: boolean | null;
    assignedToAsset?: boolean | null;
    storeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationTypeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
};

export type LocationsResult = {
  locations: ({
  __typename: "LocationConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  locationType: {
  id: string;
  name: string;
} | null;
}>;
});
};

export const Locations = {
  query: "query locations($storeId: String!, $filter: LocationFilterInput) {\n  locations(storeId: $storeId, filter: $filter, sort: [{key: name}]) {\n    ... on LocationConnector {\n      __typename\n      nodes {\n        id\n        code\n        name\n        locationType {\n          id\n          name\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<LocationsResult, LocationsVariables>;

export type LocationsWithVolumeVariables = {
  storeId: string;
};

export type LocationsWithVolumeResult = {
  locations: ({
  __typename: "LocationConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  onHold: boolean;
  volume: number;
  volumeUsed: number;
  locationType: {
  id: string;
  name: string;
} | null;
  stock: {
  __typename: "StockLineConnector";
  totalCount: number;
};
}>;
});
};

export const LocationsWithVolume = {
  query: "query locationsWithVolume($storeId: String!) {\n  locations(storeId: $storeId, sort: [{key: name}]) {\n    ... on LocationConnector {\n      __typename\n      nodes {\n        id\n        code\n        name\n        onHold\n        volume\n        volumeUsed\n        locationType {\n          id\n          name\n        }\n        stock {\n          ... on StockLineConnector {\n            __typename\n            totalCount\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<LocationsWithVolumeResult, LocationsWithVolumeVariables>;
