/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type LocationsVariables = {
  storeId: string;
};

export type LocationsResult = {
  locations: ({
  __typename: "LocationConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  name: string;
}>;
});
};

export const Locations = {
  query: "query locations($storeId: String!) {\n  locations(storeId: $storeId) {\n    ... on LocationConnector {\n      __typename\n      nodes {\n        id\n        code\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<LocationsResult, LocationsVariables>;

export type LocationsWithVolumeVariables = {
  storeId: string;
};

export type LocationsWithVolumeResult = {
  locations: ({
  __typename: "LocationConnector";
} & {
  nodes: Array<{
  id: string;
  code: string;
  name: string;
  onHold: boolean;
  volume: number;
  volumeUsed: number;
  stock: {
  __typename: "StockLineConnector";
  totalCount: number;
};
}>;
});
};

export const LocationsWithVolume = {
  query: "query locationsWithVolume($storeId: String!) {\n  locations(storeId: $storeId) {\n    ... on LocationConnector {\n      __typename\n      nodes {\n        id\n        code\n        name\n        onHold\n        volume\n        volumeUsed\n        stock {\n          ... on StockLineConnector {\n            __typename\n            totalCount\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<LocationsWithVolumeResult, LocationsWithVolumeVariables>;
