/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../../api/graphql";

export type InternalOrderProgramSettingsVariables = {
  storeId: string;
};

export type InternalOrderProgramSettingsResult = {
  supplierProgramRequisitionSettings: Array<{
  programId: string;
  programName: string;
  tagName: string;
  suppliers: Array<{
  id: string;
  name: string;
  isOnHold: boolean;
}>;
  orderTypes: Array<{
  id: string;
  name: string;
  isEmergency: boolean;
  availablePeriods: Array<{
  id: string;
  name: string;
}>;
}>;
}>;
};

export const InternalOrderProgramSettings = {
  query: "query internalOrderProgramSettings($storeId: String!) {\n  supplierProgramRequisitionSettings(storeId: $storeId) {\n    programId\n    programName\n    tagName\n    suppliers {\n      id\n      name\n      isOnHold\n    }\n    orderTypes {\n      id\n      name\n      isEmergency\n      availablePeriods {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<InternalOrderProgramSettingsResult, InternalOrderProgramSettingsVariables>;

export type RecentStocktakeItemsVariables = {
  storeId: string;
  onOrAfter?: string | null;
};

export type RecentStocktakeItemsResult = {
  stocktakes: ({
  __typename: "StocktakeConnector";
} & {
  nodes: Array<{
  id: string;
  lines: {
  nodes: Array<{
  itemId: string;
}>;
};
}>;
});
};

export const RecentStocktakeItems = {
  query: "query recentStocktakeItems($storeId: String!, $onOrAfter: NaiveDate) {\n  stocktakes(\n    storeId: $storeId\n    filter: {stocktakeDate: {afterOrEqualTo: $onOrAfter}, status: {equalTo: FINALISED}}\n  ) {\n    ... on StocktakeConnector {\n      __typename\n      nodes {\n        id\n        lines {\n          nodes {\n            itemId\n          }\n        }\n      }\n    }\n  }\n}",
} as TypedDocument<RecentStocktakeItemsResult, RecentStocktakeItemsVariables>;

export type InsertInternalOrderVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    colour?: string | null;
    theirReference?: string | null;
    comment?: string | null;
    maxMonthsOfStock: number;
    minMonthsOfStock: number;
    expectedDeliveryDate?: string | null;
  };
};

export type InsertInternalOrderResult = {
  insertRequestRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
}) | ({
  __typename: "InsertRequestRequisitionError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const InsertInternalOrder = {
  query: "mutation insertInternalOrder($storeId: String!, $input: InsertRequestRequisitionInput!) {\n  insertRequestRequisition(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionNode {\n      id\n    }\n    ... on InsertRequestRequisitionError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertInternalOrderResult, InsertInternalOrderVariables>;

export type InsertProgramInternalOrderVariables = {
  storeId: string;
  input: {
    id: string;
    otherPartyId: string;
    colour?: string | null;
    theirReference?: string | null;
    comment?: string | null;
    programOrderTypeId: string;
    periodId: string;
    expectedDeliveryDate?: string | null;
  };
};

export type InsertProgramInternalOrderResult = {
  insertProgramRequestRequisition: ({
  __typename: "RequisitionNode";
} & {
  id: string;
}) | ({
  __typename: "InsertProgramRequestRequisitionError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const InsertProgramInternalOrder = {
  query: "mutation insertProgramInternalOrder($storeId: String!, $input: InsertProgramRequestRequisitionInput!) {\n  insertProgramRequestRequisition(storeId: $storeId, input: $input) {\n    __typename\n    ... on RequisitionNode {\n      id\n    }\n    ... on InsertProgramRequestRequisitionError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<InsertProgramInternalOrderResult, InsertProgramInternalOrderVariables>;
