/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../../api/graphql";

export type StoreFacilityVariables = {
  storeId: string;
  nameId: string;
};

export type StoreFacilityResult = {
  names: ({
  __typename: "NameConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
  code: string;
  properties: string;
}>;
});
};

export const StoreFacility = {
  query: "query storeFacility($storeId: String!, $nameId: String!) {\n  names(storeId: $storeId, filter: {id: {equalTo: $nameId}}) {\n    ... on NameConnector {\n      __typename\n      nodes {\n        id\n        name\n        code\n        properties\n      }\n    }\n  }\n}",
} as TypedDocument<StoreFacilityResult, StoreFacilityVariables>;

export type UpdateNamePropertiesVariables = {
  storeId: string;
  id: string;
  properties: string;
};

export type UpdateNamePropertiesResult = {
  updateNameProperties: ({
  __typename: "NameNode";
} & {
  id: string;
  properties: string;
}) | ({
  __typename: "UpdateNamePropertiesError";
} & {
  error: {
  description: string;
};
});
};

export const UpdateNameProperties = {
  query: "mutation updateNameProperties($storeId: String!, $id: String!, $properties: String!) {\n  updateNameProperties(\n    storeId: $storeId\n    input: {id: $id, properties: $properties}\n  ) {\n    ... on NameNode {\n      __typename\n      id\n      properties\n    }\n    ... on UpdateNamePropertiesError {\n      __typename\n      error {\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<UpdateNamePropertiesResult, UpdateNamePropertiesVariables>;
