/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type MasterListsVariables = {
  storeId: string;
};

export type MasterListsResult = {
  masterLists: ({
  __typename: "MasterListConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const MasterLists = {
  query: "query masterLists($storeId: String!) {\n  masterLists(storeId: $storeId) {\n    ... on MasterListConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<MasterListsResult, MasterListsVariables>;
