/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type MasterListsVariables = {
  storeId: string;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    name?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    code?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    description?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    existsForName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    existsForNameId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    existsForStoreId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    isProgram?: boolean | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
};

export type MasterListsResult = {
  masterLists: ({
  __typename: "MasterListConnector";
} & {
  nodes: Array<{
  id: string;
  name: string;
}>;
});
};

export const MasterLists = {
  query: "query masterLists($storeId: String!, $filter: MasterListFilterInput) {\n  masterLists(storeId: $storeId, filter: $filter) {\n    ... on MasterListConnector {\n      __typename\n      nodes {\n        id\n        name\n      }\n    }\n  }\n}",
} as TypedDocument<MasterListsResult, MasterListsVariables>;
