import {
  ConfigureNamePropertyInput,
  PropertyNodeValueType,
} from '@common/types';

export const gapsNameProperties: ConfigureNamePropertyInput[] = [
  {
    id: 'supply_level',
    key: 'supply_level',
    name: 'Supply Level',
    valueType: PropertyNodeValueType.String,
    allowedValues: 'Primary,Sub-National,Lowest Distribution,Service Point',
    propertyId: 'supply_level',
    remoteEditable: false,
  },
  {
    id: 'facility_type',
    key: 'facility_type',
    name: 'Facility Type',
    valueType: PropertyNodeValueType.String,
    allowedValues:
      'National Vaccine Store,Regional Vaccine Store,Referral Hospital,Municipal Warehouse,Maternal Clinic',
    propertyId: 'facility_type',
    remoteEditable: false,
  },
  {
    id: 'ownership_type',
    key: 'ownership_type',
    name: 'Ownership Type',
    valueType: PropertyNodeValueType.String,
    allowedValues: 'Government,NGO,Private,Faith-based',
    propertyId: 'ownership_type',
    remoteEditable: false,
  },
  {
    id: 'population_served',
    key: 'population_served',
    name: 'Population Served',
    valueType: PropertyNodeValueType.Float,
    allowedValues: null,
    propertyId: 'population_served',
    remoteEditable: true,
  },
  {
    id: 'electricity_availability',
    key: 'electricity_availability',
    name: 'Electricity Availability',
    valueType: PropertyNodeValueType.String,
    allowedValues: '> 16 hours,8-16 hours,< 8 hours,No availability',
    propertyId: 'electricity_availability',
    remoteEditable: true,
  },
  {
    id: 'solar_availability',
    key: 'solar_availability',
    name: 'Solar Availability',
    valueType: PropertyNodeValueType.String,
    allowedValues: '> 16 hours,8-16 hours,< 8 hours,No availability',
    propertyId: 'solar_availability',
    remoteEditable: true,
  },
  {
    id: 'gas_availability',
    key: 'gas_availability',
    name: 'Gas Availability',
    valueType: PropertyNodeValueType.String,
    allowedValues: '> 16 hours,8-16 hours,< 8 hours,No availability',
    propertyId: 'gas_availability',
    remoteEditable: true,
  },
  {
    id: 'kerosene_availability',
    key: 'kerosene_availability',
    name: 'Kerosene Availability',
    valueType: PropertyNodeValueType.String,
    allowedValues: '> 16 hours,8-16 hours,< 8 hours,No availability',
    propertyId: 'kerosene_availability',
    remoteEditable: true,
  },
];
