name: Build standard reports

on:
  pull_request_target:
    types: [closed]
    paths:
      - "standard_reports/**"
      - "standard_forms/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build reports on"
        required: true
        default: "develop"

concurrency:
  group: build-standard-reports-${{ github.event.pull_request.base.ref || inputs.branch }}
  cancel-in-progress: true

jobs:
  build-reports:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref || inputs.branch }}
          token: ${{ secrets.JSON_SORT_PAT }}
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: server

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install standard_reports JS dependencies
        working-directory: ./standard_reports
        run: yarn install

      - name: Build reports
        working-directory: ./server
        run: cargo run --bin remote_server_cli -- build-reports

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.base.ref || inputs.branch }}
          commit_message: "chore: regenerate standard reports/forms"
          commit_options: "--no-verify"
          file_pattern: |
            standard_reports/generated/standard_reports.json
            standard_forms/generated/standard_forms.json
