name: Bundle size diff - Build

on:
  pull_request:
    paths:
      - "client/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat ./client/.nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: cd ./client && rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build
        run: cd ./client && yarn build-stats

      - name: Upload base stats.json
        uses: actions/upload-artifact@v4
        with:
          name: base
          path: ./client/packages/host/dist/stats.json
          retention-days: 3

  build-pr:
    name: Build PR
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat ./client/.nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: cd ./client && rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build
        run: cd ./client && yarn build-stats

      - name: Upload base stats.json
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./client/packages/host/dist/stats.json
          retention-days: 3
