name: Nightly Automated Builds
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 6 * * *" #  Every day at 6AM UTC which is 6PM NZDT

jobs:
  create-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tags for target branches
        run: |
          chmod +x .github/workflows/create-nightly-tags.sh
          .github/workflows/create-nightly-tags.sh
