on:
  workflow_dispatch:
  schedule:
    - cron: "30 7 * * 7" # Every Sunday at 7:30 PM UTC - equivalent to 7:30 AM NZST

name: Manual Cargo Clean

jobs:
  build_and_test:
    name: Run cargo clean against self-hosted
    runs-on: self-hosted
    timeout-minutes: 25
    steps:
      - name: Delete Postgres CARGO_TARGET_DIR
        run: rm -r /tmp/target/postgres
      - name: Delete Sqlite CARGO_TARGET_DIR
        run: rm -r /tmp/target/sqlite
