on: workflow_dispatch

name: Remote Server Mac Build

jobs:
  build_and_test:
    name: Remote Server Mac Build
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      RUSTFLAGS: '--cfg recursion_limit_256'
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Initialise
        working-directory: ./server
        run: cargo run --bin remote_server_cli -- initialise-from-export -n 'reference1' -r
      - name: Build
        run: ./build/mac/build.sh
      - uses: actions/upload-artifact@v6
        with:
          name: mac_sqlite
          path: |
            **_mac_sqlite
            server/omsupply-database