name: Sort JSON files

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  sort:
    name: Sort JSON locale files
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Sort files
        run: |
          chmod +x .github/workflows/sort-json.sh 
          .github/workflows/sort-json.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Sorted JSON translation files'
          commit_options: '--no-verify'
