name: Sort JSON files

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  sort:
    name: Sort JSON locale files
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Sort files
        run: |
          chmod +x .github/workflows/sort-json.sh 
          .github/workflows/sort-json.sh
      - name: Configure git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: git commit --no-verify -m 'Sorted JSON files'
