name: Trigger Plugin Tests

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to test'
        required: true
        type: string
    secrets:
      ORG_WORKFLOW_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to test'
        required: true
        type: string

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tests in plugin repositories
        run: |
          # List of repositories to trigger tests in
          REPOS=(
            "msupply-foundation/sao-tome-plugins"
            # Add more repositories as needed
          )
          
          for repo in "${REPOS[@]}"; do
            echo "Triggering test workflow in $repo with image tag: ${{ inputs.image_tag }}"
            
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.ORG_WORKFLOW_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$repo/actions/workflows/test.yml/dispatches \
              -d '{
                "ref": "main",
                "inputs": {
                  "image_tag": "${{ inputs.image_tag }}",
                  "branch": "Tests"
                }
              }'
            
            # Add a small delay between requests to avoid rate limiting
            sleep 2
          done