/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import type { TypedDocument } from "../../api/graphql";

export type StocktakeDetailVariables = {
  storeId: string;
  stocktakeId: string;
};

export type StocktakeDetailResult = {
  stocktake: ({
  __typename: "StocktakeNode";
} & {
  id: string;
  stocktakeNumber: number;
  status: "NEW" | "FINALISED";
  description: string | null;
  comment: string | null;
  isLocked: boolean;
  lines: {
  __typename: "StocktakeLineConnector";
  totalCount: number;
  nodes: Array<{
  id: string;
  itemName: string;
  item: {
  id: string;
  code: string;
};
  batch: string | null;
  expiryDate: string | null;
  snapshotNumberOfPacks: number;
  countedNumberOfPacks: number | null;
  comment: string | null;
}>;
};
}) | ({
  __typename: "NodeError";
} & {
  error: {
  __typename: string;
  description: string;
};
});
};

export const StocktakeDetail = {
  query: "query stocktakeDetail($storeId: String!, $stocktakeId: String!) {\n  stocktake(storeId: $storeId, id: $stocktakeId) {\n    __typename\n    ... on StocktakeNode {\n      id\n      stocktakeNumber\n      status\n      description\n      comment\n      isLocked\n      lines {\n        ... on StocktakeLineConnector {\n          __typename\n          totalCount\n          nodes {\n            id\n            itemName\n            item {\n              id\n              code\n            }\n            batch\n            expiryDate\n            snapshotNumberOfPacks\n            countedNumberOfPacks\n            comment\n          }\n        }\n      }\n    }\n    ... on NodeError {\n      error {\n        __typename\n        description\n      }\n    }\n  }\n}",
} as TypedDocument<StocktakeDetailResult, StocktakeDetailVariables>;
